lib/config/directory/homedir.go, lib/config/directory/homedir_test.go
Background:
bazel runs builds in a sandbox. astore commands need to be run in bazel.
From within the sandbox, there is no HOME env variable.
Problem:
before this change, the code relied solely on the HOME environment
variable to find user configurations.
After this change:
if an absolute home directory cannot be found through configdir, the
library that uses the HOME var, fall back to looking up the home directory
in nis by using the correct system call, via os/user.
Additionally:
- added a small test that verify the correct behavior.
- introduced a Refresh function to allow the test to be written.
=> fix: compute home directory correctly even in the absence of $HOME.

bazel/astore/defs.bzl
With the fix submitted to compute the HOME based on user configurations,
the workaround hard coding the environment variable is no longer necessary.
Additionally, remove a parameter that's no longer necessary.
=> astore bazel rules: remove hard coded home.

astore/client/astore/BUILD.bazel, astore/client/astore/delete.go, astore/client/commands/BUILD.bazel, astore/client/commands/commands.go, astore/client/commands/delete.go, astore/rpc/astore.proto, astore/server/astore/BUILD.bazel, astore/server/astore/delete.go, kbuild/kapt/controlurl.go, kbuild/main.go, lib/khttp/dispatch.go, lib/khttp/downloader/downloader.go, lib/khttp/kcache/cache.go, lib/oauth/ogithub/github.go
Currently:
- adds command with dry run flag
- adds proto stubs
Plan (detailed):
- finish client stubbing in `astore/client/astore/delete.go`
- add additional/remove flags? 
- implement guess sid or id from single string
- add raw delete functionality server side and unit test
- add delete to rpc server and implement e2e testing with client stubs
Future:
- Running garbage collection could just be a chronjobbed github action that reads the metadata from the remote and deletes as necessary. Linux runners are pretty much free.
- Altering the timestamps of files could be a good way to test this
- for e2e testing we can multistage an intermediate docker image and save code coverage across stages.
=> [WIP] initial draft of adding astore deletion

bazel/astore/defs.bzl
The bazel rule currently fails to download files not available for amd64-linux
(the default architecture that astore download looks for).
=> Add arch attribute to astore_download bazel rule

bazel/linux/defs.bzl
Add missing space between kernel directory and extra arguments
passed to the make command used internally by kernel_module_rule.
Specifying an extra argument while instantiating the rule, would cause
the argument to become interpreted as part of the kernel path instead of
additional args.
=> bazel/linux: add missing space to make template

bazel/linux/BUILD.bazel, bazel/linux/defs.bzl, bazel/linux/run_um_kunit_tests.sh
Introduce a bash script to run kernel unit tests inside a user-mode linux image
generated with KUnit enabled. To do that the scripts expects three parameters:
1. Path to the user-mode linux image
2. Path to the rootfs image
3. Path to the folder to expose as hostfs to the user-mode linux proces (this
can be used to expose test kernel modules to the running user-mode linux
process, so that it will be able to load and run them at runtime).
The new macro rule simplifies the work required to instantiate the underlying
sh_test rule: it defines the kernel module, linux and rootfs image as required
data to run the test, then passes their runtime paths to the bash script we
just introduced.
=> WIP: Add rule to declare and run kernel unit tests

bazel/linux/defs.bzl
Specify the module name to the make command used internally by the
kernel_module rule (+ refactor the command to make it easier on the eyes).
Our current make command works fine in cases where we define a single
kernel module in the Makefile/Kconfig file. Instead, in cases where
there are multiple modules defined in a single file (i.e., multiple
objects assigned to obj-m), it ends up compiling all of the modules
instead of the one specified my the kernel_module rule.
Specifying the module name, forces the Kbuild system to only build that
module.
=> bazel/linux: Specify module name in make command

bazel/linux/defs.bzl
I have finally found what I think is the best way of handling cross-attribute checks in a rule implementation function. This is documented in the MACRO section of the bazel documentation https://docs.bazel.build/versions/master/skylark/macros.html#errors.
=> bazel/linux: Better handling of kernel_test error

bazel/linux/run_um_kunit_tests.template
This should fix the cloudbuild issues. See bazel documentation related to $TEST_TMPDIR here https://docs.bazel.build/versions/master/test-encyclopedia.html#initial-conditions.
=> bazel/linux: add uml_dir arg to kunit test script

bazel/linux/README.md
Update the linux kernel bazel rules README to document what has changed with the new version of the kernel_test rule.
=> bazel/linux: Update README.md

bazel/go_repositories.bzl, go.mod, go.sum
This is necessary to run docker emulators, such as minio, opa, or docker-compose files.
=> add docker client as go dependency

bazel/utils/labels.bzl, bazel/utils/match.bzl, bazel/utils/transform.bzl, bazel/utils/transform/BUILD.bazel, bazel/utils/transform/transformer.sh
Background:
Bazel rules can generate "file artifacts", or "tree artifacts".
A file artifact is 1 bazel object, representing a file.
A tree artifact is 1 bazel object, representing a tree of files.
Individual files in tree artifacts are invisible to the rest of
the bazel rules, as they don't have a corresponding file object.
- modify the transform rule so that it can handle "tree artifacts",
and transform files from tree artifacts as per "include" and
"transform" parameters.
- add support for the "expand" attribute, so "transform" can be
used to break a "tree artifact" into independent "file artifacts"
or sub-"tree artifacts".
Additionally:
- Improve labels.bzl to handle paths that start fromt the root
of the label (wrong result was returned before).
- Add an helper …
=> bazel/utils/transform: add support for "tree artifacts".

kbuild/utils/generate_custom_archive.sh
Update the name of the generated .tar.gz file. It no longer adds -test
after KVER and instead allows the user to completely specify the name.
I.e., -v KVER will generate KVER.tar.gz.
=> kbuild/utils: fix generate_custom_archive output

lib/client/client.go, lib/kflags/flags.go, lib/kflags/kcobra/cobra.go
Problem:
Current flag initialization logic has the default flag values
set in the .go code, (possibly) overridden by env variable,
(possibly) overridden by parameters downloaded via http/astore.
Finally, the cobra handler parses the flags, and the final
value is set.
Every time flags change values, some objects need to be
re-created. For example: if log verbosity is changed, the
logger object needs to be re-created (well, or updated).
- the logger object was re-created when the DEFAULTS were
changed, but not when the final set of flags was loaded.
Pretty much causing some flags to be ignored when passed
from the command line (but not when defaulted from env
or from http configurations).
After this change:
- actually plumbed the object initialization logic with
current …
=> lib/kflags, lib/client: fix initialization bug.

lib/client/client.go, proxy/ptunnel/commands/tunnel.go, proxy/ptunnel/tunnel.go
Problem:
When credentials expire, even if refreshed, "enkit tunnel" is unable
to recover the session. This is because credentials are never reloaded
from disk.
- have commands/tunnel.go set things up so credentials are re-loaded
every time we attempt a connection, so the latest are always used.
- ... but stick to the last known valid credentials if loading fails.
Additionally:
- clarify logging slightly, so that the problem is clear for someone
looking at the log.
=> proxy/ptunnel: re-load credentials at every connection attempt.

lib/knetwork/BUILD.bazel, lib/knetwork/shutdown.go, proxy/nasshp/blocking.go, proxy/nasshp/browser.go, proxy/ptunnel/commands/BUILD.bazel, proxy/ptunnel/commands/tunnel.go, proxy/ptunnel/tunnel.go
Background:
Before this PR, the cleanup code on tunnel close was sketchy at best,
potentially leaking goroutines, leaving connections opened, and not
really propagating close() events correctly.
In this PR:
- try to propagate close and shutdown events correctly from web sockets.
If the web socket stops being readable, do a shutdown for write.
If the web socket stops being writable, do a shutdown for read.
This resulted in adding a couple utilities in knetwork/shutdown.go.
- close the client connection if the websocket dies.
Apart from the shutdown, the new code tries to close the socket
correctly when all is done.
- close the websocket with the server, and try to ensure the corresponding
routines. This is very tricky to get right, as the websockets library
used doesn't really have …
=> proxy/ptunnel,nasshp: significantly improved cleanup and error handling.

lib/retry/retry.go
After this change: there's always a log line printed when a retry is
performed, and a single log line, with all the detailed information.
=> lib/retry: minor logging improvement.

lib/goroutine/BUILD.bazel, lib/goroutine/gochan.go, lib/multierror/multierror.go
Specifically:
WaitAll() now returns a multierror rather than a plain array
of errors, only if an error was actually received.
multierror is expanded to have support for sparse arrays of errors,
eg, an array with some entries being nil (all good) and some entries
being actual errors.
Why?
1 - This allows WaitAll() to be used just like any other function,
it just returns an error, or nil if there are no errors.
Before, it always returned an array.
2 - This allows to chain WaitFirstError() and WaitAll() arbitrarily
Like: WaitAll(WaitFirstError(func1, WaitAll(func5, func6)), WaitAll(func3, func4))
and still have error propagation work correctly.
The cost on multierror should be negligible: people that were using
a contiguous array should have no additional cost. Sparse arrays are
slightly …
=> lib/goroutine, lib/multierror: minor API improvements.

bazel/linux/defs.bzl
Often kernel_tree_version fails due to the user not respecting the
package / install_script naming convention. With this commit we make the error
message less cryptic for that specific case.
=> bazel/linux/def.bzl: Better error messages

bazel/linux/defs.bzl
As a default "srcs" parameter, consider only the makefile parameter and
all the .c and .h files belonging to the package where the kernel_module
rule has been instatiated.
Currently, if the user doesn't specify the "srcs" parameter of the
kernel_module rule, the implementation will consider all files belonging
to the package to be the source files for that kernel module.
If for some reason, a file with the same name of one of the intermediate
build files pollutes the package, bazel will try to copy/link that over in
the build dir. This seems to cause a compilation failure since that file
could already exist there and that filesystem is read-only?
The bug can be reproduced, for example, by copying the module_name.mod.c
in the package source tree and modifying it (or the kernel module …
=> bazel/linux/defs.bzl: Fix kernel_module bug

kbuild/utils/generate_custom_archive.sh
Copy the tools folder as well from the custom kernel source tree.
Not doing that was causing the make rule to build .o file from .c
files not to execute. Which was causing an error message like:
make[1]: *** No rule to make target '', needed by '.  Stop.
=> kbuild/utils/generate_custom_archive.sh: Fix bug

astore/client/auth/auth.go, astore/server/auth/factory.go
Specifically: minor errors in log messages, don't use /etc/ssh pem file
by default. Better to have CA disabled than potentially use incorrect
certificates.
=> enkit/auth: minor cleanups.

bazel/utils/run_clang_format.template.sh
Delete the temporary .clang-format file created during the command execution.
Copy back the .clang-format.bk only if it exists.
---
This is a minor issue, it shouldn't be worthy of a new enkit release.
=> bazel/utils: Fix minor clang-format issue

kbuild/utils/README.md, kbuild/utils/buildroot_2020.11.2-Add-scripts-and-config-for-kunit-rootfs-image.patch
This buildroot patch allows the creation of a rootfs image that takes
care of automatically running all KUnit tests at startup.
See the patch commit message for more info.
=> kbuild/utils: Buildroot patch

astore/server/auth/BUILD.bazel, astore/server/auth/auth_test.go, astore/server/auth/factory.go
This PR adds a simple test to verify that:
1) The authentication still generates cookies.
2) The CA parameters are optional.
3) CA based generation works with both RSA and ED25519 keys.
=> astore/server/auth: add a few tests to verify formats of keys accepted.

astore/client/auth/auth.go, astore/rpc/auth.proto, astore/server/auth/auth.go, lib/kcerts/ssh.go, lib/oauth/oauth.go
I still need to test this but the code is here to review.
Public Key is send with the token request and not with the auth request:
Reason: The way that the auth requests cookie is sent would requrie significant refactoring in main.go of astore server.
Downside:  A public key isn't tied to a per login flow.
=> Change Auth Flow to not send Priv Key over the wire 

WORKSPACE, proxy/nss/BUILD.bazel, proxy/nss/README.md, proxy/nss/configs/certs.conf, proxy/nss/configs/nss-autouser.simple.conf, proxy/nss/configs/pam_script_acct, proxy/nss/configs/sshd, proxy/nss/confparse/BUILD.bazel, proxy/nss/confparse/README.md, proxy/nss/confparse/confparse.c, proxy/nss/confparse/confparse.h, proxy/nss/confparse/confparse_test.cc, proxy/nss/nss-autouser.c, proxy/nss/nss-autouser.h, proxy/nss/nss-autouser_test.cc, proxy/nss/testdata/advanced.conf, proxy/nss/testdata/simple.conf
This PR introduces:
- libnss-autouser, an nsswitch.conf module to allow automated
creation of users at login with ssh certificates.
- confparse, a small library for parsing ssh like configuration
files in C.
=> proxy/nss: add support for certificate authentication. 

astore/server/auth/auth.go
Corrects mistake where the public key was being deserialized using the wrong method.
=> add in correct parse public key, not using wire format

BUILD.bazel, astore/BUILD.bazel, astore/e2e_test.go, proxy/ptunnel/commands/BUILD.bazel, ui/ptunnel/BUILD.bazel
Over the last few weeks, we had a few changes that committed
code that did not build, or tests that did not succeed.
This PR makes most of the repo build again and pass tests again.
Specifically:
- split out the astore/server test from the astore/e2e test.
- mark the e2e test as a test that has to be run manually.
- fix a bunch of minor build issues in the test itself.
Without those changes, e2e did not build, prevented the
server test from being built and running, and made a global
run fail unless the dependencies had been manually installed.
- ptunnel had a missing kcerts dependency in the bazel file.
This made ptunnel not build with bazel.
- ui/ptunnel stuff is not building and not passing tests right now.
Manually fixed a trivial mistake, but that was not enough.
For now, I'm just …
=> Make bazel build and bazel test ...:all work again.

astore/client/auth/auth.go, astore/server/auth/BUILD.bazel, astore/server/auth/auth.go, astore/server/auth/auth_test.go, lib/kcerts/ssh.go
With recent changes to generate keys client side, and have them
signed by the server only, auth_test.go broke.
The new interface supported RSA keys only, while the test
verified ed25519 as well. I had two choices, either:
1) drop ed25519 support
2) do the minimal amount of work to have ed25519 supported.
I went for the latter route. This means:
- don't PEM encode the key in the client <-> server communication.
The ssh library is already marshalling them. This simplifies
the code, as there is no PEM encoding supported by ssh
for ed25519 keys at this point (eg, ssh-keygen -e -m PEM -f ed-key
will fail with an error like 'unsupported key format').
- change the interfaces so that some generics are passed
around. This is more error prone, as the golang compiler
can no longer warn us about a …
=> astore/server/auth/auth_test.go: make it work again.

proxy/nss/configs/pam_script_acct
Before this change: if AUTOUSER NSS was not involved with the login
of a user, the pam script would fail. This would cause existing users
in the normal passwd file to not be able to log in.
After this change: if AUTOUSER NSS was not involved with the login,
exit 0, to let pam continue with whatever it is doing, rather than
kicking the user out.
=> [bugfix]: pam_script_acct should exit 0 if autouser is not involved.

kbuild/utils/generate_custom_archive.sh
The Enfabrica kernel build separates the kernel config from the kernel
build output directory.  Previously, the archive script assumed the
kernel config had a specific path.  Thus the archive script and
Enfabrica kernel build layout were incompatible.
The change here is to add an option to the archive script to specify
the path of the kernel config.  The default maintains the previous
behaviour, assuming ".config" in the kernel build directory.
Also the kernel version parameter is now optional.  If not specified
the kernel version is taken from the kernel build directory, from
${SRCDIR}/include/config/kernel.release.
Signed-off-by: Curt Brune <curt@enfabrica.net>
=> kbuild: update custom archive script for use with enf kernel builds

astore/server/auth/factory.go
If no principals were specified, it would add []string{""} to principals instead of an empty string. This would lead to the certificate containing "", and the valid username. 
While this didn't affect functionality (since its invalid) just removes some dirty output from sshd since it causes some wonky errors.
=> Fixes HostCert Invalid

lib/kcerts/ssh.go
Background:
OpenSSH server (and this is an OpenSSH feature - other servers
don't necessarily implement it) allows the certificate to specify
what the user can and cannot do on the remote host.
Eg, can agent forwarding be used? can a pty be allocated?
This PR enables all extensions in ssh.
=> bugfix: allow the generated certs to allocate a pty.

lib/kauth/login.go
So since this got change to not be pem encoded:
https://github.com/enfabrica/enkit/blob/master/astore/server/auth/auth.go#L137 
This change is needed in order to be compatible. The code without this fix works with the current version of auth. Not sure if we want this to be cross compatible or not (e.g. retry with pem encoded).
=> Fix compat issue with future auth-server release

lib/kcerts/BUILD.bazel, lib/kcerts/ked25519/BUILD.bazel, lib/kcerts/ked25519/LICENSE, lib/kcerts/ked25519/cert.go, lib/kcerts/keys.go, lib/knetwork/BUILD.bazel
Right Now, if you ssh encode a ed25519 private key, it is invalid in sshd, but not ssh for some reason. 
Needs investigation, but this works with sshd.
=> Fix SSHD Weirdness on HostKeys

bazel/go_repositories.bzl
Upgrading the go_repo to v1.36.0 as part of the introduction of the license manager caused a regression that broke the container_image bazel rule as seen here https://github.com/enfabrica/enkit/commit/f78c01ce3cedb6247d2d90a0e73d7a698148faee. If I remember correctly, running `bazel run //:gazelle` updated a bunch of go repos automatically.
=> Revert org_golang_google_grpc to v1.32.0

bazel/linux/defs.bzl
Add a build rule for building the NVidia driver family of kernel
modules.  The NVidia kernel module build does not follow the model of
a stock kernel module build, so create a custom rule for it.
This new rule is inspired by the regular kernel module build rule,
modified to deal with the peculiarities of the NVidia build:
- builds multiple kernel modules from one master Makefile
- provides custom arguments to the NVidia Makefile
- builds a configuration test, that generates headers used by all the
kernel modules.
With this rule in place I can have a BUILD.bazel file for the NVidia driver
that looks like this, without any modifications to the original NVidia source:
```bazel
load("@enkit//bazel/linux:defs.bzl", "nv_driver")
#
#
#
nv_driver(
name = "nv_driver",
kernels = [ …
```
=> Add NVidia driver build rule

lib/kcerts/ssh.go
I think this was a legacy piece of code that got checked in
=> Hotfix Change Multiplier on Cert TTL

manager/client/main.go
Background:
As per https://golang.org/pkg/os/exec/#Cmd, if Stdout or Stderr are
not set, stdout and stderr are sent to /dev/null.
This discards all of our precious logs.
- do not discard stdout and stderr
=> ip-manager: don't discard stdout and stderr.

lib/client/client.go
This fixes a small error in a previous commit, where the code was
attempting to parse a string as if it was a bool. My bad, was
tested in a rush.
=> bugfix: strings are not bools.

proxy/ptunnel/tunnel_test.go
When some of the domain names resolved to IPv6, the test failed.
In this PR:
- use net.JoinHostPort() that works with IPv6.
- escape the generated whitelist patterns, so they don't take []
to mean "character class" in fnmatch style.
Additionally:
- minor logging changes, that helped debug the issue.
=> ptunnel: fix test in the presence of IPv6 records.

lib/oauth/cli/main.go, lib/oauth/factory.go, lib/oauth/oauth.go, lib/token/token.go
Tokens carried the time they were issued, but not the time they
expired. Deciding if a token was valid or not was entirely upon
the server receiving it.
- add the ability to encode an expiry time in each token.
- add support for two token formats, one with expiry, and one without.
- extend the context support to export more metadata.
- extend the previously introduced cli to print both token formats.
=> lib/token, lib/oauth: carry expiry time with tokens.

lib/oauth/cli/BUILD.bazel, lib/oauth/cli/main.go, lib/oauth/factory.go, lib/oauth/oauth.go, lib/token/token.go
This PR creates a tiny utility to manually inspect and generate tokens.
Together with this utility, there is a minor refactor of lib/oauth/factory.go
to allow instantiating the code to actually sign and generate cookies.
The utility takes a set of keys from command line, and can either
open cookies, or create them, with arbitrary duration.
=> lib/oauth: add tiny cli tool to generate and print tokens.

lib/oauth/cli/BUILD.bazel, lib/oauth/cli/main.go, lib/oauth/factory.go, lib/oauth/oauth.go, lib/oauth/ogrpc/ogrpc.go, lib/token/token.go, lib/token/token_test.go, proxy/nasshp/nassh.go
Background:
Before this change, a token was either valid or invalid.
There was no way to determine why it was invalid (except for the
error status) or how much time was left in the token.
- lib/token has been modified so:
1) decoders can attach arbitrary metadata using the standard context.Context
golang library. This breaks API compatibility.
2) decoders keep moving forward even if there is an error. This
allows to extract the validity of a token (and its content)
even if expired.
An error is still returned, of course, as the token is invalid.
But the caller can still check the information decoded, and print
it if necessary.
- updated oauth library so that:
1) decoders are used with the new API.
2) issued time is returned. This breaks API compatibility.
- updates through …
=> lib/token: allow to extract the issued time.

proxy/nasshp/nassh.go
Missed this in code review, noticed while fixing the test:
all log messages in nasshp should include "logid", so it
is possible to identify the connection that cause the problem.
=> nasshp: minor logging improvements.

proxy/httpp/build.go
This is a temporary hack waiting the overhaul of the proxy
configuration file. Until then, let's disable certificate
verification when talking to internal backends.
This is a security risk. However, most of the interal backends
configured happen to be horrible ssl appliances with self signed
certificates, and no ability to configure a real certificate.
Practically speaking, this is the only option to get them to
work.
With the config overhaul, it will be possible to selectively
disable certificate validation, or pin certificates directly
in the configuration file.
=> feature/fix: disable TLS by default with backends.

bazel/linux/defs.bzl
I was just testing the kernel builds, and noticed that the bazel
output has an unexpected newline. Eg:
kernel building: compiling module enf.ko for enf-5.11.16-1+enf-1621888669-gd552cf86321e
; 318s remote
kernel building: compiling module enf.ko for custom_distro-zctap-backported-5.10
; 303s remote
kernel building: compiling module enf.ko for enfvm-5.11.16-1+enf-1621893941-gd552cf86321e
; 288s remote
kernel building: compiling module enf_queues_test.ko for custom-5.9.0-um
; 275s remote
This PR removes it.
=> linux/defs.bzl: remove ugly newline.

lib/kflags/kconfig/namespace.go
Background:
When a package is downloaded from our internal repository and run,
a few variables are passed via the environment and can also be use
for command line flag substitution.
In this PR:
Add the 'enkit_path' variable, replaced as '{enkit_path}' on the
cli, or exported as KCONFIG_ENKIT_PATH on the environment.
=> kflags/kconfig: export enkit_path to running packages.

lib/client/client.go
Background:
Most errors in enkit today default to causing the binary to exit
with status 1. Shell scripts have no choice but to parse the output
to tell different errors apart.
In this PR:
- change the identity error handling to return status 100 when an
identity error takes place.
- this allows scripts to tell the error apart, and behave accordingly.
=> lib/client: differentiate credential errors.

proxy/ptunnel/commands/tunnel.go
1) The only way to background a tunnel was to use & in shell.
This caused two issues: a) race condition, there is no way
to know that the tunnel handshake has completed and it is
ready to listen for connections when it is first used, and
b) there is no way to handle errors properly. Eg, wait for
it to finish? can't do, if all goes well, it'll never finish.
2) There was no error checking before the first connection attempt.
This caused a tunnel creation to succeed, but then fail the
first time it was actually used.
In this PR:
- introduce a --background option. This will open the listening
socket and check for errors *before* backgrounding, so it is
dead easy and reliable for shell scripts to background a tunnel.
- introduce error checking before opening the listening …
=> proxy/ptunnel/tunnel: add support for backgrounding.

bazel/workspace_status.sh
See comment in the file for reasons. Tl;Dr: if local files change,
the status file has to be rebuilt, old state cannot be cached/reused.
=> workspace_status: mark variables as STABLE.

bazel/linux/defs.bzl
The Module.symvers file will be necessary to build external modules that
consume exported symbols from a given module that it takes a dependency
on. Declaring it as a build artifact makes it easily available to other
builds.
=> linux/defs.bzl: Declare Module.symvers for each package

WORKSPACE, bazel/init.bzl
- WORKSPACE initializes the go toolchain
- bazel/init.bzl initializes the go toolchain
- the first initialization wins (WORKSPACE), so all works in enkit/
- another repository (internal) uses @enkit/baze/init.bzl
- there is no WORKSPACE initialization
---> CRASH, as the initialization in bazel/init.bzl is invalid with
the newer versions of the toolchain.
In this PR:
- initialize the golang toolchain from one place only,
bazel/init.bzl, with the correct version.
=> bazel/init.bzl: initialize golang sdk in one place only.

astore/server/BUILD.bazel, astore/server/main.go, lib/khttp/kassets/BUILD.bazel, lib/khttp/kassets/assets.go, lib/khttp/server.go, lib/oauth/BUILD.bazel, lib/oauth/oauth.go, lib/server/BUILD.bazel, lib/server/run.go
This is a minor cleanup: right now, server.go includes a Run()
with heavy dependencies on grpc, and a bunch of helper functions
to deal with asset files.
The functions for asset file managmenet are generically useful
and self contained. But by being in the server library, they
cannot be used without bringing in the entire grpc ecosystem.
Also, it does not make sense for those functions to be in lib/server.
In this PR:
- move asset management functions as they are in lib/khttp/kassets.
- update code using those functions/libraries as necessary.
- rename lib/server/main.go in lib/server/run.go as there is no main
there.
This PR is otherwise a noop: no code change has been performed.
=> lib/server: break out assets management function.

bazel/linux/defs.bzl
This commit fixes build failures caused by _kernel_module_targets
dropping the visibilty of kernel module builds.
=> linux/defs.bzl: Fix visibility propagation

bazel/init.bzl, bazel/ui/BUILD.bazel, bazel/ui/deps.bzl, bazel/ui/merge-package.sh, bazel/ui/react.bzl, bazel/utils/binary.bzl
- Adds in the download_binary and declare_binary rules, which are simple wrappers
- Uses the wrapper to download binaries and executes them inside the ui tests.
=> Vendor jq and Update tests

bazel/linux/kernel_tree.BUILD.bzl
Background:
When bazel analyzes a target, it has to determine which input files
are necessary, if they changed, and maintain a tree in memory.
To do so, it has to load the list of files, compute hashes, ...
For kernel trees, this is really slow: there's 100,000s files
in there.
In this PR:
- change the glob expression from (**/* excluding directories [the default])
to a simple * including directories.
- from empirical evidence, this seems to make the build visibly faster.
Looking at the bazel output on the screen, with this simple change
bazel went from: 325K targets configured, to just 26!
The only side effect is that it seems like the directories scanned
are made available in read only mode, which is actually desireable.
Although the amount of work to determine which files changed is …
=> bazel/linux/defs.bzl: speed up kernel builds.

bazel/linux/defs.bzl
Background:
Before this PR, a module depending on another did not
compile correctly. There were 2 separate issues:
1) Module.symvers file, was not exported/imported correctly.
Beside the mechanics to import the file, the -C parameter
passed to make causes it to change directory, and breaks
bazel generated relative paths.
2) Most modules are compiled for a set of kernels. When
one module depends on another, it must be linked against
the same kernel version being built.
This PR:
- adds the correct logic to export and bring in Module.symvers
files (thanks Raghu!)
- adds logic so that when a module depends on another, it selects
the variant built with the same kernel version.
=> bazel/linux/defs.bzl: get kernel dependencies to work correctly

monitor/BUILD.bazel, monitor/docker-compose.yml
In this PR:
- add rules to create a docker container for our monitor.
- add docker-compose.yml as an alternative to our typical shell scripts
to start the container locally.
=> monitor: dockerize the background pinger.

scripts/gee
Previously, these commands could only be executed from within a
~gee/<repo>/<branch> directory.  This change allows these branches to be run
from any directory, using the default repo if repo cannot be determined.
- Make mkbr, rmbr, gcd work from any directory.
- Make lsbr, update_all work from any directory.
=> Allow some commands to run from anywhere

scripts/gee
Armor up gee against git-induced filesystem weirdness with "cd ."
=> Fix busted getcwd with cd .

scripts/gee
Added some better checks.  At one point, I did away with our generation
of an ssh key in favor of using enkit's certicate to authenticate to github.
Unfortunately, this didn't work as expected (the enkit cert only grants
access to enfabrica/internal, but not $GHUSER/internal).  So, for the moment,
it seems we still need gee to generate ssh keys for the user, so I rolled
back that part of the change but kept other improvements.
- Check enkit agent.
- move to new org-64667743@github.com remotes
- Use enkit cert exclusively.
=> gee: improve ssh connectivity

scripts/gee
Make the output of "rupdate" and "update_all" commands more legible by adding a
banner message to separate branch updates from each other.
=> gee: add banners

scripts/gee
This is adding back some functionality that I deleted when we were trying to
switch to enkit certs instead of ssh keys.
=> gee: use SSHKEYFILE if it exists

scripts/gee
Instead of dropping the user into an interactive shell, the
new conflict resolution flow prompts the user for each
conflicting file in each commit, and asks the user to
choose between:
- accepting "your" (child) version,
- accepting "their" (parent) version,
- running a merge tool
- skiping a commit
- aborting the rebase operation altogether.
=> gee: new conflict resolution flow

scripts/gee, scripts/gee.orig
The old behavior: "gee update" would notice if origin/branch was ahead of branch,
and would automatically integrate commits from origin/branch before updating.
This was done in order to support a workflow where the user is running gee to
make commits to the same branch on different workstations, and we want to use
gee to keep the two local git repositories in sync.
However, this breaks down under the following conditions:
feature2 is a branch of feature1.
feature1 gets submitted into master (a squash-merge).
feature2 then does "git rebase --onto master feature1 feature2"
Everything up to this point works great, until the user then runs:
in feature2: "gee update".
This causes all of the discarded commits to get pulled from origin/feature2,
which are then rebased onto feature2 creating a …
=> gee: ask before pulling from origin

machinist/machine/commands.go
- passes in config to enroll command so that some base flags don't have to be set.
- using cobra Args commands breaks kcobra, so I removed it.
=> Simple machinist fixes

scripts/gee
A user encountered an issue where jq couldn't be installed without running
"apt update" in the dev container first.  In this change, we play it safe
by always running apt update before apt install.
=> gee: apt update before apt install

scripts/BUILD.bazel, scripts/gee, scripts/gee.bats
This built atop PR #167.
Adds gee.bats, a unit test for testing gee internal functions.
Adds _parse_options, a gee internal function that needed testing.
=> gee: added unit test

bazel/shellutils.bzl, scripts/BUILD.bazel
gee: use shelltest as a regression test for gee.
This should help me avoid embarrassing mistakes in the future, though this tool really needs to be rewritten in a real language.
=> add gee-shellcheck_test

scripts/gee
The problem: `pr_submit` would perform a squash merge, causing derived branches to have
merge conflicts when updated later.  This PR changes the `pr_submit` behavior to safely
update all derived branches to safely rebase onto the squash-merge commit.
This PR also contains some cleanup to make it easier to test gee non-interactively.
=> gee: handle squash-merge

scripts/gee
This PR is a consequence of a use case:
- user use "gee pr_checkout" to check a PR into a branch
- user made some changes on their branch, and the PR changed.
- now user wants to rebase their branch from the upstream PR.
Commits:
- gee pr_checkout: use gh pr checkout, update parent
- gee pr_checkout: fix branch creation.
- eliminated special handling of $MAIN, handle upstream branches other than $MAIN
- improve _safer_rebase to handle upstream branches such as pull requests
=> gee: better PR checkout/update

scripts/gee
This fixes a bug that was introduced in
https://github.com/enfabrica/enkit/pull/162.
It turns out that adding "--depth" option to "git clone" also implies the
"--single-branch" option, which causes git to only pull down the refs for the
main branch.
That is, the .git/config file for origin contained:
```
[remote "origin"]
url = org-64667743@github.com:jonathan-enf/internal.git
fetch = +refs/heads/master:refs/remotes/origin/master
```
It should be:
```
[remote "origin"]
url = org-64667743@github.com:jonathan-enf/internal.git
fetch = +refs/heads/*:refs/remotes/origin/*
```
This will cause git to error out as if origin/feature1 didn't exist, because
git was configured not to fetch it.
Since we always want all branch heads to be pulled down from origin, I had to
add the "--no-single-branch" …
=> gee__init: add --no-single-branch to git clone

lib/khttp/kassets/assets.go
Background:
Static assets are served differently depending on the file name.
For example: the .html extension is normally stripped, so foo/bar.html
is served as foo/bar.
/index.html was served as both /index and as /, but a foo/bar/index.html
was only served as foo/bar/index.
After this change:
foo/bar/index.html is also served as foo/bar/. Arguably, this PR fixes
an existing bug in the code, as the intended behavior was for any
index.html file to serve as the directory index.
=> lib/khttp/kassets: allow indexes in subdirectories.

scripts/gee
During the automatic merge conflict resolution flow, I found that I implemented
git rebase --skip incorrectly (I was terminating on non-zero exit code, which
really just indicated that rebase wasn't complete).
I also noticed that my handling of empty commits was broken (that now
auto-skips the commit, is there a better way?).
=> gee: fix rebase-skip option

enkit/BUILD.bazel, enkit/main.go, lib/bazel/commands/BUILD.bazel, lib/bazel/commands/commands.go, scripts/BUILD.bazel
This change adds a `bazel` subcommand tree to `enkit`, initiailly
populated with `bazel affected-targets list`. This command is not yet
implemented, but will eventually print the list of affected targets to
stdout.
Output of `enkit bazel affected-targets list --help`:
```
List affected targets between two source revision points
Usage:
enkit bazel affected-targets list [flags]
Aliases:
list, ls
Examples:
$ enkit bazel affected-targets list
List affected targets between the last commit and current uncommitted changes.
$ enkit bazel affected-targets list --start=HEAD~1 --end=HEAD
List affected targets in the most recent commit.
Flags:
-h, --help   help for list
Global Flags:
-e, --end string         Git committish of 'end' revision, or empty for current dir with uncomitted changes
--help-all …
```
=> enkit: Add `bazel` subcommand

license_manager/proto/BUILD.bazel, license_manager/proto/license_manager.proto
This change adds a gRPC definition for the license_manager service,
intended to supplant the existing license service under `//manager` with
a protocol that uses multiple unary RPCs instead of a bidirectional
streaming RPC, in an effort to clarify the implementation of both the
client and the server.
Requirements and more info can be found in: https://docs.google.com/document/d/1TNqbBprpcNU9tTHVCFzRwaQoHlGFdjkw221C5p9UsAw/edit
Tested: All targets build:
```
bazel build //license_manager/...
```
Jira: INFRA-90
=> license_manager: Add proto definition file

lib/errdiff/BUILD.bazel, lib/errdiff/errdiff.go, lib/errdiff/errdiff_test.go
This change adds a testonly library called "errdiff" that allows unit
tests to easily see if errors match an expected substring.
This allows for a bit more fidelity than checks by the assert package,
as the latter only has functions for checking error presence (though
oftentimes the error expected in tests is not the one actually returned)
and exact error equivalence (though it may be difficult and/or brittle
to formulate an expectation on an exact error value).
=> testing: Add errdiff lib

lib/server/run.go, license_manager/server/BUILD.bazel, license_manager/server/main.go, license_manager/service/BUILD.bazel, license_manager/service/service.go, license_manager/service/service_test.go
This change adds:
* A LicenseManager service with all handlers returning unimplemented
* Tests for said service expecting unimplemented for all methods
* A server binary that starts the LicenseManager service on a port
specified by flag.
Design and more info: https://docs.google.com/document/d/1TNqbBprpcNU9tTHVCFzRwaQoHlGFdjkw221C5p9UsAw/edit#
Tested: Builds and all unit tests pass:
```
bazel test //license_manager/...
```
Server starts:
```
[~/dev/enkit] (license_manager_server_boilerplate)
sminor-> bazel run //license_manager/server:license_manager -- --port=8081 --alsologtostderr &
[1] 9262
[=== 2021-10-01 05:21:39 === SUCCESS ===]
[~/dev/enkit] (license_manager_server_boilerplate)
sminor-> INFO: Invocation ID: 7742f725-9df7-43e2-96a4-49bbe64969b0
INFO: Analyzed target …
```
=> license_manager: Add server boilerplate

lib/kflags/BUILD.bazel, lib/kflags/defaults.go, lib/kflags/env.go, lib/kflags/env_test.go, lib/kflags/flags.go, lib/kflags/kconfig/config.go, lib/kflags/kconfig/namespace.go, lib/kflags/map.go
This change introduces a new Augmenter, the MapAugmenter, which allows
to provide flag defaults from a simple map, provided at the agumenter
creation time.
The MapAgumenter can be configured to use one or more EnvManglers
(now renamed VarMangler) to allow to compute a different key from
a flag name. For example, by using a Camel mangler, for a flag named
"network-timeout", the key "NetworkTimeout" is looked up in the flag.
Additionally, this PR restructures manglers to be more genereically
useful, and introduces a couple new ones.
No functional change to the codebase, this just adds new library
functions that will be used in an upcoming PR.
=> lib/kflags: add ability to provide command line flags from a map.

lib/config/BUILD.bazel, lib/config/directory/homedir.go, lib/config/directory/homedir_test.go, lib/config/multi.go, lib/config/multi_test.go, lib/config/simple.go, lib/config/store.go
Background:
So far, the config library allowed to store a config by key, and
retrieve it.
In this PR:
- add ability to delete a key.
- improve comments and documentation.
- add corresponding tests.
Additionally:
- Write() function in the homedir store has been improved to guarantee
atomicity on POSIX filesystems.
=> lib/config: add ability to delete key.

lib/config/BUILD.bazel, lib/config/datastore/BUILD.bazel, lib/config/datastore/datastore.go, lib/config/directory/homedir.go, lib/config/directory/homedir_test.go, lib/config/multi.go, lib/config/multi_test.go, lib/config/simple.go, lib/config/store.go
Background:
So far, configs could only be stored in a directory, or in the
home directory of the user.
This PR introduces a new config.Store implementation, capable
of storing objects and configs in datastore.
=> lib/config: add a datastore config manager.

scripts/gee
There's a bug in git verison 2.17.1, which happens to be the version currently
installed in the hardware container.
The bug: "git worktree remove $BR" is always failing with the error message:
"fatal: working trees containing submodules cannot be moved or removed"
However, inspection of the client reveals that no submodules are present.
The issue can be resolved in two ways: by upgrading to a more recent git, or
by adding a "--force" option to "git worktree remove."
Since updating "git" requires updating a large set of shared libraries that
could impact EDA tools, I opted for the latter option.
=> gee: fix for git v2.17.1 worktree remove

scripts/gee
Decided that having "gee whatsout" show differents from parent, rather than
differences from main (same as "gee diff") was more intuitive.
Along the way, noticed that "git diff --quiet" has the opposite polarity of
exit code than I expected, so fixed.
=> gee whatsout: diff against parent, not master

scripts/gee
Even though the cc_format rule in enkit was updated to accept file names as
arguments, the enkit library was never released or updated in internal.  This
caused the default behavior (cc_format iterating over all files) to persist.
I think that ultimately, this felt like a fragile and unnecessary extra
dependency, so I went back to invoking clang-format-10 without depending on any
particular version of enkit being released.  The same formatting rules
(specified in cc.format) are employed.  Maybe at some point in the future
we can swap to building clang-format from source, if needed.
Ultimately, gee really should be a stand-alone tool that works in environments
other than enfabrica's.
=> gee fix: fix clang-format

scripts/gee
Bug: merge conflict resolution flow was attempting to merge-fix files with no
conflicts in them.
The underlying issue was that I misunderstood the "git status --porcelain"
output format.  I am now parsing that data correctly and skipping over conflict
resolution for files without conflicts.
Along the way, I also fixed a related bug where "grep -c <something>" at the
end of a pipe was exiting with a non-zero exit code, causing "set -e" to cause
the process to fail.  I now append "| cat" to the end of such pipelines to
avoid being caught in this way.
Overall, gee is now complex enough that it needs to be rewritten (in golang?).
=> gee: fix merge conflict resolution

bazel/go_repositories.bzl, go.mod, go.sum, lib/config/datastore/BUILD.bazel, license_manager/proto/license_manager.proto, license_manager/server/main.go, license_manager/service/BUILD.bazel, license_manager/service/license.go, license_manager/service/service.go, license_manager/service/service_test.go
This change contains the bulk of the server handler implementation, along with associated unit tests.
The service proto is tweaked:
* More fields are added to `RefreshRequest` to better handle the case where the server is adopting existing allocations after a restart. The client must pass all the information (license type, owner, build_tag, etc.) during RefreshRequests in case the server has restarted; otherwise, the server won't know which license to allocate, who it is allocated to, etc.
* Common fields between RefreshRequest and AllocateRequest are deduplicated to an Invocation message.
* Repeated fields are pluralized
* Queued license count added to LicensesStats response
Jira: INFRA-90
=> license_manager: Implement server handlers

lib/knetwork/kdns/BUILD.bazel, lib/knetwork/kdns/dns.go, lib/knetwork/kdns/dns_test.go, lib/knetwork/kdns/factory.go, lib/knetwork/kdns/flags.go, machinist/mserver/command.go, machinist/testing/BUILD.bazel, machinist/testing/machinist_e2e_test.go
Does the following things:
- allows for the kdns server to use tcp and udp on the same port
- adds in compression for udp response times
- refactors small amount of factory functions
- modifies machinist e2e testing to pass with the new api
=> Refactor of kdns and machinist to include tcp and QoL

lib/bazel/proto/BUILD.bazel, lib/bazel/proto/workspace_log.proto
The workspace_log proto is from the bazel repository and is required for
parsing workspace logs; these logs will be used to determine SHA hashes
for third-party dependencies, allowing for the detection of changes
without hashing each file individually.
This file is copied over integrating directly the WORKSPACE because:
* it saves fetch time (the bazel repository is large)
* BUILD files fetched in the bazel repository do not grant us visibility
to the proto, necessitating patches
=> bazel: Add workspace_log proto

bazel/workspace_status.sh
Working on finishing linting and noticed that the order was backward for linting.
Also, should it be origin master or upstream master? or both?
=> Change Ordering in workspace status

lib/bazel/affected_targets_test.go, lib/bazel/query.go, lib/bazel/target.go
Prior to this change, affected targets detection would attempt to read
and hash generated files, which don't actually exist.
The purpose of the hash is to detect when targets change. Generated
targets are based solely on the rule that generates them, so this change
ensures that:
* the generating rule is registered as a dependency of the
generated-file target
* hashing the generated file target doesn't attempt to read any files
Tested: Added unit test for this case
Jira: INFRA-120
=> INFRA-120: Fix affected targets detection with generated files

lib/bazel/affected_targets_test.go, lib/bazel/target.go
Some labels in `internal` are actually directories. When this is the
case, these directory labels are used as commandline flags rather than
file contents. It is debatable if this should just be fixed in
`internal`, but in the meantime dependency detection can tolerate this
case.
When a "source file" label that actually represents a directory is
encountered, the hash of the "source file" should correspond simply to
the hash of the label itself. This resolves a "can't read: is a
directory"-type error when attempting to hash the underlying "file" for
a directory source file target.
Jira: INFRA-121
=> INFRA-121: Fix bazel graph parsing for directory labels

scripts/gee
There's been a longstanding bug where "gee pr_submit" was causing the branch being
submitted to get checked out into ~/gee/<repo>/master.  I finally root caused and
fixed the issue.
PR generated by jonathan from branch gee_fix_munged_master.
Commits:
*  1039b23 gee pr_submit: fix checkout into master dir
=> gee pr_submit: fix checkout into master dir

lib/bazel/BUILD.bazel, lib/bazel/exec.go, lib/bazel/exec_test.go, lib/bazel/query.go, lib/bazel/query_test.go, lib/bazel/workspace.go, lib/bazel/workspace_test.go
This change modifies how `bazel` commands are run inside enkit to dump
both stdout and stderr to temporary files. This simplifies command
running, which no longer requires goroutines and negotiating an io.Pipe,
and allows for the code to log stdout/stderr output on command failure.
This in turn will let us debug why bazel commands fail in the presubmit.
Tested:
affected-targets tested locally against this change:
```
bazel run //enkit bazel affected-targets list --start=master --end=infra/123 --loglevel-console=debug
Affected targets:
//lib/bazel:go_default_test
//lib/bazel:go_default_library
//lib/bazel/commands:go_default_library
//enkit:go_default_library
//enkit:enkit-win-amd64
//enkit:enkit-linux-amd64
//enkit:enkit-darwin-amd64
//enkit:enkit
//enkit:deploy
//:gazelle-runner …
```
=> INFRA-123: Write bazel command output to tempfiles

flextape/client/BUILD.bazel, flextape/client/client.go, flextape/client/client_test.go, flextape/proto/flextape.proto, manager/client/BUILD.bazel, manager/client/main.go
This change creates:
* a client library for Flextape communication
* unit tests for said library
* a codepath in the existing license manager client that uses Flextape
communication, triggered via environment variable
Tested: In addition to the above:
```
bazel run //flextape/server:flextape
watch -x -n 1 grpc_cli call localhost:6433 Flextape.LicensesStatus ''
for i in $(seq 1 10); do (LICENSE_SERVER_IMPL=flextape bazel-bin/manager/client/client_/client localhost 6433 xilinx bar sleep 5 &); sleep 1; done
```
Jira: INFRA-107
=> INFRA-107: Implement flextape support in existing client

infra/cloudbuild/helpers/bazel_test.sh
In enkit, the presubmit test step is erroneously running `bazel build` instead of `bazel test`.
=> bazel presubmit: Run tests in `bazel test` step

lib/bazel/options.go, lib/bazel/options_test.go
This change fixes an issue where errors are not propagated when
keep_going is not set.
Tested: Added unit tests
Jira: INFRA-148
=> lib/bazel: Don't swallow errors when keep_going not set

flextape/proto/flextape.proto, flextape/service/license.go, flextape/service/service.go, flextape/service/service_test.go
The client should log to the user the status of the license acquisition
progress when queued. Currently, there's not much progress the client
can communicate, other than that it's queued.
This change modifies the server to return the queue position so that
clients can communicate this to the user, providing user visibility that
in fact progress is being made (or the queue appears to be stalled).
Tested: Unit tests
Jira: INFRA-139
=> flextape: Return queue position to client

infra/cloudbuild/helpers/git_rebase_pr.sh
Updating via merge should be more resilient than doing so via rebase.
Tested: Layered this on top of #308 in #311 and it passes checks as expected: https://console.cloud.google.com/cloud-build/builds/9f120110-bf64-4c5f-9ee9-2627e0055706;step=5?project=cloud-build-290921
Jira: INFRA-163
=> presubmit: Attempt to merge-update instead of rebase-update

flextape/proto/BUILD.bazel, flextape/proto/config.proto, flextape/proto/flextape.proto, flextape/server/BUILD.bazel, flextape/server/config.textproto, flextape/server/main.go, flextape/service/service.go
This change adds:
* A protobuf config definition, for a config file passed to the server
on startup
* A flag on the server to provide the config file at runtime
* Server code to parse the config
Jira: INFRA-159
=> flextape: Add config definition and Xilinx config

infra/cloudbuild/helpers/git_rebase_pr.sh
This change copies the `git_rebase_pr.sh` helper from internal after
fixing INFRA-175.
Jira: INFRA-175
=> presubmit: Fix merge-update process

scripts/gee
Fulfill feature request: gcd now populates BROOT and BRBIN environment variables.
Also fixed gcd documentation, and implemented `gcd <branch>/<path>` functionality.
PR generated by jonathan from branch gee_gcd_features.
Commits:
*  f8d38c0 gcd: add BROOT and BRBIN variables, improve documentation, add "gcd <br>/<path>" functionality.
=> gcd: add BROOT, BRBIN, br/path functionality

flextape/service/service.go
This change ensures that the license name is set during construction,
fixing an issue where  was reporting
for the license vendor.
Jira: INFRA-188
=> flextape: Set license name during construction

bestie/proto/BUILD.bazel, bestie/proto/hello.proto, bestie/server/BUILD.bazel, bestie/server/main.go
This change adds enough of a gRPC and HTTP application to:
* get something running on Google Cloud Run
* develop Bazel rules to deploy a container to Google Cloud Run
The initial gRPC service is a hello-world type service that is expected
to be deleted quickly; this is simply the quickest path to a working RPC
service for testing Cloud Run.
The binary also exports a /metrics endpoint, which we can use to test
HTTP fetches as a surrogate for an actual UI.
Tested: `bazel run //bestie/server:bestie` and successfully:
* did `grpc_cli` call of `Greet` RPC: `grpc_cli call localhost:6433 bestie.proto.Greeter.Greet 'name: "Scott"'`
* fetched metrics: `curl localhost:6433/metrics`
Jira: INFRA-193
=> bestie: Add initial skeleton

scripts/gee
gee: Consistently use "--quiet" option with git push.
PR generated by jonathan from branch gee_push_quiet.
Commits:
*  bf29436 gee: use --quiet option with push universally.
=> gee: use --quiet option with push universally.

scripts/gee
This is a quick fix to a bug I found in the conflict resolution flow.
PR generated by jonathan from branch gee_rebase_pick.
Commits:
*  1f7ba94 gee: restart rebase flow after "picking" as rebase might have succeeded.
=> gee: restart rebase flow after "picking" as rebase might have succeeded.

scripts/gee
The hardware image is still running git 2.17, which doesn't support the
"git mergetool --guitool" option.  So, we emulate that option by manually
specifying a --tool="${GUI_MERGETOOL}".
The good news: this works.
The bad news: the "meld" GUI merge tool in the hw container is also broken.
One step at a time.
PR generated by '' from branch gee_guitool.
Commits:
*  1b39c00 support older git that doesn't implement guitool
=> gee: unbreak gui mergetool for older versions of git

bazel/cloud_run/defs.bzl, bestie/server/BUILD.bazel, bestie/server/main.go, flextape/server/BUILD.bazel, lib/server/BUILD.bazel, lib/server/run.go
This change adds rules to deploy a Docker image to Cloud Run, and
provides an example deployment for bestie.
This change also adds a new common server factory function, since
the current factory doesn't seem to allow normal HTTP2 requests to succeed.
This new server sets up gRPC and HTTP2 but not grpc-web, which is
currently not needed. Ideally they should be coalesced into one method,
which we may be able to do once we understand the nuances of the
various protocols.
Tested:
```
bazel run //bestie/server:bestie_image_push && bazel run //bestie/server:bestie_cloud_run_deploy
grpcurl -d '{"name": "scott"}'  bestie-24mnsxopwq-uw.a.run.app:443 bestie.proto.Greeter/Greet
{
"greeting": "Hello, scott!"
}
curl --http2-prior-knowledge https://bestie-24mnsxopwq-uw.a.run.app/metrics
```
Jira: …
=> bazel: Add cloud_run rules

scripts/gee
gee bugfix: fix malformed "git push" argument.
I typoed a command: "git push --quiet u origin" instead of "git push --quiet -u
origin", breaking the gee pr_make command.
This is the right opportunity to act on Carlo's suggestion that this commonly
re-used commmand should be refactored into a function, so that is what I've
done.
PR generated by jonathan from branch gee_push.
Commits:
*  baad91b gee: migrate to _push_to_origin fn
=> gee bug fix: malformed git push command

flextape/server/run.sh
This change contains a script with the Docker command used to bring up
Flextape on build-00. This script can get deleted once flextape is
migrated to the cluster.
Tested: Ran this command on build-00; flextape is currently running.
Jira: INFRA-252
=> flextape: Add Docker deployment script

scripts/gee
Buried in my code, I accidentally called "confirm_default_no" instead of
"_confirm_default_no."
Further evidence that gee needs to be rewritten in golang.
PR generated by jonathan from branch gee_confirm_default_no.
Commits:
*  862196c gee: fix _confirm_default_no typo
*  b6b6e14 gee: add "config enable_meld" option (#350)
=> gee: fix _confirm_default_no typo

scripts/gee
This PR fixes a corner case where gee was setting the CHECKS_FAILED counter to
a null string instead of zero when "gh pr checks" would fail but no actual
checks failed.
This would occur when running in a branch with a closed PR (the PR has no
changes, and so "gh pr checks" fails as the pr is uncheckable, but no actual
check fails).
PR generated by jonathan from branch gee_errors.
Commits:
*  574dd20 gee: ensure the number of failed checks is always numeric.
=> gee: ensure the number of failed checks is always numeric.

scripts/gee, scripts/gee.bats
gee pr_submit: also use metadata to find child branches.
gee pr_submit rebases orphaned branches when a parent branch is submitted, to
avoid merge conflicts.
Old behavior searched for orphans by looking for branches that had a commit in
common with the parent.  This proved useful but incomplete: if the parent had
been rebased but the child had not, then the selected commit might exist in the
parent but not the child.
New behavior: supplement the finding of lost children by also using the
parentage metadata to recursively find all children of the submitted branch.
Also added a bats test for the recursive child finder.
Side note: I really need to swing to golang soon.
=> gee pr_submit: more complete detection of orphans

scripts/gee, scripts/gee.bats
Add _check_pr_description function to examine the user-provided PR description
and make sure that it is at least basically conformant with expectations: a one
line title, a blank line, and then one or more lines of body text.
PR generated by jonathan from branch gee_pr_description2.
Derived from branch gee_pr_description's PR #347.
Commits:
*  db3c4c0 gee: add _check_pr_description function
*  1d5c06a add test for _check_pr_description
=> gee: validate pr descriptions

infra/cloudbuild/postsubmit_bazel.yaml
This change adds a postsubmit build that builds and tests all bazel
targets in enkit. This will be used to detect bad changes that should
trigger someone to roll back.
Jira: INFRA-189
=> cloud build: Add postsubmit

lib/token/BUILD.bazel, lib/token/asymmetric.go, lib/token/symmetric.go, lib/token/symmetric_test.go, lib/token/time.go, lib/token/time_test.go, lib/token/token.go, lib/token/token_test.go
This is another nop: no changes to the code other than moving
functions around and invoking `go fmt` on all files.
Background: token.go is quite large, > 500 lines of code.
In preparation to add more asymmetric functions, splitting
the file into multiple ones.
Tested: all tests are still passing. Coverage is low, but
this change has not modified the code in any way.
=> lib/token: split large file into multiple ones.

lib/token/BUILD.bazel, lib/token/asymmetric.go, lib/token/asymmetric_test.go
This is adding in yet another encoder to allow encrypting
data using private and public keys.
Some of this code comes from astore, a next step could be
to refactor the internal astore code to use the token library.
Tested: unit test covering the most important part of the library.
=> lib/token: add support for asymmetric encryption.

lib/config/directory/homedir.go
This PR fixes a minor file descriptor leak homedir Write, where
a tempfile is created, but the corresponding file object is never
closed.
This is generally not impacting, as configs are read/written to
at startup only.
But the config store API effectively provides a key value store,
and this could be used outside initial configuration handling.
Tested: unit tests pass before and after. No real test to detect leaks at this point.
=> lib/config/directory: minor bugfix - leaking file descriptor.

flextape/server/flextape_config.textproto
This change adds cadence licenses for all features that expire in March
2022. Licenses for features that expire soon are skipped.
Jira: INFRA-274
=> flextape: Add cadence licenses

flextape/server/run.sh
Tested: Deployed to build-00
Metrics for cadence shown in https://monitoring.corp.enfabrica.net/d/uRCWqp27z/flextape?orgId=1:
Jira: INFRA-274
=> flextape: Update image version

machinist/testing/machinist_e2e_test.go
Background:
See https://console.cloud.google.com/cloud-build/builds/3e2fc550-dfef-498b-95cb-11921306d0b5;step=5?project=cloud-build-290921,
test fails every now and then with the message below**.
Running the test with --runs_per_test=100, shows about
60% failure rate. This is not surprising: DNS returns records in random
order by standard, test expects them in an exact order.
In this PR:
- change `Equal()` to `ElementsMatch()`.
After this change, test passes 100% of the times.
[**]
--- FAIL: TestJoinServerAndPoll (0.28s)
machinist_e2e_test.go:114:
Error Trace:	machinist_e2e_test.go:114
Error:      	Not equal:
expected: []string{"10.0.0.4", "10.0.0.1"}
actual  : []string{"10.0.0.1", "10.0.0.4"}
Diff:
--- Expected
+++ Actual
@@ -1,4 +1,4 @@
([]string) (len=2) {
- (string) (len=8) …
=> machinist/testing: fix e2e test.

proxy/nss/confparse/confparse.c
Background:
Strings need to end with a \0. Function to unescape strings
did malloc(), but did not add \0 at the end.
This caused confparse_test ParseQuotedString.All to fail at times.
Probably, some good % of the times malloc() was returning zeroed
memory out of pure luck.
In this PR:
- correctly terminate the string before returning it.
=> proxy/nss/confparse: address problem found by unittest.

flextape/proto/flextape.proto, flextape/service/license.go, flextape/service/service.go, flextape/service/service_test.go
This change extends the LicensesStatus RPC to show details on each
invocaition that has been allocated, and each invocation that is queued.
This should help us answer questions about where particular builds are
queued if asked.
Tested: Unit tests, ran server plus clients with
```
for i in $(seq 1 10); do (LICENSE_SERVER_IMPL=flextape bazel-bin/manager/client/client_/client localhost 6433 xilinx vivado sleep 60 &); done
```
and then `LicensesStatus` with:
```
grpc_cli call localhost:6433 flextape.proto.Flextape.LicensesStatus ''
```
and verified that `allocated_invocations` and `queued_invocations` were
filled as expected.
Jira: INFRA-287
=> flextape: Return queue details in LicensesStatus

scripts/gee
gee pr_submit: fix bug that caused gee to fail to rebase child branches.
A previous PR reworked the way that gee detects the child branches of a branch
that has been submitted, and rebases them using "rebase --onto" to avoid
unnecessary merge conflicts.  Unfortunately, I introduced a bug causing
gee to check the wrong variable when looking for the list of child branches.
Further evidence of the need for a golang rewrite, but we've already had
plenty of that.
Tested:
Submitted a PR with children and made sure the children got rebased.
PR generated by jonathan from branch gee_whats_up_with_pr_submit.
=> gee pr_submit: fix bug that caused gee to fail to rebase child branches.

flextape/server/flextape_config.textproto
This change updates license counts with the provisional license file
received from Cadence, providing licenses through 16-Dec.
This assumes that unexpired license amounts can be summed together for a
total license count.
Jira: INFRA-313
Jira: INFRA-314
=> flextape: Update license counts

flextape/server/run.sh
This change updates the run script to the current image deployed.
Tested: Currently running on `build-00`
Jira: INFRA-314
=> flextape: Update image

flextape/client/client_test.go, flextape/frontend/BUILD.bazel, flextape/frontend/frontend.go, flextape/server/BUILD.bazel, flextape/server/main.go, flextape/server/templates/queue.go.tmpl, flextape/service/service.go
This change adds a `/queue` route to flextape that returns a page
showing:
* Each license + feature configured
* Current allocations for each, including command ID and owning user
* Current queued invocations for each, including command ID and owning
user
The page uses Bootstrap from a CDN for formatting and hiding all but a
single selected license/feature combo's details.
Features with no reservations or queued invocations are sorted to the
bottom. The page remembers which panel is uncollapsed and the scroll
position on refresh.
Tested: Ran flextape locally, added load wrapping some `sleep` commands,
and observed `localhost:6433/queue`:
Jira: INFRA-288
=> flextape: Add server-side HTML UI

scripts/gee
gee: remove \"git branch --show-current\" calls.
The hw-dev containers only support git version 2.17.1, which does not support
the `git branch --show-current` call.  To maintain backwards compatibility,
those calls have been replace with `git rev-parse  --abbrev-ref HEAD`.
Tested:
* installed patched gee in hw-dev container.
* reloaded gee's bash_setup functions.
* verified that git error messages are gone.
PR generated by jonathan from branch gee_backwards_compat.
=> gee: remove \"git branch --show-current\" calls.

scripts/gee
scripts/gee: add title to merge-commit message, allow edits.
I accidentally omitted the PR title from the squash-merge commit message.
This PR fixes the automatic production of the commit message to include the
PR title as the first line.
I also added an option for the user to edit the commit message at the
last moment before submitting, just in case.
Tested:
- Passes shellcheck.
- Using this version of the tool to submit.
PR generated by jonathan from branch gee_pr_description3.
=> scripts/gee: add title to merge-commit message, allow edits.

flextape/server/run.sh
This change updates the deployed version in `run.sh` to match what is
currently running on `build-00`
Tested: Currently running on `build-00`
Jira: INFRA-288
=> flextape: Update deployed version

faketree/faketree_test.sh
$UID is a bash feature, not a feature of posix, so the test would fail while using dash. 
This succeeds using dash, changes the way to get user id.
=> Change faketree $UID to $(id -u)

lib/token/BUILD.bazel, lib/token/multi.go, lib/token/multi_test.go, lib/token/symmetric.go
Add support to generate tokens that can be decrypted by different
keys.
This is in preparation for future code, but it allows to generate tokens
meant for specific systems to consume them, while issuing a different
key to each such system.
It can also be used to implement schemes where data is stored with
an escrow key alongside a per-user/per-session key, or where data
is encrypted to be sent to different recipients.
=> lib/token: add multi encryption support.

WORKSPACE, proxy/BUILD.bazel
This PR adds a few rules to build a distroless container with enproxy,
and to upload it to gcr.
I realized today that while I had used this rule multiple times in
the past, I had never merged it in.
=> enproxy: add rules to release docker image.

lib/khttp/krequest/request.go
(this is in preparation for follow up PRs)
Background:
When fetching a resource via HTTP, the client needs to know the
IP of the server, and the "name of the server" that will be used
in the "Host:" header to retrieve the server.
Typically, both the IP and Host header are computed from the URL
to retrieve. Eg, "get http://www.google.com/" will resolve www.google.com
to an IP, and add a Host header containing "www.google.com".
The golang libraries default to the same behavior: compute the
Host and IP from the URL to retrieve.
This is a problem in testing, when connecting to a reverse
proxy, or set of load balanced backends, eg, when the IP resolution
does not match the host that needs to be retrieved.
In this PR:
- add the ability to override the host independent of
the URL to be …
=> lib/khttp/krequest: allow to override the host header.

lib/khttp/server.go
(in preparation for next PR)
Before this PR: pretty much the only way to start the server
was via defining flags, and creating the object via flags.
In this PR: break down the initialization so it's easy to
create the object without flags.
=> lib/khttp/server.go: allow to start a server without flags.

infra/postsubmit/proto/BUILD.bazel, infra/postsubmit/proto/postsubmit.proto
This change adds a documented protobuf that lays out the configuration
for postsubmit builds. Each configuration will be an
`infra.postsubmit.Build` message in its own configuration file;
Terraform and other configuration will be generated from this high-level
config and applied to create the builds in GCP.
Tested: Builds
Jira: INFRA-361
=> postsubmit: Define build configuration proto

.gitignore, infra/cloudbuild_staging/.terraform.lock.hcl, infra/cloudbuild_staging/README.md, infra/cloudbuild_staging/enkit_bazel_postsubmit.yml, infra/cloudbuild_staging/enkit_postsubmit.tf
This change adds a Terraform config that attempts to create the
following:
* a Cloud Build for the `enkit` repository
* a cron trigger in Cloud Scheduler for the aforementioned build
* an SMTP notifier that sends build failure notifications via Cloud Run
...in accordance with the manual setup steps described
[here](https://cloud.google.com/build/docs/configuring-notifications/configure-smtp)
and
[here](https://cloud.google.com/build/docs/automating-builds/create-scheduled-triggers).
Since this is our first official foray into Terraform, the directory
includes a README about how to install and use Terraform, as well as
manual setup steps for a new project that can't be done inside
Terraform.
This change commits the Terraform lock files as well as the recorded
state after `terraform apply` …
=> cloud build staging: Add initial Terraform

bazel/go_repositories.bzl, go.mod, machinist/example/deployment/docker-compose.yml, machinist/mserver/BUILD.bazel, machinist/mserver/command.go, machinist/mserver/controller.go, machinist/polling/BUILD.bazel, machinist/polling/register.go, machinist/state/controlplane.go, machinist/testing/machinist_e2e_test.go
These are just a collection of bug fixes for machinist that needed to get done for NC/MTV
Problems:
- settting the state file and dns port did nothing to the internal application
- machines would error out if they had the same name instead of updating in place (people wanted this changed)
Solutions:
- state.AddMachine no longer errors if the machine is the same name, updates in place instead
- updates our go.mod and updates the golang-protobuf library a minor version (Note, not protobuf, but the go library bindings)
- Puts the DNS port and the state files from the CLI to the running 
- Fixes a flakey e2e test. 
- Removes random print statements
=> Machinist Bug Fixes

lib/server/run.go
- Problem: lib/server doesn't accept http.Handler, but the concrete type that implements it.
- Solution change it from the concerte http.ServeMux to the interface http.Handler
Tested: bazelisk test //..., no changes all tests are the same. bazelisk build //test/... works now.
=> INFRA-351 change lib/server types accepted

kbuild/v2/sample-runner.sh
This patch corrects a minor typo in the example builder script that
prevents it from runnnig correctly.  Needed to change "DEB" to "APT"
in a couple of spots.
=> kbuild/v2: fix typo in example script

bazel/linux/run_um_kunit_tests.template
As noted in the comment, this prevents a path string overflow. Without
this change, the mconsole initialization fails:
```
printk: console [stderr0] disabled
umid_file_name : buffer too short
```
And it succeeds with it:
```
printk: console [stderr0] disabled
mconsole (version 2) initialized on /tmp/tmp.tOCqXFlP01/zbnwLP/mconsole
```
=> kunit: Use an ephemeral tmp path as the UML directory

faketree/faketree_test.sh
When testing with `@enkit//faketree/...` the location of the binary is actually located in `external/`
This just allows for a fallback to find the binary in case it isn't located as a first party test.
http://buddy.bazel.corp.enfabrica.net/invocation/023bed4d-e347-4067-bbbb-5487ff3f8c90
=> Changes to get Faketree to work as a test dependency

flextape/client/BUILD.bazel, flextape/client/flextape_client/BUILD.bazel, flextape/client/flextape_client/main.go, infra/postsubmit/proto/BUILD.bazel, proxy/BUILD.bazel
The original license manager client has two code paths: one that talks
to the old server, and one that talks to the new server. The old server
is no longer in use.
This change copies the code path that talks to the new server into a new
binary under //flextape/client/flextape_client. This will allow us to
delete the entire //manager subtree in a future change.
This change prepares us to add signal handling required for INFRA-418
more cleanly.
Jira: INFRA-418
=> flextape client: Move to separate binary

lib/config/marshal/BUILD.bazel, lib/config/marshal/marshal.go, lib/config/marshal/marshal_test.go, lib/config/marshal/select.go, lib/config/marshal/select_test.go, lib/token/BUILD.bazel, lib/token/token.go, lib/token/token_test.go
TypeEncoder in lib/token would always use gob encoding, and could
use gob encoding only. While we had support for arbitrary marshallers
in lib/config/marshal, gob was not usable.
In this PR:
- add support for gob encoding in config/marshal, so gob is
treated just like any other format supported.
- change token.TypeEncoder to use config/marshal. Specifically:
- it now users marshal.Marshal/marshal.Unmarshal instead of
hardcoding gob support.
- it now provides a setter so an arbitrary marshaller can be
selected.
Additionally:
- add initial tests for config/marshal. Goal for now is to just
cover the added functionality.
- add tests in token_test.go to cover marshalling/marshalling with
an arbitrary marshaller passed to type encoder.
Tested: all unit tests in lib/token and …
=> lib/token: use config/marshal from TypeEncoder

lib/knetwork/echo/BUILD.bazel, lib/knetwork/echo/echo.go, lib/knetwork/echo/echo_test.go
Background:
Verifying that tunnels work as expected requires having a TCP endpoint
we can write to, and read from. This is a common enough pattern that
it's worth having a simple object to use that implements this feature.
This PR:
- implements a very naive TCP echo server. What's written to it gets
written back.
- over features, I chose simplicity. There's very little code here.
This also means the implementation is very naive: for example, on
Close(), it terminates only the listening socket. All other sockets
will terminate when the client disconnects. Also, no timeouts are
implemented.
=> lib/knetwork/echo: small and naive echo server for testing.

proxy/BUILD.bazel, proxy/enproxy/BUILD.bazel, proxy/enproxy/enproxy.go, proxy/enproxy/enproxy_test.go, proxy/main.go, proxy/nasshp/nassh.go
The enkit proxy creates a MUX that is able to dispatch to an
http proxy, or to the nassh tunnel handling (which happens to
use websockets and GET/POST requests via HTTP).
Creation of this MUX was performed directly from main, together
with a bunch of flags/configuration parsing.
Among other things, this made testing harder.
In this PR:
- break out code out of main() into a dedicated object, under
enproxy/. This object follows the common conventions in the
enkit/ repo, allowing direct initialization via flags or via
simple modifiers/functors.
- add unit test covering the basic functionality of the proxy
as well as ability to establish tunnels.
Note that this PR is still in preparation for follow up PRs:
THERE WERE NO BEHAVIORAL CHANGES IN THIS PR. Tried to minimize
code changes as much as …
=> proxy/: refactor for modularity and testing.

flextape/client/client.go, flextape/client/flextape_client/main.go
This change listens for SIGINT/SIGTERM and kills the child process
before exiting by cancelling the appropriate context.
Before this change, issuing a signal via e.g. `kill` would kill the
`flextape_client` process, but not the process that it was wrapping.
This makes manual cleanup on worker nodes more tedious than it needs to
be.
This change allows us to reliably kill both processes by issuing a
single SIGINT/SIGTERM.
Tested:
* Started local flextape server
* Started client wrapping a `sleep 60` command: `bazel run
//flextape/client/flextape_client -- localhost 6433 xilinx vivado
sleep 60`
* Looked for both the sleep and the flextape_client invocation: `watch
'ps -ax | rg "sleep|bazel"'
* Sent a SIGINT to the `flextape_client` invocation: `kill -2 <pid>`
* Confirmed that `sleep 60` was …
=> flextape client: Kill wrapped process on SIGINT/SIGTERM

.github/CODEOWNERS, bestie/server/BUILD.bazel, bestie/server/main.go
This change modifies bestie to prepare it to run in k8s instead of Cloud
Run:
* Server is changed to the "normal" server rather than the one
specifically for Cloud Run (which needed a different setup for
proper HTTP/2 handling)
* Bazel rule to deploy to Cloud Run is removed
This change also adds Greg as a codeowner of bestie.
Tested:
* brought up server locally with `bazel run //bestie/server:bestie`
* Metrics endpoint is alive: `curl localhost:6433/metrics`
* Prints BES messages when pointing bazel at it with `bazel build
//bestie/... --bes_backend=grpc://localhost:6433`
Jira: INFRA-436
=> bestie: Remove Cloud Run support

proxy/BUILD.bazel, proxy/amux/BUILD.bazel, proxy/amux/amuxie/BUILD.bazel, proxy/amux/amuxie/amuxie.go, proxy/amux/mux.go, proxy/enproxy/BUILD.bazel, proxy/enproxy/enproxy.go, proxy/httpp/BUILD.bazel, proxy/httpp/build.go, proxy/httpp/build_test.go, proxy/httpp/proxy.go, proxy/nasshp/nassh.go, proxy/nasshp/nassh_test.go, proxy/ptunnel/tunnel_test.go
Background:
http handlers that require WebSockets need to be passed an http.RequestWriter
that can be type casted into an http.Hijacker.
This dependency is not well documented.
The proxy code further requires a Mux that can match host names.
Given that the default http.Mux cannot match on hosts out of the box,
back when the code was written I ended up using muxie (popular and
very performant, used by the iris framework).
When testing nassh, I realized that the gorilla library for WebSockets
used by nassh was not working, but I could not pinpoint the exact issue, and
thought it was a problem between gorilla WebSockets, and non-gorilla
mux.
To work around the problem I ended up using a hack where I combined multiple
muxes together: a simple domain mux (in khttp, hand written), a default …
=> proxy: mux cleanup and bug fix.

scripts/gee
gee: ignore "apt update" errors
Some of our installations have stale/broken links to certain launchpad
repos ( https://enfabrica.atlassian.net/browse/INFRA-383 ).  This causes
"sudo apt update" to fail with exit code 100, which then causes gee to
fail when trying to install missing tools.  gee now works around this
issue by ignoring all exit codes from "apt update."
Tested:
Ran "gee repair" on hw-dev-00, which has a broken repo configured.
PR generated by jonathan from branch gee_workaround_apt.
=> gee: ignore "apt update" errors

scripts/gee
gee: fix resurrection of deleted branches
When the user says "gee rmbr foo", gee emits instructions for how to undo the
deletion of the branch, usually something like "gee make_branch foo <sha>".
Unfortunately, those instructions didn't work right, leaving the gee client in
a detached head state that was causing some gee operations to fail with fatal
errors.
This PR changes the behavior of "gee make_branch foo <sha>" to do what was
originally intended: it makes a new branch named "foo", and then resets the
HEAD ref of that branch to be <sha>.
Tested:
1. Created a branch.
2. Deleted that branch.
3. Peformed branch necromancy using "gee mkbr".
PR generated by jonathan from branch gee_mkbr_sha.
=> gee: fix resurrection of deleted branches

faketree/faketree_test.sh
Currently the test for fake assumes that /etc is readable by the executing user. this is not the case in most CI environments.
This replaces the dependencies in /etc with random /tmp ones.
=> faketree: make work in remote tests

bestie/server/BUILD.bazel, bestie/server/main.go, bestie/server/service.go, bestie/server/testresult.go
Defined the following metrics for monitoring the BES Endpoint
service through Prometheus and Grafana:
- total number of Bazel builds seen
- count of each Bazel event, tagged by event ID
Also replaced the regex with a much simpler check for any test
output file ending with ".metrics.pb" to be processed for
test result metrics.
Tested: 'bazel run //bestie/server:bestie' to run BES Endpoint
locally on port 6433. Ran a 'bazel test' client command multiple
times, with --bes_backend=grpc://localhost:6433, to generate a
variety of Bazel events through the endpoint. Set up a local
Grafana dashboard to observe Prometheus metrics being updated.
Jira: INFRA-438
=> bestie: Add initial BES Endpoint service metrics

machinist/mserver/controller.go, machinist/mserver/mserver.go, machinist/testing/machinist_e2e_test.go
Adds a feature where people can see what machines are currently in the dns server by calling the _info record
=> machinist: add _info endpoint

infra/postsubmit/proto/BUILD.bazel, lib/kbuildbarn/BUILD.bazel, lib/kbuildbarn/README.md, lib/kbuildbarn/options.go, lib/kbuildbarn/urls.go, lib/kbuildbarn/urls_test.go
Does the following:
- establishes the pattern to add functional, "optional" options
- adds in support and testing to generate bytestream urls.
- tests all url generation.
=> Support for Bytestream Urls, Options and Url generation testing

scripts/gee
gee: consistently send logs to stderr
Fixing a small pet peeve in gee.  Now all log messages go to stderr, as they
should.
Tested:
This now works as it should:
gee whatsout | xargs wc -l
PR generated by jonathan from branch gee_logging.
=> gee: consistently send logs to stderr

flextape/service/BUILD.bazel, flextape/service/service_test.go, lib/bes/BUILD.bazel, lib/bes/buildbuddy.go, lib/bes/buildbuddy_test.go, lib/knetwork/echo/BUILD.bazel, lib/testutil/BUILD.bazel, lib/testutil/assert.go, lib/token/BUILD.bazel
This change adds a simple BuildBuddy HTTP-based client with a method
that can fetch all BES events for a particular invocation ID.
`assertProtoEqual` test helper method moves out of flextape tests to the
`testutil` package so it can be shared by package `bes`'s tests.
Jira: INFRA-468
=> bes: Add library to fetch BES logs from BuildBuddy

enkit/BUILD.bazel, enkit/main.go, enkit/outputs/BUILD.bazel, enkit/outputs/commands.go
This change adds enkit subcommands for bazel artifacts mounting, as laid
out in
https://docs.google.com/document/d/1L9skX1BKY-AZ15GVypQWxiy360UkUo5mNXglC9vvO9g/edit#.
These commands will need to tie together functionality from faketree,
bb_clientd management, and zipfile/tempdir management, so unlike other
enkit subcommand trees there is no pre-existing logical source location
to put the commands themselves. For now, they are added as a package
under `enkit` itself.
Tested: Output for help of each command:
`enkit outputs mount`:
```
Mount the build outputs of a particular invocation
Usage:
enkit outputs mount [invocation ID] [flags]
Examples:
$ enkit outputs mount 73d4a9f0-a0c4-4cb2-80eb-b4b4b9720d07
Mounts outputs from build 73d4a9f0-a0c4-4cb2-80eb-b4b4b9720d07 to the
default location. …
```
=> Bazel FUSE: Add enkit commands

bazel/dependencies/BUILD.bats.bazel, bazel/dependencies/BUILD.bats_file.bazel, bazel/deps.bzl
Background:
bats is a unit testing framework for shell scripts.
When using @// syntax to refer to a file, it always refers to the
current workspace. Eg, if the defs.bzl is invoked from a repository
by a namespace called internal, @// will refer to "internal".
- use @enkit - so the BUILD.*.bazel files can be used from other
repositories without copying them.
- import bats_file library, so we have the full set of tools.
=> bazel/bats: configure it in a way so it is usable from other repos.

lib/kbuildbarn/BUILD.bazel, lib/kbuildbarn/options.go, lib/kbuildbarn/protoparse.go, lib/kbuildbarn/protoparse_test.go, third_party/bazel/src/main/java/com/google/devtools/build/lib/buildeventstream/proto/BUILD.bazel
What this does:
Generates out a generic LL of symlinks out of a NamedSetOfFiles protobuff message. Each node of the LL contains a source and destination symlink, formatted for bb_clientd cas and scratch directory.
=> kbuildbarn: start formatting symlink urls

proxy/amux/BUILD.bazel, proxy/amux/amuxie/amuxie.go, proxy/amux/mux.go, proxy/amux/mux_test.go
Background:
DNS allows domain names ending with a trailing ".", eg, "www.enfabrica.net."
or "www.google.com.". Adding a trailing dot is considered best practice
when specifying domain names in cli tools, bots, or automated systems
in general, as - without a trailing . - the name is considered "relative"
by DNS resolver library, and will be looked up multiple times in DNS
using the "search" domains in resolv.conf, increasing the load on DNS,
and possibly leading to very unexpected results.
An http server should generally treat "enfabrica.net" and "enfabrica.net." as
exactly the same domain. Golang muxes (and most web servers) don't do this by
default, introducing various kind of problems (see a good discussion here:
https://news.ycombinator.com/item?id=5384864, using a trailing period on …
=> proxy/amux: handle domains with trailing ".", add conformance tests.

proxy/nasshp/BUILD.bazel, proxy/nasshp/blocking.go, proxy/nasshp/blocking_test.go
Background:
tunnel users will block waiting for data to arrive or for space in buffers.
When new data arrives, or when more space becomes available, those clients
need to be woken up and signaled. This is implemented using the Waiter()
class in this file.
This PR introduces 3 changes:
1) Wake up clients more aggressively. Specifically, it may be viable to
empty more of the buffer on reset (buffer can be rewind), and there
may be more space to fill after... data has been removed.
2) Don't close the channel on Fail. closing channels in go is optional,
the garbage collector can entirely take care of that. But once a channel
is closed.. closing it again, or writing on it, will result in panic.
This made writing code calling Close() extremely fragile and very
hard to get right, as it required …
=> proxy/nasshp: ensure the tunnel never blocks.

proxy/nasshp/browser.go, proxy/ptunnel/tunnel.go
Background:
The API allows users of ptunnel to, well, close the tunnel when desired.
In the current implementaion if a tunnel is closed without error,
the library will keep trying to connect anyway.
In this PR:
- make sure errors are propagated correctly, implement Unwrap in one
of the internal error types.
- have a well defined error returned by close, so the rest of the
code can do the right thing.
Tested:
end to end test (in another PR) does not timeout, Close() results in clean
shut down.
=> proxy/nasshp: correctly handle close request.

proxy/nasshp/window.go
Background:
During latest rounds of testing, I noticed that during some rarer
error conditions and resumes, the connection would contain corrupted data.
This PR fixes those problems.
Specifically:
- "buffer" represents all data buffered. "pending" data still to
acknowledge. "offset" indicates parts of the data that has already
been consumed ("emptied") from the buffer.
When a reset is received "rewinding" the connection, some data
is "unemptied" - eg, the cursor can move back. This generally
causes "pending" data to become "buffer" data again, and well,
causes the "offset" counter to be moved back.
The old code assumed that it was the _last_ buffer that had
an offset to be zeroed/decremented, which is incorrect.
Data is always emptied/consumed from the _first_ buffer.
The code above …
=> proxy/nasshp: fix incorrect resume under very specific conditions.

proxy/nasshp/browser.go
Background:
go support a great race detector. By turning on the race detector
for all the tests in proxy/, it detected a couple issues in browser.go.
This PR:
- addresses all detected races in the proxy/ codebase, by changing
rack/wack variables to use atomics, which was the initial intent
when the code was written.
Tested:
Before this change, running the tests for enproxy with the race
detector on reported problems in browser.go. After this change,
no races are detected.
=> proxy/nasshp: make the code race free.

proxy/enproxy/enproxy.go, proxy/main.go
Background:
Up until this PR, the only way to validate a config file and set
of flags was to start a proxy server, which is extremely inconvenient,
as it requires taking down the old proxy and starting a new one,
and... only then you find out if there's a config error.
In this PR:
- added a simple --validate-only flag, which prevents starting the
proxy, but still does as much of the config file validation as
possible. Causes a non-zero exit status in case of error.
Additionally:
- improve the messages printed in case of configuration file errors.
Tested: right now, run the main manually with and without --validate-only, and some invalid flag combinations. I expect to add a sh_test or similar in an upcoming PR.
=> proxy: add support for --validate-only flag.

scripts/gee
gee codeowners: parse reviewer state
This PR adds an annotation to the "codeowners" output to display the
review state (COMMENTED, APPROVED) for each reviewer, if available.
This information can be used to make sure only the necessary people
get pinged.
Tested: ran "gee codeowners" command in a few branches, with and without PRs,
with and without reviews.
PR generated by jonathan from branch gee_codeowners_state.
Derived from branch gee_codeowners's PR #315.
=> gee codeowners: parse reviewer state

WORKSPACE, infra/cloudbuild/presubmit_bazel.yaml, proxy/amux/BUILD.bazel
This change has fixes to address the following issues we see in
presubmits currently:
* occasional timeouts -> timeout raised to 30m from 20m
* query errors on grpc_web repositories -> grpc web plugin repositories
loaded for Windows and MacOS, even though they are unused
Tested: `bazel query 'deps(//...)'` now runs successfully locally
=> presubmit: Fix issues

infra/cloudbuild/presubmit_bazel.yaml
Now that the developer image has a recent version of enkit, we can
migrate off of the custom version with the patched version of enkit
(originally done to get a version of enkit with the bazel presubmit
subcommands).
This change causes the presubmit to use whichever image is tagged
`enkit-bazel-presubmit`, which will allow us to update the presubmit
container without code changes in the future (build reproducibility
concerns are relaxed around the presubmit itself, so no need to pin to
specific image hashes).
Tagged image is `3a1381e7931d2d50304acba6bb6d2848af6937369481572cb0719dcbe41ab33e`, uploaded yesterday by @ccontavalli:
Jira: INFRA-111
=> presubmit: Move to canonical dev image

astore/rpc/BUILD.bazel, machinist/rpc/BUILD.bazel, ui/yarn.lock
Problems: 
- once of the dependencies was not on the right version in the yarn.lock, causing `bazelisk build //...` to fail. Regenerating yarn.lock fixes this. 
- changes the ordering of proto declaration in machinist and astore 
...works now with bazel 5.0
=> bugfixes: update yarn lock

bestie/proto/test_metrics.proto, bestie/server/BUILD.bazel, bestie/server/bigquery_metrics.go, bestie/server/main.go, bestie/server/service.go, bestie/server/testresult.go
This continues the work of #394 and #406 by adding support
for uploading test metrics to BigQuery. The changes in this
PR do the following:
- Read and process metrics contained in *.metrics.pb file(s)
produced during bazel test runs. Format and push these
test metrics to the BigQuery 'bestie-builds.<dataset>.testmetrics'
table, where <dataset> is specified by the --dataset command line
parameter.
- Supports both file:// and bytestream:// schemes for the
outputs.zip file in the TestResult event, which correspond to
local and cluster operation of the BES Endpoint, respectively,
using APIs provided by enkit/lib/kbuildbarn. A new --baseurl
command line parameter allows a deployment-specific base URL
to be specified.
- Adds several service metrics related to BigQuery interactions
for …
=> bestie: Add test metrics upload to BigQuery (#423)

enkit/outputs/BUILD.bazel, enkit/outputs/commands.go, proxy/ptunnel/BUILD.bazel, proxy/ptunnel/exec/BUILD.bazel, proxy/ptunnel/exec/exec.go, proxy/ptunnel/tunnel.go, proxy/ptunnel/tunnel_test.go
This change adds a few helper functions:
* A function to determine if a particular host requires a tunnel for
communication
* A function to start and background a tunnel to a particular host
listening on a port
These helper functions are used to allow `enkit outputs` subcommands to
determine:
* if a tunnel should be started to communicate with buildbarn
* if so, start a tunnel and replace the destination port with the local
port the tunnel is currently listening on
Tested: `enkit outputs mount` gets past tunnel initialization to a
BuildBuddy error (no invocation ID supplied)
Jira: INFRA-507
=> enkit outputs: Start tunnel when necessary

enkit/outputs/commands.go
problems: 
- cluster host in the url should not include port
- default port was wrong
[INFRA-518]
[INFRA-518]: https://enfabrica.atlassian.net/browse/INFRA-518?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fuse: fix outputs mount command

enkit/outputs/commands.go
Prior to this change, bb_clientd was started with a hardcoded port,
instead of the port of the actual service or the tunnel, if one
was opened.
This change removes the hardcoded port and passes the correct port to
bb_clientd initialization.
Tested:
```
bazel run //enkit:enkit -- \
outputs \
mount \
--invocation=6175ddd6-de64-447d-a827-87bba04391f4 \
--url=<REDACTED> \
--api-key=<REDACTED> \
--buildbarn_host=<REDACTED>
cat ~/outputs/6175ddd6-de64-447d-a827-87bba04391f4/test.log
```
Jira: INFRA-518
=> Bazel FUSE: Propagate correct port to bb_clientd

scripts/gee
gee codeowners: fix for "WORKSPACES" (tiny PR)
I noticed that `gee codeowners` wasn't reporting the right codeowners for
changes to WORKSPACES.  Turns out this was an edge-condition in my rules
processing code that only affects rules that aren't wildcards, and the
file in question happens to be in the root directory of the repo.
While I'm in here, I also snuck in a purely cosmetic improvement to
the markdown format of the generated codeowners comment.
Tested:
- made a test branch and only changed the WORKSPACES file
- verified that "gee codeowners" reported the right owners.
=> gee codeowners: fix for "WORKSPACES" (tiny PR)

enkit/outputs/commands.go, lib/kbuildbarn/exec/bb_clientd.go
What this does: 
- implements the shutdown command by:
* unmounting the mount directory
* killing the bb_clientd process
* deleting the output base
=> fuse: implement shutdown command

scripts/gee
gee diff: support diffing upstream pull requests.
`gee pr_checkout` works to create a branch from an upstream PR.
`gee up` successfully integrates new commits from upstream.
but `gee diff` wasn't working, even though it used the same syntax as `gee up`.
I finally figured out why, and the hack I need to fix it.  I've updated
`gee diff` to do the right thing when diffing against an upstream pull ref.
Tested:
Ran "gee diff" from within a pr_NNN branch.
```
$ cd ~/gee/enkit/pr_432
$ ../gee_diff_upstream/scripts/gee diff
CMD: /usr/bin/git fetch upstream refs/pull/432/head
From github.com:enfabrica/enkit
* branch            refs/pull/432/head -> FETCH_HEAD
CMD: /usr/bin/git diff FETCH_HEAD
diff --git a/scripts/gee b/scripts/gee
index c9b89bc..beb5e61 100755
--- a/scripts/gee
+++ b/scripts/gee …
```
=> gee diff: support diffing upstream pull requests.

bazel/go_repositories.bzl, bestie/server/BUILD.bazel, bestie/server/testresult.go
Change the handling of the outputs.zip file so that it is not
read into memory prior to processing each of its file elements.
Use the https://github.com/xenking/zipstream package to iterate
through each of the files, looking for file names ending in
.metrics.pb.
Tested: Ran BES Endpoint service both locally and in the staging
cluster, where it detected the test.metrics.pb file produced by
a standalone test app.
Jira: INFRA-504
=> bestie: Use zipstream package to read outputs.zip

enkit/outputs/BUILD.bazel, enkit/outputs/commands.go, faketree/exec/exec.go
This change implements `enkit outputs run` when either a zip file is
passed (perhaps from a previous `enkit outputs mount`) or a dir is
passed (maybe from an already-unzipped outputs.zip)
Tested: `enkit outputs run --zip_path ~/tmp/outputs.zip` manually on
local zip file - reroots the zip to `/enfabrica`, and starts a shell at
that path.
`enkit outputs run --zip_path ~/tmp/outputs.zip cat cartoons.txt` skips
the shell and instead prints the contents of the file.
Jira: INFRA-514
=> Bazel FUSE: Implement run with zip_path, dir_path

enkit/outputs/commands.go, lib/kbuildbarn/exec/bb_clientd.go, lib/kbuildbarn/exec/templates/config.jsonnet
When using a tunnel, two hostnames are requried:
* The host to tunnel to (`pbzl.service.enfabrica.net`)
* The host to make requests to (`build.local.enfabrica.net`)
The latter is required because the tunnel host is typically a
non-routable internal IP, whereas this host resolves to localhost if a
tunnel is required; additionally, ingress will route requests based on
the destination host, which is expected to be the build.local... host.
This change breaks the single host flag into two flags: One is used to
resolve to a non-localhost address (if no tunnel is required) or a
localhost address (if a tunnel is required), and requests are to be
directed to this URL. The new flag specifies the endpoint to tunnel to
if a tunnel is required.
Tested:
```
bazelisk run //enkit:enkit -- \
outputs \ …
```
=> Bazel FUSE: Separate request host from tunnel endpoint

bestie/server/BUILD.bazel, bestie/server/bigquery_metrics.go, bestie/server/testresult.go
Just renaming one of the metric tags that get inserted by the
BES Endpoint using information from the BES TestResult event.
The 'test_name' tag identifier can be easily confused with a
testcase name tag supplied by the test client application.
Since this represents the test target specified for the
'bazel test' command, the 'test_target' tag identifier
seems more appropriate.
Tested: Verified using a localhost instance of the BES Endpoint
that the new tag identifier is processed correctly and appears
in the BigQuery testmetrics table.
Jira: INFRA-551
=> bestie: Rename metric tag test_name to test_target

scripts/bkup
bkup: add volume id support, filters
When I had to use bkup to restore an old laptop's file to a new laptop, one
snag I ran into is that bkup uses the docker ID as a UUID to disambiguate
different machines owned by the same user.  But if I want to restore another
machine's data to this one, I need a way to override the generated ID.
This PR solves the problem by dropping a "volume_id.txt" file in the
.config/rclone directory.  If this file doesn't exist, it is created
and populated with the docker image ID.  This file can be overriden
to restore backups that were created on a different machine.
I also added a "lsvolumes" command to list all available volume ids.
Also, I learned that git repositories are too big to realistically
save and restore.  These are *probably* backed up to remote …
=> bkup: add volume id support, filters

scripts/bkup
bkup: remove remote files that were deleted locally
When restoring from backup, I noticed that "rclone sync --update" wasn't
removing locally deleted files from the remote.
I addressed this by:
1.  removing `--update`
2.  adding `--backup-dir` to move overwritten/deleted files to a backup remote
location.
3.  adding an extra step to delete files older than 7 days from the remote
backup location.
Tested:
Testing it right now.
NOTE: this PR includes changes that are also in PR #462.
Review and submit that PR first, so that this PR will be
easier to read.
=> bkup: remove remote files that were deleted locally

lib/config/marshal/select.go, lib/config/marshal/select_test.go
When a YAML config is included in another config today by URL, the
config language detection by extension fails because it is passed a URL
that has a query string suffix instead of a local file path. When this
happens, the default unmarshaler of JSON is used, which causes obtuse
parse errors to be thrown when parsing other formats.
This change first tries to parse the input path as a URL, falling back
to the assumption that the path is a local file path if URL parsing
fails. URL parsing allows us to pick out the path component, ignoring
all other components like query strings that may suffix the string.
Tested: Added unit test to demonstrate issue and verify fix.
Jira: INFRA-487
=> marshal: Fix type detection when passed a URL

lib/kbuildbarn/BUILD.bazel, lib/kbuildbarn/buddy.go, lib/kbuildbarn/buddy_test.go, lib/kbuildbarn/protoparse.go, lib/kbuildbarn/protoparse_test.go, lib/kbuildbarn/urls_test.go
Prior to this change, all files mentioned in the output stream are
mounted in the scratch directory under the invocation ID using the path
specified in the BuildEvent message verbatim. This change modifies paths
in the following way:
* If the artifact is a test artifact, it is rerooted at
`bazel-testlogs/$LABEL/$RUN/$ATTEMPT/`, where `$LABEL` is a subdirectory
generated from the test target's label, `$RUN` is the run number
(there may be multiple runs for a given test if `--runs_per_test` was
passed on the bazel commandline) and `$ATTEMPT` is the attempt number
(if bazel retried a test marked flaky).
* If the artifact is a test artifact, its path is unmangled by replacing
`__` with `/`, which allows paths like `test.outputs__outputs.zip` to
be the more intelligible …
=> enkit outputs: Change mount paths for various files

astore/client/BUILD.bazel, bazel/astore/defs.bzl
This change ensures that the script generated by `astore_upload` rules
has a unique name per `astore_upload` target, so that multiple
`astore_upload` targets can coexist in the same BUILD file.
Tested: `bazel aquery //developer/enkit:all` errors in enfabrica/internal on master currently, but doesn't error with enkit patched with this change: `bazel aquery //developer/enkit:all --override_repository=enkit=/home/bminor/dev/enkit`
Jira: INFRA-583
=> astore_upload: Base script name off of target name

machinist/polling/metrics.go, machinist/polling/register.go
Problem:
atomic integers pin a cpu if dmesg is flooded, this removes the atomic integer.  
This is technically a NoOp since we don't have any grafana metrics currently using these machinist metrics.
Tested:
Ran 
```
bazelisk run //machinist/cmd:cmd -- controlplane --port=8080 --domains=hello.world --bind-net=127.0.0.1
```
```
bazelisk run //machinist/cmd:cmd -- node poll --auth-server=https://auth.corp.enfabrica.net --control-port=8080 --control-host=127.0.0.1 --ips=99.99.99.99 --name=hello
```
Flooded Dmesg via iptables:
```
sudo iptables -A INPUT -j LOG --log-level 3
```
And watched process usage.
=> machinist:  remove atomic integer count

WORKSPACE, bazel/dependencies/grpc/no_remote_tag.patch
This change imports gRPC to fix an issue where `py_proto_library`
targets work in workspaces that import enkit but not in enkit
standalone.
The crux of the issue is that other workspaces rely on gRPC's workspace
rules to initialize various binds, including one that maps local Python
headers to `//external:python_headers`. Since enkit doesn't import grpc,
it doesn't make this bind, which breaks the build graph.
This change moves the gRPC import configuration from
`enfabrica/internal` to this repository; once we update the enkit
reference in internal, the grpc initialization code there can be
dropped.
Tested: `bazel query 'deps(//...)'` was broken with #471 but is working
with #471 and this change.
=> enkit: Import gRPC to fix py_proto_library issue

CODEOWNERS, scripts/gee
CODEOWNERS: use right syntax for usernames
This is the companion PR to https://github.com/enfabrica/internal/pull/3101.
This corrects the syntax for specifying users by username in CODEOWNERS files.
Tested:
=> CODEOWNERS: use right syntax for usernames

bestie/proto/BUILD.bazel, bestie/proto/test_metrics.proto
The enkit repo owns the definition of test_metrics.proto and needs
to produce each of the language-specific protobuf libraries being
used, currently Go and Python. The latter is @enkit referenced
by the internal repo for writing metrics to its test.metrics.pb file.
Summary of changes:
- Added py_proto_library() target in bestie/proto/BUILD.bazel.
- Renamed KeyValuePair submessage to Tag in test_metrics.proto file.
Tested: Using a local instance of BES Endpoint, sent simulated test
metrics in a test.metrics.pb file for processing by the endpoint.
Required use of the --override_repository command line arg by
the client 'bazel test' command to reference the changes in the
enkit repo.
Jira: INFRA-593
=> bestie: Add py_proto_library target for test_metrics.proto

bestie/proto/BUILD.bazel
Anticipating BES Endpoint usage by the performance test team,
whose test cases are written in C++, this change adds a build
target to create the C++ protobuf bindings for the test_metrics.proto
file, which can be externally referenced from the internal repo
as "@enkit//bestie/proto:bestie_cc_proto".
Tested: 'bazel build //bestie/proto:bestie_cc_proto` to generate
the appropriate C++ protobuf .h and .cc files.
Jira: INFRA-615
=> bestie: Add cc_proto_library target for test_metrics.proto

faketree/faketree.go, faketree/faketree_test.go, faketree/faketree_test.sh
Background:
So far, faketree only supported bind mounts, eg, mounting one directory
on top of another.
This PR:
- implements a TODO in code, completing support for mounting arbitrary
directories.
This is partially in preparation for the next PR, where more of this
feature will be needed, and is a step toward fixing INFRA-256 and 
INFRA-535.
Tested: added unit tests, passing.
=> faketree: support mount options.

faketree/faketree.go, faketree/faketree_test.sh
The PID namespace was created *LAST*, just before execing the
desired command. This caused "a few problems":
1) The spawned command was effectively PID 1 in the namespace.
PID 1 is always a bit of an oddball, as the kernel treats it
differently from other processes. See "man pid_namespaces"
for details.
Specifically, if PID 1 dies all its children are SIGKILLed
automatically by the kernel, which in turn means that child
management has to be done correctly in the spawned command
(makes next PR not working/impossible to implement).
2) If --mount of /proc was specified, the mount would either
not work, or point to /proc outside of the namespace.
Mounting it correctly *required* doing it after the PID
namespace is mounted. Further, golang libraries fail
to properly create a …
=> faketree: change how the pid namespace is handled.

scripts/gee, scripts/gee.changelog.md
gee pr_make: support DRAFT and ABORT
Tested:
Used this PR to test:  PR was at first aborted, then
marked as a draft, and the converted from draft to ready.
=> gee pr_make: support DRAFT and ABORT

bazel/dependencies/BUILD.bats.bazel, bazel/dependencies/BUILD.bazel, bazel/dependencies/bats_root.patch, bazel/deps.bzl
* Update to `bats_core 1.5.0`
* Patch `bats_core` to fix `BATS_ROOT` bug that fails to correctly
calculate `BATS_ROOT` when executed in a remote bazel environment.
* Fix missing library tree in BUILD file.
Tested:
re-ran a few bats tests.
Jira: INFRA-498
=> bats_core: add missing source files, patch BATS_ROOT bug.

scripts/gee, scripts/gee.changelog.md, scripts/gee.md
gee: add "restore_all_branches" command
I recently had to restore my work environment from github.
This command ensures that my local repository reflects my remote origin
repository, adding all branches to the worklist and synchronizing them
with the remote heads.  It then runs "gee repair" to (imperfectly)
reconstruct branch parentage.
I have a "TODO" to find a way to make parentage metadata version controlled,
but that's a task for another day.
Tested:
I blew away my gee repository, and restored everything using:
gee init
gcd master
gee restore_all_branches
=> gee: add "restore_all_branches" command

scripts/bkup
bkup: fix filters, prompt user for a volume identifier
Auto-generating a volume UUID from the docker image is confusing.  Instead,
it's better to just ask the user to name the backup volume they want to save to
or restore from (for example: "chromebook1").  We only prompt once and then
save this cookie away locally.
While working on this PR, I noticed that my file filters weren't working the
way I expected them to.  It turns out that rclone's filter file format doesn't
support comments on the same lines as filters, so I removed them.
Tested:
Filter rules are tested with:
rclone ls ~ --filter-from ~/.config/rclone/filter-list.txt
and examining the files reported.
UUID prompting was tested by removing my laptop's `volume_id.txt` file and
running `bkup lsvolumes`.
=> bkup: prompt user for a volume identifier

bazel/cloud_run/defs.bzl
This change adds attributes to the `cloud_run_deploy` rule:
* `container_args`, which allow for passing additional arguments to the
container via the rule, rather than needing to embed them in the
containers' `cmd` or `entrypoint` facilities. Note that the container
must be set up to accept these args.
* `port`, which allows for starting containers that have a hard-coded
port on Cloud Run without jumping through hoops to get the containers
to respect `$PORT`. Containers should still listen on `$PORT` if
possible (in which case the attribute can be left at the default) but
in the case they do not, `cloud_run_deploy` allows the default port to
be overridden.
Tested: `bazel run --override_repository=enkit=/home/bminor/dev/enkit
//infra/bestie:prometheus_bq_remote_storage_adapter_deploy` …
=> cloud_run_deploy: Add args, port attributes

WORKSPACE, bazel/deps.bzl
This change updates rules_pkg to the latest version, which allows debs
to be included as data dependencies without crazy filegroup/output_group
hacks.
rules_docker is updated as well to be compatible with the new rules_pkg.
Tested: 
* Against internal via `--override_repository` to confirm that deb
data dependencies work as expected, via test PR
https://github.com/enfabrica/internal/pull/3501 modified to not use filegroup
* `bazel run //machinist/mserver/cmd:upload-image to check that Docker rules
still work as expected
Jira: INFRA-687
=> WORKSPACE: Bump rules_pkg version to latest

shims/buildbuddy/BUILD.bazel, shims/buildbuddy/cmd/BUILD.bazel, shims/buildbuddy/cmd/main.go, shims/buildbuddy/urls.go, shims/buildbuddy/urls_test.go
This is a shim designed to be routed at L7, and captures any /file/download url and rewrites it to have the bytestream url be the intra-cluster url name of the storage section of buildbarn. It then forwards to any url of choice (usually the existing buildbuddy service)
As far as integration tests go, this is installed on staging currently. Seems to work nicely. 
jira: INFRA-683
=> infra: create buildbuddy shim

bestie/server/bigquery_metrics.go, bestie/server/xml_result.go
To facilitate Grafana dashboard table displays, copy the
metricname into a new 'name' tag so that it appears among
the list of displayable entities for Grafana.
Support a new 'created' tag that contains a timestamp to
be used for the metric instead of the one defined as the
original timestamp field. This allows the test application
to define a single value timestamp that is stored in the
'created' tag for both the pass/fail testresult metric and
any associated data metrics generated by the test cases
during the same run. Grafana can then use the 'created'
tag (instead of the Prometheus scrape timestamp) as a
consistent way to filter all metrics for a given time
selection.
Tested: Ran `bazel test --cache_test_results=no --test_output=streamed \
--bes_backend=grpc://localhost:6433 …
=> bestie: Add 'name' and 'created' metrics tags support

flextape/service/service.go, flextape/service/service_test.go
This change fixes a nil pointer dereference by ensuring that a
prioritizer is set if the config doesn't specify a prioritizer.
Tested: Added unit test
Jira: INFRA-772
=> flextape: Fix crash on Allocate()

flextape/server/run.sh
The newest version of flextape crashes on Allocate(). This change rolls
back the run.sh script to the version that has been running more-or-less
problem-free on hw-dev-00 for a few weeks.
Jira: INFRA-772
=> flextape: Roll back to latest known good version

proxy/enproxy/BUILD.bazel, proxy/enproxy/enproxy.go, proxy/enproxy/enproxy_test.go, proxy/nasshp/BUILD.bazel, proxy/nasshp/browser.go, proxy/nasshp/counters.go, proxy/nasshp/nassh.go, proxy/nasshp/window.go, proxy/utils/BUILD.bazel, proxy/utils/counter.go, proxy/utils/types.go, proxy/utils/whitelist.go
Background on some design decisions:
1) a separate http server is started on a different port just
to export metrics. This simplifies authentication, https, and
simplifies the main mux used for proxying and ssh.
2) some objects that need to export metrics are instantiated
multiple times. This makes it hard to use the simple/default
globals.
3) some counters already exist in the code, and are used
internally for the engine to work.
4) some counters are in really hot paths, eg, per read/write
performed.
The design uses simple per-object counters, paired with
an object implementing the prometheus.Collector() interface
just like recommended in the docs when reading "legacy counters",
counters that already exist in code.
This also allows multiple instances of objects by using
things like …
=> enproxy: add basic prometheus metrics and plumbing.

scripts/gee, scripts/gee.changelog.md, scripts/gee.md
gee: add pr_push command
The pr_push command is a command for explicitly pushing commits from a
branch created with `gee pr_checkout` back into the author's PR branch.
Tested: Checked out a PR with `gee pr_checkout`, and then pushed a commit
into it user `gee pr_push`.  Remote user then ran "gee update" to pull
that change into their local branch.
=> gee: add pr_push command

flextape/server/run.sh
This change updates the image hash used for the deployed version of
flextape following the successful config update to use the `even_owners`
scheduler for all licenses.
Tested: not yet
Jira: INFRA-804
=> flextape: Update image hash

kbuild/v2/upload.sh
When publishing a URL to an artifact that already exists, the query
defaults to `uid=latest`, which breaks existing WORKSPACE rules that use
older UIDs. With --all, the query allows access to any version of an
artifact at that path.
Jira: INFRA-794
=> kbuild: Setup public URL to access all versions of an artifact

faketree/faketree.go, faketree/faketree_test.go, faketree/faketree_test.sh
Background:
All works well when Ctl+c is used, or when the job control system
sends SIGTERM (or later, SIGKILL). Signals are propagated, faketree
waits for all children to die.
But when the "main command" run by faketree (eg, the direct child)
completes (successfully, or crash), faketree now waits for all its
children to complete, assuming the "main command" is taking care
of all its children directly (on successful completion, or on exit,
when the job control system does not have to intervene).
For commands that don't clean up after themselves, this will cause
faketree to wait until --wait-timeout, and then SIGKILL all children
(which is risky, as it could cause once again license leak, and
could cause long waits).
In this PR:
- If the "main process" spawned by faketree completes, send
a …
=> faketree: send SIGTERM to children after the main command dies.

lib/knetwork/kdns/dns.go
Background:
Without NXDOMAIN, the query is marked successful even without results.
This can cause some clients to stop querying other dns names (when
implementing a resolv.conf 'search' walk, for example).
Fix is very simple:
- return NXDOMAIN status if there are no results.
=> machinist: return NXDOMAIN if there are no records for a query.

scripts/gee, scripts/gee.changelog.md
gee: fix pr_make failure
I introduced a bug in a previous PR.  I use "read" to scan a line of input,
but I forgot to handle the case where there are no open PRs.  This cause
read to exit with a non-zero exit code, causing the bash script to terminate.
The go rewrite can't come soon enough.
Tested: Made this PR using this version of gee.
=> gee: fix pr_make failure

bazel/linux/kunit/kunit.py, bazel/linux/kunit/kunit_config.py, bazel/linux/kunit/kunit_json.py, bazel/linux/kunit/kunit_kernel.py, bazel/linux/kunit/kunit_parser.py, bazel/linux/kunit/kunit_tool_test.py, bazel/linux/run_um_kunit_tests.template
3 commits here:
- import the unmodified kunit scripts from our enf/impish-19.19 kernel
tree.
- minor tweak to kunit.py to run without a complete kernel tree
- munge the test result to contain the number of test suites
Fixes: SF-73
=> Update kunit result parsing

scripts/gee, scripts/gee.changelog.md, scripts/gee.md
gee: implement pr_rollback command
This PR makes it easier to rollback a PR.  It generates the rollback branch,
rolls back the commit associated with the specified PR, and generates the
associated PR.
Tested:
DRYRUN=1 ./gee pr_rollback 444  # inspected commands
./gee pr_rollback 444  # generated a test rollback
=> gee: implement pr_rollback command

bazel/dependencies/BUILD.bazel, enkit/BUILD.bazel, enkit/cmd/BUILD.bazel, enkit/cmd/command.go, enkit/doc_gen/BUILD.bazel, enkit/doc_gen/main.go, enkit/outputs/commands.go, machinist/polling/BUILD.bazel, proxy/enproxy/BUILD.bazel
This change moves the command building that happens in `main.go` to a
separate library that returns a struct containing all the pieces with
convenience methods to run the command.
This facilitates writing a binary that emits markdown documentation from
enkit using a built-in cobra library. This documentation can serve as a
reference for users of enkit.
Tested: `bazel run //enkit/doc_gen -- --out-dir=/tmp/docs` works; `bazel
run //enkit -- login` still works.
Jira: INFRA-494
=> enkit: Move command building to library

bazel/utils/BUILD.bazel
This change fixes an import string that causes an issue when importing
enkit into other repositories. Because a `BUILD` file contains a
`load()` that starts with `@//`, this gets resolved relative to the
other repository, rather than relative to enkit.
This change removes the leading `@` so that the import is always
resolved relative to enkit.
Tested: `bazel query --override_repository=enkit=/home/scott/dev/enkit
'deps(//:cc_format)'` which shows the issue with enkit on master and
doesn't show the issue with this fix.
Jira: INFRA-494
=> bazel: Fix `load` import string

astore/server/astore/retrieve.go, astore/server/astore/retrieve_test.go
This change removes the sorting when querying by UID only, as it seems
that the Datastore indexes are not properly configured to handle this
case. Unit tests are updated, and for all affected cases, corresponding
GQL is documented in a comment and tested manually in the Cloud Console
to ensure there are no index issues.
Additional testcases are added to document the behavior of the TagSet
field as it exists (tri-state, different behavior when an empty set is
present vs. no set) but no behavioral changes are made to this case.
`rpc/astore` import is renamed to `apb` in the unit tests to make it
clear that this package is protobuf generated code.
Tested: See above
Jira: INFRA-830
=> astore: Remove Created sorting on some Retrieve queries

proxy/ptunnel/BUILD.bazel
This test can't run in Cloud Build due to differences in how the
loopback address is resolved. This change disables the test so that we
can get better signal from presubmits running on other changes.
=> tunnel_test: Disable in Cloud Build

astore/server/main.go
Background:
astore authentication has support for authenticating via github in
addition to google. We had to roll this back as the github support
for auth certificates was incomplete.
The current implementation still mandates supplying flags for the
optional authenticator, even when disabled.
In this PR:
- when additional authentication is disabled, do not mandate
supplying github flags.
- make error messages clearer.
=> astore: make github config fully optional.

astore/client/commands/commands.go
This change adds debug-level log statements for debugging why
downloading by UID doesn't work.
Jira: INFRA-830
=> astore client: Add debug logs

bazel/linux/defs.bzl, bazel/linux/kunit/BUILD.bazel, bazel/linux/kunit/kunit.py, bazel/linux/kunit/kunit_json.py, bazel/linux/kunit/kunit_kernel.py, bazel/linux/kunit/kunit_tool_test.py, bazel/linux/run_um_kunit_tests.template
This change fixes Python import paths and BUILD files for the kunit
binary/library to make it Bazel compliant.
An extra target is also defined to build a Python hermetic zip; this zip
file is ran instead of the script, so that we don't have to worry as
much about runfiles issues. The script template is modified to pass the
zip to python3, as the zip is not itself executable.
Tested: `BAZEL_PROFILE=buildbarn bazel test
//driver/farmem:enf_rma_unit_test
--override_repository=enkit=/home/bminor/dev/enkit` with internal PR
1656 works
=> kunit: Fix BUILD files, imports

bazel/linux/kunit/BUILD.bazel, bazel/linux/kunit/kunit_tool_test.py, bazel/linux/kunit/test_data/test_config_printk_time.log, bazel/linux/kunit/test_data/test_interrupted_tap_output.log, bazel/linux/kunit/test_data/test_is_test_passed-all_passed.log, bazel/linux/kunit/test_data/test_is_test_passed-crash.log, bazel/linux/kunit/test_data/test_is_test_passed-failure.log, bazel/linux/kunit/test_data/test_is_test_passed-no_tests_run.log, bazel/linux/kunit/test_data/test_kernel_panic_interrupt.log, bazel/linux/kunit/test_data/test_multiple_prefixes.log, bazel/linux/kunit/test_data/test_output_isolated_correctly.log, bazel/linux/kunit/test_data/test_output_with_prefix_isolated_correctly.log, bazel/linux/kunit/test_data/test_pound_no_prefix.log, bazel/linux/kunit/test_data/test_pound_sign.log, bazel/linux/kunit/test_data/test_read_from_file.kconfig
This change copies testdata that the unit test needs to run from
https://github.com/enfabrica/linux/tree/enf/impish-19.19/tools/testing/kunit/test_data,
and fixes the `py_test` rule to allow access to this data.
Tested: Unit test runs with `bazel test //bazel/linux/kunit/...`
=> kunit: Add unit test testdata

BUILD.bazel, bazel/go_repositories.bzl, go.mod, go.sum
This change replaces the mystery command that I keep forgetting with a
bazel run target, making it easier than ever to generate
go_repositories.bzl from go.mod.
Tested: `bazel run //:gazelle_update_repos`
=> gazelle: Add target for updating from go.mod

infra/postsubmit/proto/BUILD.bazel
This change adds a BUILD rule to generate Python code from
postsubmit.proto, in preparation for a Python conversion tool in
internal.
=> postsubmit: Generate Python stub

infra/postsubmit/proto/postsubmit.proto
This change adds a timeout field to the Build spec, which is the only
missing piece to onboard the FPGA nightly regression.
Tested: None
Jira: INFRA-876
=> postsubmit: Add timeout field

bazel/utils/BUILD.bazel, bazel/utils/build_test.bzl, bazel/utils/diff_test.bzl, bazel/utils/files.bzl, bazel/utils/testdata/escape_and_join1.expected, bazel/utils/types.bzl
Background:
A few utilities have been duplicated across repositories. A few extra
utilities were added. I have a need to use a couple of those utilities
(mainly, merge_kwargs and some friends) in enkit. Rather than track
the full set of deps, I added most utilities in the enkit repository.
It would be good to have a few more utilities, but for future PRs.
I will follow up this PR with a cleanup of other repositories to
re-use the now published utilities.
=> bazel/utils: update utils with internal changes, publish extra utils.

infra/postsubmit/proto/postsubmit.proto
This change adds fields to the Build message that are necessary in order
to migrate the two existing HW nightly regressions:
* `fpga-fullchip` passes a bunch of arguments to `bazel test` that we
need to preserve
* `fpv-nightly` makes use of positive tags in
`build_tag_filters`/`test_tag_filters`, and currently the proto
message only handles negative tags.
Jira: INFRA-875
=> postsubmits: Add more necessary fields

proxy/enproxy/enproxy_test.go
This PR will fail pre-submit until the other PRs are merged!
This test is particularly stressful as:
- it uses an echo server behind a fully running proxy.
This leads to a bi-directional ptunnel used in the client,
and bi-directional stream in the nasshp proxy.
- it uses io.Pipe to inject the data, which does no buffering,
and pretty much propagates reads and writes as they are.
- it sends a message that is a prime to the size of the buffer,
which helps trigger things like short writes at the
beginning and end of the buffer.
This test has highlighted all the bugs fixed in the series
of PRs I just sent out. Specifically:
- non clean Close() on close.
- short reads (which I had observed in production from log files)
- a few forms of corruption on reconnect (rarely, but visible
with …
=> proxy/enproxy: add end to end test for tunnel.

lib/khttp/BUILD.bazel, lib/khttp/server.go, lib/khttp/server_test.go
Background:
server.go was created out of the proxy in a hurry, turns out it's more
broken than I'd like to admit. In this specific case:
- flags were not prefixed properly
- description were not updated
- semantics were not intuitive
Last point bit me last night: I was assuming the port number to be
a default if not specified in the address, turns out that if an address
is specified at all, the port number is completely ignored.
In this PR:
- fix the prefix
- fix the description
- have the port number behave as a true default port number
Additionally, added small unit test, and go fmt.
=> khttp: fix server.go to be more reasonable.

astore/server/BUILD.bazel, bazel/appengine/defs.bzl
Background:
If gcloud is not passed a --project=, it will default to whatever
was configured when gcloud was last run. This is extremely risky.
In this PR:
- make passing a project= attribute mandatory.
- set project= in our BUILD.bazel file.
This rule should probably be moved to the internal repository.
Leaving it as a TODO for the future.
=> appengine: change rules to mandate providing a project attribute.

proxy/enproxy/enproxy.go, proxy/enproxy/enproxy_test.go, proxy/nasshp/BUILD.bazel, proxy/nasshp/browser.go, proxy/nasshp/counters.go, proxy/nasshp/nassh.go, proxy/nasshp/nassh_test.go, proxy/ptunnel/tunnel.go, proxy/utils/BUILD.bazel, proxy/utils/atomictime.go, proxy/utils/atomictime_test.go, proxy/utils/clock.go, proxy/utils/counter.go, proxy/utils/counter_test.go
Background:
When a client disconnects, enproxy does not close the session between
the proxy and the backend, so if the client comes back, the session
can be resumed.
This causes connections to build up over time, and pretty much leak
memory until the connections naturally die.
In this PR:
- add a few counters to keep track of orphaned connections, export
them to prometheus for monitoring.
- use those counters to periodically and automatically expire sessions.
Additionally, a few support classes were needed (and added):
- atomic time, to keep track of time atomically.
- a mock clock implementation, to abstract time.After.
It's a large PR, it could probably have been broken in two,
but it's hard to do after the fact.
Tested: written unit tests, will need to stage the change.
=> enproxy: add automated session expiration.

proxy/nasshp/counters.go, proxy/nasshp/nassh.go, proxy/nasshp/nassh_test.go
This PR adds the most notable missing counters: total amount of bytes
read/written to browser, read/written to the server.
=> enproxy: add bytes read/write counters.

lib/bazel/affected_targets.go
When the start query is broken but the end query is not, we may be in a
situation where the build graph is broken on master, and this presubmit
is for a fix PR, so we want to ignore the build graph breakage at the
start point.
However, for PRs that aren't fixing build graph breakage, we are
potentially passing the presubmit without actually testing anything.
This change logs the error that was encountered when evaluating the
build graph, to allow users to see and debug the underlying issue
causing query to fail.
Jira: INFRA-899
=> enkit bazel: Log error when start query broken

flextape/server/run.sh
Update production container to accept changes from 
https://github.com/enfabrica/internal/pull/4468/files
tested: deployed and checked metrics https://flextape.corp.enfabrica.net/metrics
=> Flextape: update sha of running container

flextape/client/client.go, flextape/proto/config.proto, flextape/server/main.go, flextape/service/service.go
All durations that the service uses are moved to a "server" config
section, so that they are no longer hard-coded. At the same time,
timeouts are greatly raised to reduce the number of expirations that
happen because the client is too slow to refresh an active allocation.
The client is modified to attempt a refresh earlier into the
server-specified duration, but given the raised timeouts its minimum
refresh duration is raised from 1s to 5s.
Jira: INFRA-607
=> flextape: Raise and parameterize timeouts

bazel/appengine/config.bzl
Background:
push target for web targets works locally, but fails from cloudbuild.
For some reason, it seems like it is performing stricter checks when
the push is from cloudbuild? could be I'm using an older version of
the dev container (and gcloud tools).
Either way, the 'app_engine_apis' parameter in app.yaml is only
supported by a subset of the appengine environments, not the one
used by those rules. The parameter has to go.
Tested: modified BUILD.bazel file in our docs directory to override the
defaults, see PR4504, and it works.
See also the https://cloud.google.com/appengine/docs/standard/python/config/appref,
that does not have the parameter.
=> bazel/appengine: remove incompatible default parameter.

bazel/linux/defs.bzl
When debugging, it is sometimes more convenient if compile optimizations
are disabled. It is not possible to compile kernel modules with -O0 but
-O1 seems to work. Also, disable function inlining.
Tested:
for i in "" "-c fastbuild" "-c opt" "-c dbg"; do
echo -ne "$i: "
bazel build driver/ib/enf_ib-swtest $i 2> /dev/null
nm bazel-bin/driver/ib/enf-ubuntu-impish-minimal/enf_ib-swtest.ko | grep ' [Tt] ' | wc -l
done
: 229
-c fastbuild: 229
-c opt: 229
-c dbg: 243
=> linux/defs.bzl: compile device drivers with -O1 for debug builds

lib/khttp/server.go
Previous change to normalize port and address parsing accidentally
made specifying both http and https mandatory. This PR fixes it.
=> lib/khttp/server: bugfix - don't mark ports mandatory.

lib/config/directory/BUILD.bazel, lib/karchive/BUILD.bazel, lib/kcerts/BUILD.bazel
This change marks tests that don't run successfully under Cloud Build
`no-cloudbuild`, so that they do not run in presubmits or postsubmits.
Future PRs may fix these tests to work with Cloud Build.
Jira: INFRA-927
=> Disable presubmits/postsubmits for broken tests

scripts/gee
gee: require (most) gee commands run inside a gee repo
Motivation: shaving one of the sharp edges off of gee.
If users who have their own git repository try to run "gee" in that git
repository, instead of the "gee" repository, some of gee's design assumptions
may be violated and strange things might happen.  One user already got into
trouble in this manner.
Rather than test each gee command in every possible context, I've added
a check to validate that (most) gee commands can only be run from within
a gee repository.  Otherwise, the user will be given an informative
message indicating that they should either switch to a gee repo, or
create a gee repo if such a repo does not exist.
Tested:
* Ran "gee update" from a variety of directories, gee update only
runs from the gee repo directories. …
=> gee: require (most) gee commands run inside a gee repo

kbuild/utils/README.md, kbuild/utils/buildroot/run_kunit_tests.sh
Background:
I'm changing how uml tests are run. Specifically, in the next PR
bazel will generate a "runtime package" - a directory with data and
an init.sh script to "run the test" (or really, anything) in a
generic VM (or UML).
In this PR:
- update run_kunit_tests.sh so that it checks for the presence
of an init.sh script in the mounted directory, and if it is there,
runs it.
- while at it, various improvements, specifically:
- make the script `shellcheck` clean. This required a lot of
style improvements: error handling, " in places we did not
have before, etc.
- exit calls required invoking poweroff reliably, so moved
to a trap event, and moved to `poweroff -f`, as to avoid
going through systemd/init (faster, more reliable)
- removed some obsolete / incorrect comments, added some
new …
=> kbuild/utils/buildroot: add init.sh support to run_kunit_tests.sh.

astore/server/BUILD.bazel, bazel/dependencies/BUILD.bats.bazel, bazel/shellutils.bzl, bazel/ui/react.bzl, bazel/utils/merge_kwargs_test.bzl, bestie/proto/BUILD.bazel
PR containing the files modified by:
bazel run //:buildifier
no other change, only style fixes. bazel/linux was excluded from
the PR due to work dedicated to it coming in dedicated PRs.
=> repo wide: run buildifier through the repository.

bazel/linux/defs.bzl
Use -fno-inline as it prevents inlining for more functions than the
previous setting. The number of functions in enf_ib-swtest.ko increase
from 228 in the optimized build to 502 in the debug build.
=> linux/defs.bzl: fix no inlining for debug kernel module builds

scripts/gee, scripts/gee.changelog.md
gee cleanup: fix handling of pr_NNN branches.
pr_NNN branches are created by the `gee pr_checkout` command.  Unlike regular
branches, their parent is the upstream branch referring to the PR that was
checked out.  However, this causes naive diffing against parent branch
to fail because this is illegal syntax for git:
git diff upstream/refs/pull/4628/head...HEAD
`gee diff` already contains the correct workaround for this issue.  This PR
applies the same workaround to `gee cleanup`.
Tested: Ran `gee cleanup` in a branch with a pr_NNNN branch.
=> gee cleanup: fix handling of pr_NNN branches.

scripts/gee
gee version: tell user if a new version is available.
The `gee version` command will now check for a newer version of gee on astore,
and tell the user how to upgrade if a newer version is available.
Tested: Manually ran ./gee version to view message.
=> gee version: tell user if a new version is available.

scripts/gee
gee: disable autostash
Users are having trouble with autostash.  I think it's a better user experience
to simply disable autostash, and require users to commit their work before
rebasing (easier to recover when something goes awry).
Tested: Ran the `up`, `rup`, `update_all` commands in branches both
with and without uncommitted changes.
=> gee: disable autostash

bazel/linux/defs.bzl, bazel/linux/providers.bzl, bazel/linux/uml.bzl
Background:
defs.bzl has grown too large. Upcoming changes are adding support
for kvm, which will make it even larger.
In this PR:
- create a providers.bzl - must to avoid circular dependencies.
- moved uml specific code into dedicated file - uml.bzl.
This change is a noop: no code has been harmed in the process.
Tested:
bazel test with --override_repository in internal shows no
regression in the tests.
=> bazel/linux: split defs.bzl in multiple files.

tools/bzldoc/BUILD.bazel, tools/codegen/BUILD.bazel, tools/codegen/tests/BUILD.bazel
This change runs `bazel run //:gazelle` to update BUILD files where
necessary, minimizing diffs in future changes.
=> gazelle: Run on entire repo

proxy/ptunnel/commands/BUILD.bazel, proxy/ptunnel/commands/ssh.go, proxy/ptunnel/commands/ssh_test.go
This change adds a `--proxy-map` argument to `enkit ssh`, allowing one
to map bits of a SSH target address to its corresponding proxy. This
will allow us to configure e.g.:
```
--proxy-map=.foo=https://foo.example.com,.bar=https://bar.example.com
```
in the enkit kconfig, so that a bare `enkit ssh user@machine-1.bar` will
resolve to the (potentially non-default) proxy https://bar.example.com.
This is done by matching all of the non-flag SSH args against all
entries in `--proxy-map` via substring lookup until a match is found; if
no match is found, the proxy named by `--proxy` is used as a fallback.
This logic is likely to work most of the time but fall on its face for
unusual invocations of `enkit ssh`, so proxy decisions are logged at at
least the INFO level.
Tested:
* Added unit tests
* …
=> enkit ssh: Add --proxy-map arg

tools/bzldoc/BUILD.bazel
bzldoc.bzl: added missing visibility attribute.
I think this is why I'm having difficulty loading this bzl file from internal.
Tested:
=> bzldoc.bzl: added missing visibility attribute.

bazel/init/stage_1.bzl
This change fixes a few minor issues to unblock builds in internal:
* Patch labels must be qualified by the repository name or they get
resolved relative to the calling workspace
* `com_google_protobuf` must be overridden and updated to 3.20.1 to get
around https://github.com/protocolbuffers/protobuf/issues/9688
Tested: Built internal using `--override_repository` pointing to enkit;
`//systest/...` builds. It's possible that other builds still fail; TBD
after this is merged.
Jira: INFRA-1038
=> WORKSPACE init: Fixes for internal

bazel/init/stage_1.bzl, proxy/nss/BUILD.bazel, proxy/nss/confparse/BUILD.bazel
The gtest name is deprecated in favor of "com_google_googletest"; this change migrates enkit to the new name, so that downstream repositories don't need to import the latter themselves.
Jira: INFRA-1038
=> WORKSPACE: Rename gtest to com_google_googletest

scripts/gee
gee pr_submit: check PR status
Previously, gee would emit cryptic but harmless error messages if `gee pr_submit`
was run in a branch where the PR has already been submitted.  This PR adds a few
checks to provide literate error messages to the user in this and similar scenario.
Tested:
* Attempted to run `gee pr_submit` in a branch without a PR.
* Attempted to run `gee pr_submit` in a branch associated with a merged PR.
=> gee pr_submit: check PR status

scripts/gee
gee pr_submit: disable post-submit diff check
This check was low value (gh pr submit is reliable), and would occasionally
report spurious failures (scenarios where two PRs were submitted at around
the same time, and changed the same file, but neither change conflicted with
the other).  To avoid alarming the user with a useless error, this check
is now disabled.
Tested: Will use gee pr_submit to submit this PR.
=> gee pr_submit: disable post-submit diff check

tools/codegen/codegen.bzl, tools/codegen/tests/BUILD.bazel, tools/codegen/tests/d2-test.expected, tools/codegen/tests/d2.pkgdef
codegen: add support for "pkgdef" extension as well.
This is necessary to support upcoming https://github.com/enfabrica/internal/pull/4843
Tested: Existing tests pass.  Tested in PR 4843.
=> codegen: add support for "pkgdef" extension as well.

scripts/gee, scripts/gee.changelog.md, scripts/gee.md
This PR addresses two annoyance-level issues:
1. The PR description template was unnecessarily verbose.  The new version is
shorter and thus easier to edit.
2. Instead of asking the user if they want to edit the PR description, we just
ask them how (previously, if they decided not to edit the PR description,
they would win the booby prize of pr_make erroring out).  Additionally, if
the user specifies the EDITOR environment variable, just use that editor.
3. The common use chase for `pr_submit` is "wait for all presubmits to pass
and then submit".  Previously, after all presubmits passed, we would wait
for user confirmation before submitting.  This PR removes that extra
confirmation, so that pr_submit can be more "fire and forget" after
waiting for presubmits to succeed.
4. Fixed malformed …
=> gee: streamline pr_make/pr_submit

bazel/init/stage_1.bzl
This update to `rules_docker` fixes an issue in internal where a race in
the build causes a build error while building certain images.
Tested: Built internal with enkit overridden with this change:
http://buddy.bazel.corp.enfabrica.net/invocation/9eb0ec3c-19f0-490b-91e5-43cb33d8213e
Jira: INFRA-1038
=> rules_docker: Update to v0.24.0

bazel/linux/defs.bzl, bazel/linux/qemu.bzl, bazel/linux/runner.bzl, bazel/linux/templates/check_kunit.template.sh, bazel/linux/templates/init.template.sh, bazel/linux/templates/runner.template.sh, bazel/linux/uml.bzl, bazel/utils/exec_test.bzl
Background:
So far, all the uml_|qemu_ virtualization rules were for testing
only. Now we want to use them just to run an emulator.
This PR changes the rules from "test = True" to "executable = True",
with all that it implies.
Specifically:
- refactor the .sh scripts - they can no longer rely on TEST_
environment variables being set.
- introduce an exec_test.bzl utility - that can turn any executable
rule into a test rule.
- use said rule in existing definitions so to maintain backward
compatibility with the existing ruleset.
- have the shell scripts in the rules be more useful. Specifically:
- it is now possible to override emulator/kernel/rootfs parameters
directly from the command line.
- paths and runtime info is clearly displayed on the screen, removing
sandboxing parameters, so it's …
=> bazel/linux: turn {uml|qemu} test rules into runnable rules.

bazel/linux/bundles.bzl, bazel/linux/defs.bzl, bazel/linux/providers.bzl, bazel/linux/qemu.bzl, bazel/linux/runner.bzl, bazel/linux/uml.bzl, bazel/linux/utils.bzl
Background:
RuntimeInfo is not really representative of what the provider does.
The _dir rule... is kunit specific.
defs.bzl is too big.
- move the kunit dir rule into bundles.bzl, rename it appropriately.
- rename the provider from RuntimePackageInfo to RuntimeBundleInfo.
- to avoid circular dependencies between files, create a utils.bzl
and move a few functions there. This is a bit unfortunate, but
as we break down defs.bzl further, it'll improve.
=> bazel/linux: move and rename dir bundle.

bazel/astore/defs.bzl
A repository rule's implementation only gets the ctx object as a
parameter, and this commit fixes that with a wrapper function. In a
perfect world, we would pass any attribute needed in via ctx.attr, but
like noted in the inline comment, kernel_tree_version uses "sha256" in
place of "digest", and changing it now would break external consumers of
the rule and a rolling update will not be feasible. Longer-term, this
wrapper should be replaced with a dict of attributes for the various
consumers of the common function.
The commit also introduces a strip_prefix attribute for the general
astore_package rule.
Tested manually with both astore_package consumers (which was missed
with cdf318cf0) and kernel_tree_version consumers (with and without an
authenticated download).
Signed-off-by: Raghu …
=> astore: Fix bug with astore_download_and_extract implementation

kbuild/v2/scripts/lib.sh
Since INFRA-1047 is fixed we can enable tagging the kernel artifacts
in astore.  Each kernel artifact now has a "kernel=<kernel_version>"
tag.
=> kbuild: enable tagging of kernel artifacts in astore

tools/bzldoc/md.template, tools/bzldoc/testdata/codegen.bzl, tools/bzldoc/testdata/codegen.md, tools/bzldoc/testdata/codegen.yaml
bzldoc: handle missing attrs
One of our bzl files defines a rule with no attrs attribute, for some reason,
which blows up our template. This PR adds a conditional to handle this
exceptional condition.
Tested:
Added a rule to testdata/codegen.bzl to reproduce the problem.
Watched the build fail.
Modified the template to resolve the issue.
Watched the build succeed.
=> bzldoc: handle missing attrs

kbuild/v2/README.adoc, kbuild/v2/scripts/build-uml.sh, kbuild/v2/scripts/upload-deb.sh, kbuild/v2/scripts/upload-uml.sh
This patch combines the vmlinuz kernel image and the modules.tar.gz
artifacts into a single artifact, called `vmlinuz-modules.tar.gz`.
The format of the tarball is:
``` text
boot/vmlinuz-<kernel-version>
lib/modules/<kernel-version>/...
```
This patch also removes the `modules.tar.gz` for the UML variant as it
is not needed.
=> kbuild: combine vmlinuz and modules.tar.gz into a single artifact

bazel/astore/defs.bzl
6c19853 introduced a build attribute to the astore_download_and_extract
repository rule. The implementation function is also used by other rules
that do not have this attribute in the context. The commit checks for
availabilty before using it.
--- 
Tested with both repo rules that use this function.
=> astore: Check for build attribute before using it

astore/client/commands/BUILD.bazel, astore/client/commands/commands.go, astore/client/commands/formatter.go, astore/client/commands/formatter_test.go, go.mod, go.sum
This patch adds two command line options to the `enkit astore`
commands for formatting the output of artifact meta-data.
```
-m, --meta-file string       Meta-data output file (default "-")
-f, --meta-format string     Meta-data output format. One of [text, json] (default "text")
```
These options can be used with any astore command that outputs
artifact meta data, including:
- astore ls
- astore note
- astore download
- astore tag
- astore public
- astore upload
Running the `enkit astore ls` command with JSON output to stdout,
piped through `jq .`, looks like this:
```json
$ bazel run //enkit:enkit -- astore ls kernel/enf/impish-19.19/minimal/build-headers.tar.gz -l -f json | jq .
[ …
```
=> enkit-astore: add meta-data output command line flags

bazel/linux/bundles.bzl
modprobe does not work correctly without a proper /sys: if a module is
already loaded on the host, then modprobe will erroneously see it loaded
in the guest as well because it accesses the /sys of the host.
=> bazel/linux: fix for modprobe

bazel/linux/bundles.bzl, bazel/linux/templates/kunit.template.sh
Do not reuse the init.template.sh for running kunit tests. This template
powers off the VM on exit and kunit tests are not supposed to do the
same.
=> bazel/linux: create separate template for kunit tests

kbuild/v2/README.adoc, kbuild/v2/kpub-astore, kbuild/v2/scripts/archive-bazel-uml.sh, kbuild/v2/scripts/gen-bazel-meta.sh, kbuild/v2/scripts/lib.sh, kbuild/v2/scripts/upload-deb.sh, kbuild/v2/scripts/upload-uml.sh
This patch updates the kbuild script to generate a file suitable for
commiting to the internal repo in
<internal-repo>/bazel/kernel.version.bzl.
This file contains all the info necessary for bazel to download and
verify the kernel artifacts from astore.
Partially-Fixes: SF-58
=> kbuild: generate artifact meta-data file suitable for bazel

bazel/linux/providers.bzl, bazel/linux/runner.bzl
Problem:
Would like argv supplied to be able to reference arbitrary environment
variables set by the script, or use things like $(realpath ...).
Today, however, this is not possible: argv is shell escaped, to
prevent any sort of quoting hell.
In this PR:
- stop escaping argv, allowing arbitrary shell sequences to be used
(on purpose, this is a goal).
- turn argv, from an array, into a single string. No point in maintaining
separation without escaping, and mimics the semantics of other APIs,
where arrays are generally considered safe (as passed as argv to
an execve equivalent kind of function) while a single string is
considered unsafe (as subject to space field separation, and
often passed as the argument to bash -c).
- change the contract/documentation of the provider.
=> bazel/linux: don't escape argv.

bazel/linux/bundles.bzl, bazel/linux/providers.bzl, bazel/linux/runner.bzl
Background:
The runner() in runner.bzl supports preparing the machin in
arbitrary ways, running tests in the VM, and checking the
machine in arbitrary ways.
But this feature was not exposed except for custom rules.
In this PR:
- introduced a generic vm_bundle that allows to create
a bundle with a prepare/check/run step without having
to write any bazel code.
=> bazel/linux: generic rule to implement pre- and post- checks.

bazel/linux/templates/runner.template.sh
This is a tiny change documenting `-s` in the help screen of
the runner script.
=> bazel/linux: document the most important options of all.

scripts/gee, scripts/gee.changelog.md
bazel creates a unique cache directory for each worktree directory.  These
cache directories are often quite large and exhaust disk space on shared
machines.  It was suggested that it might save disk space to delete this cache
whenever a worktree/branch is deleted.  This PR implements this suggestion.
Tested: Ran `gee rmbr` on an old branch, verified the right cache directory was deleted.
```
$ ls -ld bazel-out
lrwxrwxrwx 1 jonathan kvmext 105 Apr 11 14:56 bazel-out -> /home/jonathan/.cache/bazel/_bazel_jonathan/a23fa97ce46f53d20a55a7f9115bd9da/execroot/enfabrica/bazel-out
$ du -sh ~/.cache/bazel/_bazel_jonathan/a23fa97ce46f53d20a55a7f9115bd9da/
674M    /home/jonathan/.cache/bazel/_bazel_jonathan/a23fa97ce46f53d20a55a7f9115bd9da/
$ gcd master
$ ~/gee/enkit/gee_rm_bazel_cache/scripts/gee …
```
=> gee rmbr: also delete bazel cache

scripts/gee, scripts/gee.changelog.md, scripts/gee.md
Bazel cache dirs are creating problems on shared machines.  This gee command identifies
any bazel cache dirs not associated with any worktree that gee knows about, and offers
to delete it.
Tested: (From when this command was named "gc" instead of "bazelgc")
```
$ ./scripts/gee gc
WARNING: About to delete the following directories:
WARNING: /home/jonathan/.cache/bazel/_bazel_jonathan/093e814ab60e138d58ac3228f62dc8db
WARNING: /home/jonathan/.cache/bazel/_bazel_jonathan/77f453935039b33b590f1a3a8ef26bbe
WARNING: /home/jonathan/.cache/bazel/_bazel_jonathan/8942e9b61ff399dfb2c53ea1322c2ddf
WARNING: /home/jonathan/.cache/bazel/_bazel_jonathan/b20aeaa720f6fd448163b046448d1337
WARNING: /home/jonathan/.cache/bazel/_bazel_jonathan/bcf131ed200fcd952f4340e2b2e8d60d
Proceed? (y/N)  n
Nothing was …
```
=> gee: add "bazelgc" command to clean up bazel cache dirs

scripts/gee, scripts/gee.changelog.md, scripts/gee.md
While helping out a gee user, I found myself again wishing for better
diagnostics for gee.  This PR adds two diagnostics:
1. It adds a `~/gee.log` file that gets appended to for every command,
and contains a subset of log messages.
2. It adds a "gee diagnose" command, that gathers a bunch of diagnostic
information into a `~/gee.diagnostic.txt` file, suitable for submission
as a gist or email.
Tested: Invoked `gee diagnose` in a healthy gee repository.  Ran a variety
of gee commands and noticed ~/gee.log growing.
=> gee: add diagnostics

bazel/linux/defs.bzl, bazel/linux/repository.bzl
This is a noop: just moves the repository rules in defs.bzl
into repository.bzl. Did I mention defs.bzl is too big?
This is helps with SF-155.
=> bazel/linux: minor cleanup in preparation for next PR.

bazel/linux/bundles.bzl
When running in a sandbox, mount might fail with the message "mount:
only root can use "--types" option". Handle this failure and print a
warning to the user.
=> bazel/linux: gracefully handle mount failures

lib/kbuildbarn/exec/templates/config.jsonnet
This change updates the bb_clientd configuration so it is compatible
with a newer version of bb_clientd.
Tested:
* Put new version of `bb_clientd` on `$PATH`
* `bazel run //enkit -- outputs mount -i 7edcf668-d0a1-4f3f-8f63-19ae7d5b8e4a` successfully mounts outputs
Jira: INFRA-886
=> enkit outputs: Update bb_clientd config

bazel/linux/qemu.bzl, bazel/linux/templates/runner.template.sh, bazel/linux/uml.bzl
Rename the previous interactive mode to single-user mode, which
effectively does init=/bin/sh and is useful for debugging.
The new interactive mode is enabled only programmatically with:
vm_bundle(
name = "interactive",
prepare_cmds = [
"INTERACTIVE=1",
],
)
The init script is executed and is expected to invoke the shell.
=> bazel/linux: introduce interactive mode

bazel/linux/defs.bzl
Store the name of the kernel_module rule as part of the generated
module's path to allow compiling the same module with different
parameters.
Example:
Before: bazel-bin/.../$KERNEL/$ARCH/$MODULE.ko
After:  bazel-bin/.../$KERNEL/$NAME/$ARCH/$MODULE.ko
=> bazel/linux: handle multiple module build types

bestie/server/main.go, bestie/server/service.go, bestie/server/test_result.go, bestie/server/xml_result.go
The BES Endpoint will not attempt to read and process any output
file whose size exceeds 20 MB. This is to prevent out-of-memory
conditions being experienced several times per day in the production
cluster. This does not impact the running 'bazel test' job, but
will preclude updating the BigQuery database with any metrics
contained in the unprocessed files.
Note that the built in default of 20 MB for the file size limit
can be overridden using the --max_file_size command line
parameter.
Tested: Ran a local instance of the bestie server along with
a bazel test //systest/src/demo:test_sample_metrics that sent
its BES events to localhost:6433. Observed the desired behavior
when files exceeded the limit.
Jira: INFRA-1088
=> INFRA-1088: bestie: enforce 20 MB output file size limit

scripts/gee
Previously: the set of "pending reviews" shown by "gee lspr" was
missing many reviews shown by the web interface.  It turns out
that this was because, by default, "gh pr list" only looks 30
records deep into the set of pending PRs, missing PRs older than
a week or so.
This PR corrects that issue by expanding the data horizon.
Additionally, "lspr" now also reports which PRs are assigned to us.
Tested: Manually ran gee lspr in a few clients.
=> gee lspr: fix incomplete reviews list

scripts/gee, scripts/gee.md
This PR undoes a bad decision made months ago.  When the user asks for a diff,
they are almost always expecting "changes since this branch diverged from its
parent branch" (the 3-dot diff), not "show all differences between the
branches" (the 2-dot diff).
Tested: Ran "gee diff" manually in a few branches.
=> gee diff: show changes since branches diverged

lib/bazel/workspace.go
This change ensures that underlying Bazel commands all run with the
expected environment, which may be setting `BAZEL_PROFILE` to be picked
up by our wrapper in `tools/bazel`.
Jira: INFRA-1120
=> `enkit bazel`: Propagate environment to all bazel commands

scripts/gee, scripts/gee.changelog.md, scripts/gee.md
The problem: "gee rmbr" was failing-and-exiting for branches where the
bazel-out link exists, but points to a bazel cache directory that is no longer
there.  This PR makes gee tolerant of this error case.
Tested: Used to remove a branch with a broken link.
```
$ ~/gee/enkit/fix_rmbr/scripts/gee rmbr pr_4628
####################
####################
WARNING: Branch "pr_4628" is 2 commit(s) ahead of master.
Are you sure you want to force-remove branch pr_4628? (y/N) y
As you wish.
CMD: /usr/bin/git worktree remove --force pr_4628
CMD: /usr/bin/git branch -D pr_4628
Deleted branch pr_4628 (was 565db1b86).
CMD: /usr/bin/git push --quiet origin --delete pr_4628
Deleted pr_4628.  To undo: gee make_branch pr_4628 565db1b86
```
=> gee rmbr: handle broken bazel-out links

kbuild/v2/README.adoc, kbuild/v2/scripts/build-uml.sh, kbuild/v2/scripts/gen-bazel-meta.sh, kbuild/v2/scripts/lib.sh, kbuild/v2/scripts/upload-uml.sh
This PR creates a vmlinuz-modules.tar.gz artifact for the UML
testing kernel that matches the same format used by the "generic" and
"minimal" kernel flavours.
Fixes: SF-186
=> kbuild: create UML vmlinuz-modules.tar.gz artifact

bazel/linux/defs.bzl, bazel/linux/test.bzl
- bazel/linux: remove compatibility rules.
- bazel/linux: rename kernel_test to kunit_test, move in test.bzl file.
- bazel/linux: add a qemu_test target.
See log for individual commits. This should help with SF-162 ans SF-150.
=> bazel/linux: test cleanups, and qemu_test target

scripts/gee
If a user is having trouble connecting over ssh to github, the diagnostics
file now contains the information I should need to root cause the issue.
Tested: ran `gee diagnose`, inspected result.
=> gee diagnose: add ssh diagnostics

bazel/init/stage_1.bzl, bazel/init/stage_2.bzl, bazel/meson/meson.BUILD.bazel, bazel/meson/meson.bzl, bazel/meson/test/BUILD.bazel, bazel/meson/test/hello.c, bazel/meson/test/meson.build
Add Meson as a cc_external_rule. Can be used in a similar way to cmake
from rules_foreign_cc.
=> meson: add Bazel support for building with Meson

bazel/meson/meson.bzl
Fixes the following error:
"Error in fail: In order to use find_cpp_toolchain, you must include the
'@bazel_tools//tools/cpp:toolchain_type' in the toolchains argument to
your rule."
=> bazel/meson: fix missing toolchain argument

bazel/meson/meson.BUILD.bazel, bazel/meson/meson.bzl
The meson filegroup was defined incorrectly leading to this error:
ModuleNotFoundError: No module named 'mesonbuild'
Jira: https://enfabrica.atlassian.net/browse/SF-202
=> bazel/meson: fix missing Meson python files

bazel/astore/defs.bzl
This change raises the timeout for calculating the sha256 of items
downloaded from enkit. This timeout is currently causing false failures
in presubmits - while an individual sha256 should be relatively fast
compared to the old timeout, it is likely that the Cloud Build machine
is downloading/unpacking other items concurrently and is therefore
slower than expected.
Jira: INFRA-1179
=> astore_package: Raise sha256sum timeout

proxy/nasshp/BUILD.bazel, proxy/nasshp/counters.go, proxy/nasshp/nassh.go, proxy/nasshp/nassh_test.go, proxy/nasshp/resolver.go, proxy/ptunnel/commands/tunnel.go, proxy/ptunnel/tunnel.go
It's useful to create a mechanism by which the proxy can deduce the
correct target port for `enkit tunnel` based on the host - the first
usecase is by doing SRV record lookup for Consul DNS names.
This change modifies `enkit tunnel` to omit the port arg to
enproxy when no port is provided on the commandline. Enproxy interprets
an absence of a port as requesting port resolution.
In particular:
* `enkit tunnel` defaults to a "0" port when port is not provided on the commandline
* `enkit tunnel` omits the port arg when port is 0 when contacting enproxy
* enproxy treats no port as requiring a port resolution via SRV record, failing if the record lookup fails
* Resolution happens via an injected Resolver; a MultiResolver allows for chaining of multiple Resolvers
* Due to moving out host/port …
=> enproxy: Use negative port to signal auto port detection

bazel/linux/qemu.bzl, bazel/linux/templates/init-qemu.template.sh
Map the $OUTPUT_DIR directory from the host to the device
/dev/output_dir in the guest.
=> bazel/linux: expose /dev/output_dir

bazel/linux/templates/init-qemu.template.sh, bazel/linux/templates/init-uml.template.sh
We support propagating the exit status only when using QEMU. By mistake,
we updated the wrong init.template.sh.
Fixes: 65d5933499d1 ("bazel/linux: propagate the exit status outside the emulator")
=> bazel/linux: fix propagation of exit status

bazel/linux/templates/runner.template.sh, bazel/linux/test.bzl
The following output is printed inside the emulator:
```
//tests:test1                                                            PASSED in 0.2s
//tests:test2                                                            FAILED in 0.3s
//tests:test3                                                            PASSED in 0.4s
==================== Test output for //tests:test2:
test2 script output
================================================================================
Executed 3 test(s): 2 test(s) pass(es) and 1 fail(s).
```
Jira: https://enfabrica.atlassian.net/browse/SF-147
=> bazel/linux: add support for running multiple tests in an emulator

bazel/linux/templates/runner.template.sh, bazel/utils/files.bzl
Some bash scripts were failing silently due to missing pipefail.
=> bazel: add missing pipefail to bash scripts

bazel/linux/qemu.bzl
QEMU will try to use KVM and if that fails will fallback to TCG.
=> bazel/linux: fallback from KVM to TCG when using QEMU

kbuild/v2/template/install-uml-bazel.sh
The UML kernel build-header install script was not installing things
correctly.  The underlying bazel kernel_tree_version() rule that
unpacks and installs the build headers creates a filegroup() using:
srcs = glob(["lib", "usr", "install"], allow_empty = True, exclude_directories = 0)
The previous installer was not using one these directories at install
time, hence the files were not available to UML kernel module builds.
This patch updates the installer to use the "install" directory.
Fixes: dbf665348d4f ("kbuild/v2: Update scripts to build/publish UML kernel artifacts (#577)")
=> kbuild:uml: update build-header installer to match build rules

kbuild/v2/README.adoc
This patch fixes some of the literal code blocks in the README that
were not rendering correctly.
=> kbuild:README: update literal blocks

kbuild/v2/scripts/gen-bazel-meta.sh
This patch updates the scripts to add a stanza to the
bazel/kernel.version.bzl for each kernel flavour, describing the
tarball of kernel .deb packages.
The new stanzas have the label:  KERNEL_DEB_ENF_UBUNTU_IMPISH_<FLAVOUR>
=> kbuild: Add deb-artifacts.tar.gz astore meta data to bazel/kernel.version.bzl

bazel/linux/bundles.bzl, bazel/linux/defs.bzl, bazel/linux/test.bzl
```
kunit: do mot mount sysfs on /sys automatically
This patch removes the automatic mount of sysfs on /sys for a couple
of reasons:
1. the kunit framework now uses 'insmod' instead of 'modprobe', so the
original reason for mounting sysfs no longer exists.
2. kunit_test() can be run with a custom runner that can handle any
needed "pre-test" steps, like mounting sysfs or procfs, etc.
For the case of using a QEMU runner, we will use a common system setup
set of run commands that already handles mounting various kernel file
systems.
Relates-to: MCU-85
```
```
kunit: append the kunit command steps to the runner steps
This patch swaps the order of the 'runner_cfg' and 'cfg' parameters in
the mcreate_rule() call for kunit tests.  The net effect is the
commands from 'cfg' are appended to the …
```
=> kunit: updates for kunit inside of QEMU

astore/BUILD.bazel, astore/e2e_test.go, astore/server_test.go
This change fixes the broken target `//astore:e2e_test`, which could
never build in its current BUILD configuration.
This test still doesn't run in the current dev container, but tagging it
as such will at least allow our postsubmits to pass.
Imports are organized in the code, and proto imports are modified to
follow the `?pb` naming convention.
Tested: `bazel build //astore:go_default_test` now succeeds
Jira: INFRA-1233
=> astore e2e_test: Fix build, exclude from postsubmits

infra/postsubmit/proto/postsubmit.proto
This change adds a "disable" trigger that creates the build but prevents
it from ever running. This can be used to disable builds on a temporary
basis.
Jira: INFRA-1232
=> postsubmits: Add method of disabling build in config

infra/postsubmit/proto/postsubmit.proto
This change adds a configuration setting to postsubmits that will allow
users to configure which buildbarn instance builds should go to.
This will be used in the short-term to migrate builds to buildbarn on
gcp01 while leaving the majority of builds running on buildbarn in MTV.
Jira: INFRA-1284
=> postsubmit: Add ability to configure buildbarn instance

bazel/utils/diff_test.bzl
This propagates the behavior of diff_test to zipdiff_test: if --update_goldens
is specified, zipdiff_test script no longer terminates with a non-zero exit
code.  Important for users like Gavin who want to use multirun to group
diff_tests together.
Tested: ?
=> zipdiff_test: don't fail if --update_goldens is set

bazel/utils/BUILD.bazel, bazel/utils/echo-argv_test.sh, bazel/utils/echo-argv_test_check.sh, bazel/utils/exec_test.bzl
Background:
I noticed qemu_test rules failing when manually specifying some command
line parameters. Turns out the problem was in exec_test, that did not
expand a bash array correctly.
In this PR:
- fix the shell argument expansion.
- add a tiny test to verify that exec_test works as expected.
fool me once, yadda yadda.
Also, trying to add examples for bazel rules tests, and examples of
sh_binary() just invoking and using other targets (hint: it's easy!).
=> enkit/bazel/utils: fix error in exec_test.

scripts/README.md, scripts/gee, scripts/gee.changelog.md, scripts/gee.md
As a convenience option, I added a "-m" option to the gcd command, that
causes gcd to create a new branch that is a child of the master branch.
The "-b" option functionality (creation of a new branch that is a child
of the current branch) remains unchanged.
I also updated "gee rmbr" to be able to operate on a list of branches instead
of a single branch, and removed the "booby trap" where running "gee rmbr"
without any options removes the current branch.
This PR also improves gee's documentation a little bit.
* The "-m" option creates a new branch that is a branch of master
Tested: use "gcd -b" and "gcd -m" to create new branches, and used
"gee getparent" to confirm that the corrent branch lineage was created.
I then used "gee rmbr" to remove all of the newly created test branches
using a …
=> gee: add -m option to gcd

scripts/gee
Added "git worktree prune" to "gee repair" flow.  This removes worktree
entries the have been abandoned by their associated branches, perhaps
by the branch being deleted without removing the worktree first.
Tested: gee repair successfully invokes worktree prune.
=> gee repair: prune worktree

enkit/outputs/commands.go, proxy/ptunnel/exec/exec.go
Since buildbarn has moved to a different realm, `enkit outputs` needs a
flag to control which proxy to tunnel through when tunneling is
necessary.
This change adds said flag and makes sure it is propagated to the tunnel
creation command.
Tested:
* Ran: https://keep.google.com/u/0/#NOTE/1bz2F5i3Hy56Z_rfunezp_hhwnatWvoe2uPUN1MEj-yxfPko2ANpz-xkASPtjUQ
and was able to read all outputs
Jira: INFRA-1269
=> enkit outputs: Add proxy flag

bazel/linux/templates/init-qemu.template.sh, bazel/linux/test.bzl
Replace in the guest the hardcoded path /tmp/output_dir with the
environment variable OUTPUT_DIR.
=> bazel/linux: export the env. variable OUTPUT_DIR in the guest

enkit/cmd/BUILD.bazel, enkit/cmd/command.go, enkit/version/BUILD.bazel, enkit/version/version.go, lib/stamp/BUILD.bazel, lib/stamp/stamp.go
This change adds a `version` subcommand to enkit that prints linkstamped
info so that we can more easily debug issues that arise from an
out-of-date enkit version.
Tested: `bazel run //enkit --stamp -- version`
=> enkit: Add version subcommand

bazel/utils/remote.bzl, bazel/utils/remote/BUILD.bazel, bazel/utils/remote/noop.sh, bazel/utils/remote/runner.template.sh
See the top of remote.bzl file for an explanation of the ruleset added.
Why? Typical development cycle has developers build scripts or tests
locally, and wanting to try them on a remote machine. I expect we'll have
something better and more dynamic with machine allocations in the future,
but this is a starting point for manual testing.
SF-218 for background as well.
This is a first step: qemu run rules will be modified to better play
with the remote rules, and allow baremetal run, and we'll need an
official wrapper to prepare the environment on the remote machine.
=> bazel/utils: initial set of rules to run an arbitrary target on a remote machine.

bazel/utils/BUILD.bazel, bazel/utils/exec_test.bzl, bazel/utils/failing-script_test.sh
In this PR:
- add a `must_fail` boolean - when set to true, the test
succeeds if the execed binary fails. When left to the false
default, the binary must succeed.
Purposedly avoided naming this 'expect_failure', to avoid
conflict with still undocumented bazel feature.
- added a corresponding test.
Tested:
exec_test happens to have unit tests, old tests are passing,
newly added one is also passing. Change is minimal.
=> bazel/utils: enhance exec_test to expect failing binaries.

bazel/linux/bundles.bzl, bazel/linux/providers.bzl, bazel/linux/runner.bzl, bazel/linux/templates/runner.template.sh, bazel/linux/test.bzl
Clean up operations execute outside of the emulator after the execution
of the emulator in reverse order.
Jira: https://enfabrica.atlassian.net/browse/SF-246
=> bazel/linux: add cleanup attribute to vm_bundle

bazel/linux/qemu.bzl, bazel/linux/templates/runner.template.sh
Prefix all arguments that are handled by the runner itself with
--runner-. The rest of the arguments are stored in an array ARGS and are
available to a potential QEMU wrapper script.
Jira: https://enfabrica.atlassian.net/browse/SF-194
=> bazel/linux: pass command line arguments to QEMU wrapper scripts

bazel/utils/cc_filter.bzl
This rule filters the outputs of a C rule. It can be used to limit the
number of dependent libraries of a cc_binary.
=> bazel/utils: add cc_filter rule

bazel/meson/meson.bzl, bazel/meson/test/BUILD.bazel, bazel/meson/test/meson.build
Set the install prefix to be a subdirectory of $BUILD_TMPDIR because
rules_foreign_cc/framework.bzl replaces in the generated files any path
that is under $BUILD_TMPDIR with the appropriate placeholder (such as
$EXT_BUILD_DEPS).
=> bazel/meson: fix wrong paths

astore/client/commands/commands.go
* Fix astore upload help typo: "Allow a asingle element path" -> "Allow a single element path"
* Clean up whitespace in astore/client/commands/commands.go
=> astore client: Fix typo in help string

bazel/utils/BUILD.bazel, bazel/utils/remote.bzl, bazel/utils/remote/runner.template.sh, bazel/utils/remote_test.bzl, bazel/utils/testdata/remote/with-local-dir.files_to_copy.expected, bazel/utils/testdata/remote/with-local-dir.rsync.expected, bazel/utils/testdata/remote/with-local-dir.ssh.expected, bazel/utils/testdata/remote/with-non-run-target.files_to_copy.expected, bazel/utils/testdata/remote/with-non-run-target.rsync.expected, bazel/utils/testdata/remote/with-remote-dir-inverted.files_to_copy.expected, bazel/utils/testdata/remote/with-remote-dir-inverted.rsync.expected, bazel/utils/testdata/remote/with-remote-dir-inverted.ssh.expected, bazel/utils/testdata/remote/with-remote-dir.files_to_copy.expected, bazel/utils/testdata/remote/with-remote-dir.rsync.expected, bazel/utils/testdata/remote/with-remote-dir.ssh.expected
With this PR, remote_run is renamed to export_and_run, and can now:
- export a target to a local directory. This will copy the target
and all its necessary dependencies. This is useful for example
when there are generated files involved, and you want to use a
non bazel build or tooling.
- export (or remote copy) a non-executable target. When a target
is not executable, files are just copied.
- allow for detinations that contain a full path. So to copy files
in a specific remote directory, one can use 'machine:/path/to/dir'.
Added corresponding tests.
=> bazel/utils/remote: allow local copy, allow non-exec targets.

scripts/gee
I got annoyed that the gee-configured prompt wasn't perfect so I fixed it.
In bash: termcap and readline have a weird interaction where readline
doesn't understand which characters are non-printing and which aren't.
Bash has a prompting-specific workaround for this problem, which is to
explicitly label non-printing characters within "\[" and "\]" strings.
This PR correctly adds those labels so that readline will not corrupt
the column index when interactively editing a commandline.
Tested: manually.
=> gee bash_setup: fix non-printing characters in bash

bazel/init/stage_1.bzl
Upgrading gazelle to the latest release fixes an issue where
com_github_docker_docker takes many minutes to fetch (see
https://github.com/bazelbuild/bazel-gazelle/issues/1190#issuecomment-1069673991)
Tested: `bazel clean --expunge; bazel build //...` saw no noticeable
hangup on go repositories for once
=> bazel: Upgrade gazelle

bazel/init/stage_1.bzl
This reverts commit e0e5990f112b3263bd97675f0d9e367851d500bf.
#700 is causing gazelle errors when building enkit from internal like:
```
ERROR: /home/scott/.cache/bazel/_bazel_scott/d2f3bcdaee533eba5e33487f155bd516/external/org_golang_x_crypto/blake2b/BUILD.bazel:3:11: GoCompilePkg external/org_golang_x_crypto/blake2b/blake2b.a failed: (Exit 1): builder failed: error executing command bazel-out/k8-opt-exec-2B5CBBC6/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix linux_amd64 -src external/org_golang_x_crypto/blake2b/blake2b.go -src ... (remaining 29 arguments skipped)
Use --sandbox_debug to see verbose messages from the sandbox
compilepkg: missing strict dependencies:
/home/scott/.cache/bazel/_bazel_scott/d2f3bcdaee533eba5e33487f155bd516/sandbox/linux-sandbox/25/e …
```
=> Revert "bazel: Upgrade gazelle (#700)"

bazel/astore/defs.bzl, bazel/linux/repository.bzl
Fixing presubmit failures blocking enkit integration with internal.  The
issue was that `astore_download_and_extract` was being called from an
unexpected context, and the "timeout" attribute wasn't being populated
in the ctx context.
Since `astore_download_and_extract` is a public function, it has to support
being invoked with arbitrary ctx contexts.  (Really, these kinds of
implementation functions should never be public.)
This PR adds "timeout" attributes at tthe call sites I could find, and adds
reasonable defaults to support the call sites I couldn't find
(fail-functional).
Tested: Ran the following test from internal/master:
```
blaze query --override_repository=enkit=${HOME}/gee/enkit/astore_timeout @testing-latest-kernel//:all
```
The above command fails without these changes, and …
=> astore_download fix: add default value for timeout

scripts/gee
@hanu-enf reported a bug in which "gcd master" was taking him to a feature
branch directory instead of master.  We root-caused the problem to gee's
parsing of the output of `git worktree list --porcelain` which produces
output like this if a branch is in a rebase-in-progress state:
```
worktree /home/hanu/gee/internal/master
HEAD b144e5c34ff7bd8f24717337bde4bfd03fc649d0
branch refs/heads/master
worktree /home/hanu/gee/internal/cmn_reg
HEAD b144e5c34ff7bd8f24717337bde4bfd03fc649d0
detached
```
`gee` was not parsing the `detached` line correctly.  This PR fixes the issue
by parsing the `detached` line and then falls back on a secondary technique to
find the branch name if the branch is in a rebase-in-progress state.
If all else fails, gee gives up and uses the basename of the worktree …
=> gee gcd: fix incorrect mapping of branch-to-dir

tools/codegen/BUILD.bazel, tools/codegen/data_loader.py, tools/codegen/data_loader_benchmark.py, tools/codegen/data_loader_test.py
A user was complaining that parsing a particular YAML file (`mrng_map.elab.yaml`, 18MB)
was taking minutes of build time, so I decided to look into it.  It turns out that
if I switch from using the native python yaml parser to the compiled libyaml library,
I get a 15x performance improvement with no apparent downside.
I added a benchmark for loading a medium-sized yaml file:
```
len(big_text)=19331
yaml version = 6.0
yaml.Loader: 4.944591138999385
yaml.SafeLoader: 4.906097150000278
yaml.CSafeLoader: 0.35437141400143446
data_loader: 0.39925295200009714
```
"data_loader" is the slightly customized version of yaml.CSafeLoader that codegen
now employs.
Tested: Re-ran all //tools/codegen/... tests.  I also added a small benchmark
to data_loader_test.py.
=> codegen: switch to libyaml parser

bazel/linux/test.bzl
The output of commands executed by qemu_test is captured to a variable
and printed if the command fails. This behavior works fine with bazel
test which hides output by default. When the user executes a qemu_test
with bazel run, the expectation is to see the output in real time.
=> bazel/linux: print qemu_test output to stdout

bazel/init/stage_2.bzl
Without calling this init function, we cannot build `py3_image` targets.
Jira: INFRA-1492
Jira: INFRA-1494
=> bazel: Initialize python dependencies for Docker

bestie/server/BUILD.bazel, bestie/server/bigquery_metrics.go, bestie/server/main.go, bestie/server/service.go, bestie/server/test_result.go, bestie/server/xml_result.go
Bestie emits lots of data on every bazel invocation, which hides errors
in the log. Disabling the `--debug` flag, counterintuitively, hides the
errors, and emits the other debug data.
This change switches from the golang stdlib logger to glog, which gives
some global functions to log at different levels. While this doesn't use
the enkit logging library, using a global logger is not a regression for
bestie, and glog is strictly more convenient here.
Debug logs are changed to `glog.V(2).Infof()`s by default, which only
show up when passing the `--v=2 --alsologtostderr` flags. The ones that
are worrisome and not propagated as errors up the callstack are logged
as `glog.Error` or `glog.Warning`, appropriately. In some cases, log
statements are removed from deep in the callstack and an error …
=> bestie: Reduce logspam

bazel/linux/defs.bzl
The default number of jobs can be overriden with the jobs attribute.
=> bazel/linux: speed up kernel module builds by adding -j$(nproc)

bazel/linux/test.bzl
qemu_test should not pass size and timeout to the rules that it creates.
=> bazel/linux: allow size and timeout in qemu_test

scripts/gee
I'm not sure how, but for some users gh is configuring "origin" isntead
of "upstream" to be the base repo for managing PRs.  I still need to
root-cause why that happened to at least one user, but in the meanwhile
it's trivial to add a check to the "gee repair" command to detect the
condition and fix it.
I'm also changing the enkit agent environment variable check from looking
for SSH_AGENT_PID to SSH_AUTH_SOCK -- because in certain ssh-forwarded
environments, the latter will be set correctly even if the former isn't.
Tested: I manually broke my local git configuration, and then had gee
repair it.  I further verified that the gee repair command is harmless
in a healthy gee repo.
=> gee repair: fix incorrect gh-resolved settings

scripts/gee, scripts/gee.changelog.md, scripts/gee.md
Some bits of gee's conflict resolution flow are confusing.  Users seem
to be figuring it out, but these changes (hopefully) make the conflict
resolution options clearer, and improves the help.
There's a lot more I want to do here, but that extra effort will be
postponed until I have time to rewrite in python.
Tested: Created a merge conflict, manually ran through the conflict flow.
=> gee: improve conflict resolution flow

bestie/server/xml_result.go
* Updates bestie to handle `<error message="some error message">`
* Fixes issue where testcases that did not pass due to setup error were counted as passing
* Prior to this change, if a test case raised error in a setUp() class, the resultant test xml would have >0 error count, but since the error properties weren't handled they were being treated as passes.
=> bestie: Handle errors in test xml

bazel/linux/defs.bzl
=> bazel/linux: force colored GCC output when building modules

lib/logger/logger.go, proxy/httpp/interface.go, proxy/httpp/proxy.go, tools/codegen/BUILD.bazel
This change adds transform options to enproxy mappings to tell enproxy
to optionally add some headers on forwarded requests that signal the
authenticated user's identity to the backend.
Each value of the `Identity` object associated with the user is exposed
in its own header, and then an email-like string is exposed as well.
This is inspired by Grafana, which has a special ["Auth Proxy"](https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/auth-proxy/)
authentication mode, whereby it will respect the values of particular
headers as a pre-authenticated user.
Since these header values are configurable within Grafana, there is no
need to stick to their default-selected `X-WEBAUTH-USER`; we can choose
our own names and configure Grafana …
=> enproxy: Allow forwarding of user info via headers

scripts/gee
Previously, `gh auth login` asked the user a series of interactive questions
with ambiguous answers, and answering incorrectly would cause the authentication
process to fail.
This PR replaces the `gh auth login` flow with a gee-controlled flow that
walks the user through creating and installing a github authentication
token, and refuses to let the user proceed until this step is completed
successfully.
Also: `gee create_ssh_key` implements just the authentication part of
the `gee init` flow.
Tested: I ran `gh auth logout; gee create_ssh_key` on my own account to
create and enroll a new authentication token to github.
=> gee init: streamline github authentication token process

scripts/gee, scripts/gee.md
The typical user of "restore_all_branches" doesn't really want
to restore all the branches.  This change allows the user to
interactively select which branches to restore, if they have
the `dialog` utilty installed.
Alternately, a list of branches can be specified on the
commandline.
Tested: Works locally for me, also getting @abhienfabrica to help validate
a pre-release version.
=> gee restore_all_branches: make more interactive

scripts/gee
Reported by Leonid: "gee lsbranches" reports errors when attempting
to count whether the local branch is a head or behind the parent branch.
The underlying issue is "git rev-list" doesn't automatically fetch the
ustream branch reference when needed, but instead must be prefetched.
"gee pr_checkout" invokes "gh pr checkout" which does some very particular
things.  The parent property for the generated branch is set to
"upstream/refs/pull/NNN/head" which works for most but not all git commands.
"git rev-list", in particular, needs special handling: we have to use "git fetch"
to remap the upstream branch onto a local branch reference ("FETCH_HEAD" by default).
This PR wraps "git rev-list" in a helper function that insures that any upstream
PR reference gets mapped to a local reference, …
=> gee: fix lsbr query of upstream branches

scripts/gee, scripts/gee.changelog.md, scripts/gee.md
Just a quick bugfix: gee periodically invokes `savelog` to rotate it's log
file.  `savelog` sometimes writes to stdout, which then interferes with
the `gee gcd` command, which requires that the only thing written to
stdout is supposed to be the generated path.
This PR quick-fixes the behavior so that savelog triggering a log rotation
won't interfere with the functioning of gcd.
Tested: inflated ~/gee.log to be larger than 64K, forcing a log rotation
on the next gee invocation, and then ran `gee gcd master > /tmp/foo.txt`
to capture the stdout of gee under those conditions.  Confirmed that
savelog output no longer pollutes our results.
=> gee gcd: redirect savelog output to stderr

scripts/gee, scripts/gee.changelog.md
This PR fixes a minor annoyance: previously, gee would refuse to run certain
commands if executed outside of a gee-controlled git repository.  In the
spirit of "do what I mean not what I say", gee will now switch to a valid
gee-controlled git repository before proceeding.
Thus, gee commands can continue to operate under the assumption that
they are running from a gee-controlled git repository, and the user
has one less failure mode.
Tested: Ran "gee lspr" from a variety of directories.
In ~/gee/enkit: shows PRs associated with the enkit repository.
In ~/gee/internal: shows PRs associated with the internal repository.
In ~/gee: shows PRs associated with the internal (default) repo.
Previously, all 3 operations would fail.
=> gee: don't be so restrictive about what directory gee is run from

scripts/gee, scripts/gee.changelog.md
On a clean VM, I ran "gee init" and didn't get quite the right gh auth flow:
```
$ REPO=enkit gee init
...
CMD: /usr/bin/gh config set git_protocol ssh
Could not authenticate to github.  Got:
You are not logged into any GitHub hosts. Run gh auth login to authenticate.
Let's try refreshing your access token:
CMD: /usr/bin/gh auth login
? What account do you want to log into? GitHub.com
? What is your preferred protocol for Git operations?  [Use arrows to move, type to filter]
> HTTPS
SSH
```
whoops!  we want to avoid that prompt because if the user picks the wrong
options, it's confusing and tough to fix.
I modified gee to make sure our new gh authentication flow gets used
consistently, regardless of where in the code we're attempting to authenticate
to github.
Now I see:
```
$ REPO=enkit …
```
=> gee init: make sure we use the new gh auth flow

lib/kcerts/ssh.go, proxy/ptunnel/commands/agent.go
When forwarding access to ssh-agent using ssh, `SSH_AUTH_SOCK` gets configured
but `SSH_AGENT_PID` does not.  `enkit agent print` was checking for both
environment variables to be set, otherwise it would start a new agent.
This PR causes enkit to only check `SSH_AUTH_SOCK`, and if that variable
is set and the agent can be connected to, that agent gets used.
Tested: tests build and pass.
Manual testing:
```
$ $BROOT/bazel-bin/enkit/enkit_/enkit agent print
SSH_AUTH_SOCK=/tmp/ssh-jonathan/agent; export SSH_AUTH_SOCK;
SSH_AGENT_PID=123; export SSH_AGENT_PID;
echo Agent pid 123;
$ unset SSH_AGENT_PID
(enk:enkit_agent* S=2) [565] ~/gee/enkit/enkit_agent
$ $BROOT/bazel-bin/enkit/enkit_/enkit agent print
SSH_AUTH_SOCK=/tmp/ssh-jonathan/agent; export SSH_AUTH_SOCK;
```
=> enkit agent print: don't rely on SSH_AGENT_PID

tools/codegen/data_loader_benchmark.py
Interestingly, python's json parser is about 100x faster than even the
C-based libyaml parser.  Captured for future consideration.
Tested: Re-ran the benchmark.
=> data_loader_benchmark: also benchmark json.

scripts/gee, scripts/gee.changelog.md
While it appears that `enkit auth` is capable of inferring the username
to use during authentication, it turns out that it just caches this
information after the user does it for the first time.  We want gee
to work correctly on a completely clean install, and so the safest
option is to always specify the full `enkit auth $USER@enfabrica.net`
commandline.
Tested: rm ~/.config/enkit/* and then run `gee init`
=> gee: fix enkit auth invocation

flextape/server/run.sh
Update the default flextape hash to point to the latest release.
Testing:
- Deployed on infra-04.sea
JIRA: INFRA-1500
=> Update flextape hash

scripts/gee
gee pr_make runs some basic checks on the PR description the user
provides, namely there must be at least a title line, a blank line,
and a description body.  Customer error report complained that if
an error was detected, gee would exit and the user would lose their
PR description.  This fix gives the user an opportunity to re-edit
their PR description until they get it right.
I also added a check to make sure we don't mistake an unedited
PR template for a valid PR description.
Tested:
Ran `gee pr_make` with a bad PR description consisting of:
```
this is a
bad pr
description
```
gee informed me of the error and prompted me to re-edit the file.
This PR is the updated description.
Behavior when failing to make edits to the PR template:
```
$ ./gee pr_make
CMD: /usr/bin/git fetch upstream …
```
=> gee: let the user retry if their PR description is misformatted

scripts/gee
https://git-scm.com/docs/git-rerere
rerere is a feature that records the manual resolution of a conflict.  The
next time git runs into an identical conflict, it resolves it the same way.
This is useful when rebasing multiple branches.  For branches master->A->B,
if git rebase ends up renaming a commit when integrating from master into A,
that renamed commit becomes a merge conflict when merging from A into B.
With rerere, the manual resolution step when merging from master into A
is likely to be re-used when merging from A into B.
Tested: Still testing.
=> gee: turn on rerere for all users

scripts/gee, scripts/gee.bats, scripts/gee.changelog.md, scripts/gee.md, scripts/gee_test.sh
Current process is slow: check for failing tests, copy-paste the link into a browser,
scroll through a very long test log, hopefully find the tests that failed.
This PR accelerates that process for at least some cases, by extracting
the build ID from any failed test, pulling the log down directly using the
gcloud binary, and grepping that log for failures.
Tested:
I added a bats test for the function that parses the output of gh pr checks, and also tested manually in a branch with a failing test:
```
$ /home/jonathan/gee/enkit/gee_diagnose_checks/scripts/gee pr_checks
CMD: /usr/bin/gh pr checks
internal-bazel-presubmit             (cloud-build-290921)  fail      27m36s  https://console.cloud.google.com/cloud-build/builds/104e0ed9-6dd6-443d-8afd-1aa05c649fac?project=496137108493 …
```
=> gee pr_checks: report which tests failed

astore/server/main.go, bazel/utils/BUILD.bazel, bestie/server/main.go, flextape/server/main.go, lib/server/run.go, machinist/mserver/BUILD.bazel, machinist/mserver/controller.go, machinist/mserver/mserver.go, machinist/testing/machinist_e2e_test.go, test/example/server/main.go
Prometheus is currently fetching the list of nodes to scrape for metrics
from `mserver` via DNS A records. This means that metrics have
`instance=<IP>` on each, with no hope of ever mapping that back to a
hostname.
As it turns out, we can (and do) expose other types of DNS records, but
there is no way to get Prometheus both IP and hostname information via
DNS (it doesn't allow for fetching from the right kind of record, or
limits the fields it fetches from records that could contain both).
This change adds a separate mechanism that Prometheus does support: an
HTTP handler. By fetching `/metrics_targets`, a JSON array will be
generated that Prometheus understands that specifies scrape IPs and
their associated hostname. Port is not part of the address exposed, so
this must match …
=> machinist server: Add HTTP endpoint for discovering nodes to scrape

bazel/linux/templates/runner.template.sh
Set the environment variable $COLUMNS inside the VM if it is
appropriate.
Jira: https://enfabrica.atlassian.net/browse/SF-217
=> bazel/linux: pass terminal columns in VM

bazel/utils/remote.bzl
Really, that print should never have been merged.
Operator error. Removed.
=> bazel/utils/remote.bzl: remove leftover debug print.

proxy/enproxy/enproxy_test.go, proxy/ptunnel/tunnel.go
- proxy/enproxy: improve enproxy_test to move more data and print status.
- proxy/tunnel: fix retry strategy.
- proxy/tunnel: fix handling of short reads.
=> fixing tunnel

lib/knetwork/shutdown.go, proxy/ptunnel/commands/BUILD.bazel, proxy/ptunnel/commands/tunnel.go, proxy/ptunnel/commands/tunnel_test.go
This change extends the functionality of the `-L`/`--listen` flag on
`enkit tunnel` to support Unix Domain Socket URLs as listen targets, in
the form `unix:///path/to/socket`. This involves:
* creating a function to contain the logic that normalizes the contents
of the flag. The flag needs to continue to support `host:port`, as
well as just a naked `port`, in addition to the new UDS path.
* fixing dependent code to not assume `TCPAddr`/`TCPConn`. In some
places, type assertions are necessary, as TCP and Unix variants
contain necessary methods not in the top-level interface; these should
be relatively safe as long as we don't expand the network types to
types that lack these methods.
Additionally, cleanup logic is improved by creating a Context that
becomes done on SIGINT, and plumbing …
=> enkit tunnel: Support listening on Unix Domain Sockets

enkit/version/version.go, lib/stamp/BUILD.bazel, lib/stamp/stamp.go
This change adds a "Built at" line to `enkit version`, which displays
when the binary was built.
Tested:
* `bazel run //enkit -- version` - shows that it was built at the "zero"
time
* `bazel run --stamp //enkit -- version` - shows that it was built now
=> enkit version: Add build time info

enkit/BUILD.bazel
This change enables cgo in the enkit build, which gives it access to the
cgo DNS resolver, which uses glibc on applicable machines to do DNS
resolution. This is necessary for DNS resolution to work properly in
constrained environments, such as the Cadence VCAD chamber.
Tested: `GODEBUG=netdns=cgo+2 enkit tunnel...` shows successful DNS
resolution, whereas `GODEBUG=netdns=go+2` shows continuous failures when
DNS resolution is done via NIS.
=> enkit: Enable cgo

bazel/astore/defs.bzl, enkit/BUILD.bazel
This change ensures that cgo is enabled and used in the Linux binary, so that it can resolve addresses in the Cadence VCAD chamber machines, where NIS is used (via nsswitch.conf/glibc).
It would seem that as soon as either goos/goarch and/or static is set on the binary, rules_go uses a bazel "transition" that loses any `cgo` attribute set on the binary. This is visible when building with `--subcommands`, as the `CGO_ENABLED` env var is not set, and the resulting binary cannot use the cgo DNS resolver.
Setting `pure=off` and not setting `static` seems to be the most reliable way to get a working cgo binary.
Tested:
* Built with `bazel build //enkit:deploy`, which builds the versions that will actually be pushed to astore
* Ran `GODEBUG=netdns=cgo+2 …
=> enkit: Enable cgo resolver for deployed linux binary

flextape/proto/BUILD.bazel
Makes the flextape proto publicly visible so we can take on some of the messages as dependencies in other repos.
=> Flextape - Make Proto Public

bestie/server/main.go
Bestie is rejecting messages larger than the gRPC server default of 4MB. Since bazel targets message sizes of up to 50MB, bestie should support this as well.
This change adds a server option that sets the maximum allowed message size to a flag value, which has a default of 50MB.
Tested: no
Jira: INFRA-1828
=> bestie: Raise max gRPC message size

lib/kbuildbarn/BUILD.bazel, lib/kbuildbarn/urls.go, lib/kbuildbarn/urls_test.go
When bazel is talking to the BES endpoint via UNIX domain socket, it embeds bytestream URLs that have:
* an excessive number of slashes (bytestream://////rest/of/path)
* no host - only a path
* path is absolute path to the UDS on the client joined with the normal path (/blobs/hash/size)
This change modifies the parse code to tolerate and rewrite these URLs correctly.
Tested: unit tests
Jira: INFRA-1836
=> kbuildbarn: Tolerate bytestreams from UDS URLs

lib/bazel/affected_targets.go, lib/bazel/affected_targets_test.go, lib/bazel/commands/BUILD.bazel, lib/bazel/commands/commands.go, lib/bazel/exec.go, lib/bazel/exec_test.go, lib/bazel/options.go, lib/bazel/query.go, lib/bazel/query_test.go, lib/bazel/target.go, lib/bazel/workspace.go, lib/bazel/workspace_test.go
Recommendation: review one commit at a time, they are self contained.
This PR and set of commits allows to aggressively re-use the cache by running commands sequentially, while setting all the right flags. It includes some minor refactors.
- enkit/lib/bazel: move the code to compute affected targets in a function.
- /lib/bazel: add support for serial query or parallel query.
- lib/bazel: allow to override output_base and bazel query from command line.
- lib/bazel: remove unused method.
- lib/bazel: minor workspace.go refactor to lazily load variables.
- lib/bazel: set output_base from current client when doing things serially.
- lib/bazel: add ability to pass extra arbitrary flags to bazel.
- lib/bazel: improve debug output.
=> lib/bazel: add support for serial builds, more flags, more workspace

scripts/gee
This is a small tweak to restore_all_branches to make it "do the right thing" if
invoked from outside a gee directory.
Tested: manually ran it.
=> gee restore_all_branches: work outside gee directory

WORKSPACE, bazel/init/stage_2.bzl
We're starting to write go in our repo, but we don't want to pull in two sets of go_repositories - one from enkit and one from our repo.
Extracting the go_repositories call from step 2 allows us to bring in enkit into our repository but not it's go_repositories. This way our repo can pull in our own go_repositories.
This will also require all things enkit to be built from enkit and no other repo.
Tested by building enkit after changes (`bazel build enkit`)
Jira: INFRA-1834
=> WORKSPACE - Extract go_repositories Call From Step2

BUILD.bazel, enkit/BUILD.bazel, faketree/BUILD.bazel, flextape/server/BUILD.bazel, manager/client/BUILD.bazel
This change adds a multirun target at the top level BUILD file to release all binaries that internal needs to use, adding `astore_push` rules for each where they are missing.
Tested: Ran, pushing binaries:
```
...it-linux-amd64: uploading 24.27 MiB / 24.27 MiB [----------] 100.00% 22.10 MiB p/s 1s
...it-linux-amd64: committing amd64-linux 24.27 MiB / 24.27 MiB  100.00% 20.14 MiB p/s 1
...t-darwin-amd64: uploading 23.98 MiB / 23.98 MiB [----------] 100.00% 25.70 MiB p/s 1s
...t-darwin-amd64: committing amd64-mac 23.98 MiB / 23.98 MiB [ 100.00% 22.07 MiB p/s 1s
...-win-amd64.exe: uploading 24.46 MiB / 24.46 MiB [----------] 100.00% 26.20 MiB p/s 1s
...-win-amd64.exe: committing amd64-win 24.46 MiB / 24.46 MiB [ 100.00% 23.16 MiB p/s 1s
| Created                 Creator …
```
=> binaries: Add top-level target to release all

scripts/gee
ssh-add has a failure mode such that, if SSH_AUTH_SOCK is a forwarded
credential socket created by an ssh process, and that ssh process goes
away, ssh-add -l will hang indefinitely.
This PR adds a timeout so that ssh-add won't hang indefinitely, and gee can
attempt to recover from the situation by creating a new ssh-agent.
Tested: Proved that the change is harmless, but haven't proved that it
resolves the issue in all circumstances yet.  At least, the situation
is better than it was.
=> gee: add timeout for ssh-add

bazel/linux/runner.bzl, bazel/linux/templates/runner.template.sh
Without this PR, it's not possible to supply wrapper flags to
the rule - only through the command line.
The only alternative is to create a sh_binary wrapper to the
wrapper wrapping the emulator wrapping our code invoked by
the bazel wrappers. In short this PR can avoid yet one more
wrapping.
=> bazel/linux/runner: add support for hard coding wrapper flags.

bazel/astore/BUILD.bazel, bazel/astore/astore_upload_file.sh, bazel/astore/defs.bzl
Problem: our users are routinely updating collateral in astore, but
are neither tracking nor using the UID of each upload to keep files
strictly version controlled.  When asked to specify all files by
UID, users replied that this was too much extra manual work.
This PR attempts to address this problem by automating the updating of a
UID-specifying variable in an arbitrary text file (ie. a bazel BUILD file).
This way, the user can commit this change into source control to keep all
astore_download targets strongly version controlled.
Two variables are updated for each target:
`UID_<TARGETNAME>` -- the astore-assigned UID for the uploaded file
`SHA_<TARGETNAME>` -- the sha256sum of the uploaded file
where `TARGETNAME` is a transformation of the uploaded target filename
(see docstring).
Right …
=> astore_upload: add "uidfile" functionality

bazel/astore/BUILD.bazel, bazel/astore/defs.bzl
This PR adds optional uid/digest attributes to astore_download, and
then uses those values to validate the variables that were automatically
updated by astore_upload.
Tested: Ran the new download targets manually:
```
$ blaze build :test_astore_download_file :test_astore_download_file_with_digest
```
Automated presubmit testing isn't possible due to the lack of enkit
credentials in the presubmit environment.
=> bazel/astore: update astore_download to take optional uid/digest attributes

bazel/astore/defs.bzl
Acting on late-arriving feedback from PR #775: this PR
only actives "no-remote" if a uid is not specified.
Tested: manually, using the command:
```
cd bazel/astore
blaze build :test_astore_download_file :test_astore_download_file_by_uid :test_astore_download_file_with_digest :test_astore_download_file_v1
```
=> astore_download: remove no-remote if uid is specified

lib/kcerts/ssh.go
One time while logging in I saw the following message:
```
2022-10-04T16:12:08.202Z        WARN    error saving credentials, err: symlink /tmp/ssh-wKEavpGmnw/agent.41963 /home/jonathan/.config/enkit/agent: file exists
ERROR: symlink /tmp/ssh-wKEavpGmnw/agent.41963 /home/jonathan/.config/enkit/agent: file exists
```
Everything seemed to work, but this message wasn't sufficient for me to debug
the code, especially since we're never performing the operation in question.
Nothing seems broken, but let's improve the error messages anyway so we can
root cause this properly in the future.
Tested: All existing tests still pass.
=> enkit: improve enkit agent error message

bazel/astore/BUILD.bazel, bazel/astore/tests/BUILD.bazel, bazel/astore/tests/manual_test.sh, bazel/astore/tests/testdata.txt
presubmits for the integration PR uncovered a surprising error:
* https://github.com/enfabrica/internal/pull/9321
* https://console.cloud.google.com/cloud-build/builds/7ed83bd9-dae0-4482-bc2a-2d36a5653dd2;step=6?project=cloud-build-290921
An example error message:
```
ERROR: /tmp/git_temp_worktree_2097900939/hw/projects/mlm/design/chip/macro_gen/BUILD:10940:14:
every rule of type astore_upload implicitly depends upon the target
'@enkit//bazel/astore:astore_upload_file.sh', but this target could not be
found because of: error loading package '@enkit//bazel/astore': Label
'//bazel/astore:defs.bzl' is invalid because 'bazel/astore' is not a package;
perhaps you meant to put the colon here: '//bazel:astore/defs.bzl'?`
```
The issue is resolved by adding a bzl_library rule to …
=> bazel/astore: fix integration errors

bazel/astore/defs.bzl
It is sometimes useful to specify download artifacts by human readable tags instead of by UID. Supporting `use_default_shell_env` also allows `--action_env` bazel command line arguments to set environment variables.
Testing:
`bazel run //bazel/astore:test_astore_download_file`
JIRA: INFRA-1942
=> Support downloading artifacts from astore by tags

scripts/gee, scripts/gee.bats, scripts/gee.changelog.md
The users are right: the "autostash" behavior is the right choice for
the "just function" philosophy of gee.  This PR re-enables autostash,
but adds a few checks for post-rebase merge conflict markers, just
in case a merge conflict was introduced when the stashed changes
got re-applied.
Tested: Used modified gee to run `gee rupdate` in a branch with uncommitted changes.
=> gee: re-enable autostash

lib/bazel/query.go
The external-target-attribute-rewrite logic has a bug where it captures
a loop variable by reference, causing targets to get renamed with the
incorrect name. This change makes a copy of the loop variable and
assigns a reference to the copy instead, so that it is not mutated as
the loop continues.
This fixes an issue where affected-targets will return extra targets that
aren't actually changed between the two revisions.
Tested: `bazel affected-targets list --loglevel-console=info --start=4b551678e --end=swc_copy`
with this change doesn't yield erroneous targets, whereas it used to
roughly ~20% of the time.
Jira: INFRA-1548
=> bazel affected-targets: Fix target name bug

bazel/go_repositories.bzl, enkit/outputs/commands.go, go.mod, go.sum, proxy/ptunnel/BUILD.bazel, proxy/ptunnel/tunnel.go, proxy/ptunnel/tunnel_test.go
When doing `enkit outputs mount`, the destination host resolves to an IP in the network due to DNS spoofing to redirect traffic to a persistent tunnel. The logic correctly recognizes that it does not need to create an additional tunnel, but then attempts to connect to the remote port (traefik on 8080, in this case) rather than the persistent tunnel port (8001).
This change expands the tunnel decision logic to accommmodate the "persistent tunnel on the gateway" case. When this scenario is detected, no tunnel will be created, but the port will be replaced with `tunnelPort` in the returned value. By setting the `--tunnel-listen-port` flag, the target port can be changed to the port the tunnel on the gateway is listening on.
Tested:
* `bazel build //guidelines/...`
* `enkit outputs mount -i …
=> enkit outputs: Support persistent tunnels

enkit/outputs/commands.go
This change modifies the default tunnel port to match that of the one used for tunneling to buildbarn. This does not cause conflicts, as both the bazel profile script and this code starts a persistent background tunnel, and continues gracefully if the tunnel already exists.
Jira: INFRA-2122
=> enkit outputs: Change default tunnel port

bazel/utils/remote.bzl
The reference below gets into more details, but the dependencies of a remote_run rule are really runtime dependencies that need to be compiled for the target architecture. We want the dependencies to be built as if they were built as a top-level target on the remote machine. While tools might follow the "exec" config, that does not apply here either.
Ref: https://bazel.build/extending/rules#configurations
Jira: SF-478
=> remote: Use "target" config instead of "host" for remote_run rule

scripts/gee
This change saves the user a little time when debugging presubmit failures.
`gee pr_checks` now reports a summary of the error messages from the
presubmit job, including the line that contains a URL that points to
the specific buildbuddy page that contains the information the user
probably needs to fix the issue.
Tested: Ran the updated pr_checks command in a branch with a build failure.
=> gee pr_checks: capture URL for buildbuddy

README.md
This change adds import instructions, documenting the way we import enkit into internal and the resulting caveats.
This change also reformats the README with `mdfmt` for consistency, and changes the syntax used to codeblocks where appropriate.
Tested: No
Jira: INFRA-2420
=> README: Clean up, add import instructions

scripts/gee
While working on an unrelated problem, I finally figured out why
gee's error reporting (trap ERR) wasn't working correctly.  I learned:
* `set -E` is required to enable "errtrace" mode, allowing the ERR trap
to be inherited by functions and subprocesses.
* in bash 4.0, the EXIT trap behavior changed so that the LINENO environment
variable is always reset to 1 inside EXIT handlers.  (This feels like a
misfeature to me.)
Now that I can get ERR traps to work correctly, I can get gee to correctly
report the line number, command, and exit code of any failing command that
is causing the gee script to fail.  This should be make debugging user issues
a little easier in the future.
Tested: added a hidden "debug_error_reporting" subcommand to gee that
emulates an error condition.  Running this …
=> gee: improve error reporting

scripts/gee, scripts/gee.changelog.md, scripts/gee.md, scripts/git_recover_stash
A user recently had an issue where they had dropped some stashed
changed that they wanted to hold onto.  This PR automates the
process of discovering the identifiers necessary to recover
dropped stashed changes.
Tested: manually:
$ ./gee recover_stashes enkit
Created temporary FSCKFILE=/tmp/stashes-jonathan.0JTAXI
Searching your repo for discarded stash commits...
Checking object directories: 100% (256/256), done.
Checking objects: 100% (8266/8266), done.
Cached search results to FSCKFILE=/tmp/stashes-jonathan.0JTAXI
Found 58 commits.
Filtering candidate commits...
Found 4 matches.
914c9f7f2a43e34c8b1f8ac26f478d4a3ae66c46 Sat Sep 24 12:56:57 2022 -0700
7b81aec0ed7806963e79bd2b236523aba57405a7 Tue Oct 4 07:33:03 2022 +0000
b957986e8044e8b3097591bae25dfee04e567469 Tue Oct 4 09:32:05 2022 …
=> gee: add `recover_stashes` command

scripts/gee
A previous PR (#778) introduces trap-based error reporting for all
unhandled error conditions.  In the course of my testing, I realized
that many gee commands report failure via a non-zero return code,
which was being trapped as an error instead of allowing gee to
terminate normally.
This PR captures the return code of all gee commands and returns
them correctly (using `exit`), removing the spurious error messages.
Tested: Manual testing of `gee pr_checks` in clients with and without
PR failures, which results in the gee command either returning success
or failure.
=> gee: fix error reporting from gee commands that report failures

astore/server/auth/auth.go, lib/kcerts/ssh_test.go
The goal is to allow using the domain name as part of the
policy handling.
=> astore/server/auth: create ssh certificates with user and user@domain.

scripts/gee
Now that gee has proper ERR trap notification, I'm discovering a few unhandled
ERR traps (ie. places in the code where a command returns a non-zero exit code
that isn't explicitly checked / handled).
This single-line PR fixes one such unhandled return code.
Tested: manual testing confirms that the err trap is squashed.
=> gee: fix an ERR trap

machinist/config/machine.go, machinist/machine/commands.go, machinist/machine/node.go
This change adds a new flag that disables much of the static machine configuration done, so that machinist does not fight with current/future puppet configuration on startup.
This flag defaults to true for backwards compatibility, and will have to be explicitly specified in Puppet.
Dynamic steps (writing out keys, certs, etc. received from the auth server at runtime) are not affected by this flag - only static configuration and installation steps are controlled.
Tested: `bazel build //machinist/cmd && bazel-bin/machinist/cmd/cmd_/cmd node enroll --require-root=false --loglevel-console=debug --modify-machine-config=false --auth-server=https://auth.corp.enfabrica.net --sshd-configuration-file=/tmp/machinist/sshd_config --ca-key-file=/tmp/machinist/ca.pub …
=> machinist: Flag off most machine configuration

bestie/server/test_result.go
Today, bestie log looks like this:
```
I1108 19:51:06.937045       1 test_result.go:110] Opened output file "test.xml" for processing
E1108 19:51:06.937236       1 test_result.go:201] Error extracting XML metrics: Unstructured XML test results not supported (use junitxml)
I1108 19:51:06.941944       1 test_result.go:110] Opened output file "test.xml" for processing
E1108 19:51:06.942796       1 test_result.go:201] Error extracting XML metrics: Unstructured XML test results not supported (use junitxml)
I1108 19:51:06.975101       1 test_result.go:110] Opened output file "test.xml" for processing
E1108 19:51:06.976956       1 test_result.go:201] Error extracting XML metrics: Unstructured XML test results not supported (use junitxml)
```
There's no way to tell which failure is associated …
=> bestie: add invocation id to logs

lib/stamp/BUILD.bazel
This change updates the variables the stamp library uses to be compatible with internal's `workspace_status` script.
Tested: Vars used are correct when built against internal with `--override_repository=enkit=/home/scott/dev/enkit`
=> stamp: Update vars used

bazel/init/stage_1.bzl
This change updates rules_go and gazelle to the latest releases, to pick up any bug fixes and performance improvements that have been released since our last update.
A bug was previously preventing us from updating; it was related to gazelle not recognizing `go_repository` macros from third-party repositories (we couldn't tag functions in this repo as a go_repository macro from a downstream repo) but this is no longer an issue since downstream repos do not load dependencies from this repo anymore.
Tested:
* Various targets in enkit still build
* Internal builds all go targets with `--override_repository=enkit=...`
Jira: INFRA-3214
=> go: Update rules_go, gazelle to latest releases

astore/server/BUILD.bazel, astore/server/deploy/app.yaml
AppEngine now supports go 1.19! This change updates the runtime in app.yaml, and removes the target that enforces a build for go 1.16.
Tested: no
Jira: INFRA-3479
=> astore server: Update to go 1.19

scripts/gee, scripts/gee.md
`gh pr checks` reports data formatted like this:
```
triage  pass    4s      https://github.com/enfabrica/internal/actions/runs/3588585723/jobs/6040131746
Pushes-preview-version-of-web-pages (cloud-build-290921)        skipping        0       https://console.cloud.google.com/cloud-build/triggers/edit/c731b7a4-47a4-4ee2-8d5e-e0f699da7568?project=496137108493
external-dependencies (cloud-build-290921)      skipping        0       https://console.cloud.google.com/cloud-build/triggers/edit/4298bbb8-4289-4d32-be9e-5d0d69fe27de?project=496137108493
experimental-bazel-presubmit (cloud-build-290921)       pass    7m48s   https://console.cloud.google.com/cloud-build/builds/da0cf69c-6612-431b-9ea2-8fec49ef800a?project=496137108493
linter-checks (cloud-build-290921)      pass    34s …
```
=> gee: fix pr_checks output format

flextape/server/run.sh
Update the flextape license counts in the textproto file.
Tested:
- Deployed on infra-04.sea
JIRA: INFRA-2687
=> Update flextape server hash

scripts/gee, scripts/gee.md
This is a shortcut for invoking ripgrep over the entire current branch.
If ripgrep is not installed, this command falls back on the grep utility.
I guess I've been doing this operation several times a day, so it felt
useful (to me) to include as a shortcut in gee.
Tested: Installed locally and tested manually.  The hidden `GEE_NO_RIPGREP`
environment variable is used to demonstrate the "fallback on grep"
functionality.
```
$ grg fdst
CMD: rg fdst /home/jonathan/gee/enkit/gee_grep
/home/jonathan/gee/enkit/gee_grep/bazel/appengine/deploy/main.go
23:     fdst, err := os.OpenFile(dst, os.O_RDWR|os.O_CREATE, 0660)
27:     defer fdst.Close()
29:     _, err = io.Copy(fdst, fsrc)
34:     if err := fdst.Sync(); err != nil {
38:     return fdst.Close()
$ GEE_NO_RIPGREP=1 grg fdst
CMD: grep -r …
```
=> gee: add grep command

scripts/gee
The ~/.cache/bazel-disk-cache is also growing quite large on shared machines.
This PR improves the `gee bazelgc` command to automatically delete any action
from the bazel disk cache with an atime of earlier than than 5 days ago.
Tested: manually.
```
$ ./gee bazelgc
No ~/.cache/bazel directories to delete.
About to delete 6631 old entries from ~/.cache/bazel-disk-cache
Proceed? (y/N)  y
CMD: rm -f /home/jonathan/.cache/bazel-disk-cache/cas/e4/e4706db70e97f59781a2383c1e3c9c63228438ad35349d56b0d4d949204dfd51 /home/jonathan/.cache/bazel-disk-cache/cas/e4/e4c532c726d601dbd0bd4ec9582c1011831641dcd36d0a3eb67053499a93fe35  [...]
```
=> gee bazelgc: also gc ~/.cache/bazel-disk-cache

flextape/server/run.sh
Update the docker image hash for the deployed version of flextape on infra-04.sea
Tested:
- Deployed on infra-04.sea with correct license counts. However, the `jasper_fao` license feature just expired today after my pull request https://github.com/enfabrica/internal/pull/12931 was merged. Argh, I will create a silence and schedule another flextape update for `jasper_fao`.
License Alerting:
```
[FIRING:4, RESOLVED:5] (P1)
**Firing**
Value: B=2, C=1
Labels:
- alertname = flextape license count drift
- grafana_folder = infra_services
- license_type = cadence::jasper_fao
- priority = P1
```
JIRA: INFRA-3994
=> flextape: Update the flextape version

scripts/gee, scripts/gee.changelog.md, scripts/gee.md
Unfortunately, in the real world:
```
$ gee bazelgc
No ~/.cache/bazel directories to delete.
About to delete 21053 old entries from ~/.cache/bazel-disk-cache
Proceed? (y/N)  y
/home/jonathan/bin/gee: line 4597: /usr/bin/rm: Argument list too long
Approximately 0MiB freed.
```
Looks like we ran into the ARG_MAX limit of the bash command line.  To work
around this issue, I've modified gee to delete files in batches of 100 files
per rm invocation.
Tested: Installed and re-ran in the same directory:
```
$ gee bazelgc
No ~/.cache/bazel directories to delete.
About to delete 21053 old entries from ~/.cache/bazel-disk-cache
Proceed? (y/N)  y
Approximately 6190MiB freed.
```
=> gee bazelgc: handle very long lists of files to delete

bazel/astore/tests/BUILD.bazel
An earlier PR added `astore_download` rules as tests; these rules fail in postsubmit due to the absence of credentials. This change adds a tag that excludes these rules from postsubmit.
Tested: no
=> astore_download: Disable rules in postsubmit

bazel/utils/testdata/remote/with-all-inputs.files_to_copy.expected, requirements.txt, tools/codegen/BUILD.bazel, tools/codegen/codegen.py, tools/codegen/tests/d2-test.expected, tools/codegen/tests/gen-test.expected, tools/codegen/tests/test.template
We are adding support for capnp generation of C kernel code.
This requires a lot of turning CamelCase to snake case, or
screaming snake case. Rather than implementing all this in
jinja templates, this PR brings in:
https://pypi.org/project/jinja2-strcase/#description
That provides simple python implementations for the needed
conversion functions.
=> tools/codegen: add case handling extension in jinja2.

bes_publisher/BUILD.bazel, bes_publisher/buildevent/BUILD.bazel, bes_publisher/buildevent/mockstream_test.go, bes_publisher/buildevent/service.go, bes_publisher/buildevent/service_test.go, bes_publisher/main.go, third_party/bazel/src/main/java/com/google/devtools/build/lib/buildeventstream/proto/BUILD.bazel
This change adds a BEP handler server that will eventually publish important messages it sees onto PubSub.
In this iteration, the server simply increments metrics for messages seen, and optionally logs if the logging level is set high enough.
Tested:
* Unit tests
* Manually (see steps below)
To run manually:
* `bazel run //:gazelle && bazel run //bes_publisher -- --alsologtostderr --v=2`
* Run a bazel build: `bazel test //bes_publisher/... --bes_backend=grpc://localhost:6433`
* View metrics: `curl localhost:6433/metrics`
=> bes_publisher: Add new BEP handler server

bes_publisher/BUILD.bazel, bes_publisher/buildevent/BUILD.bazel, bes_publisher/buildevent/errslice.go, bes_publisher/buildevent/mockpubsub_test.go, bes_publisher/buildevent/pubsub.go, bes_publisher/buildevent/service.go, bes_publisher/buildevent/service_test.go, bes_publisher/main.go
This change adds logic to propagate `BuildStarted` events into a pubsub topic, with the attributes specified in
https://docs.google.com/document/d/1kA17-zwUxFDHrcpogQv5fMa9MLJpTkhwEAMAqzYCBr0/edit#heading=h.kbi1exowvrim.
Unit tests are added to ensure:
* the expected messages are published
* the messages have the correct attributes
* PublishResults received from Publish calls are handled properly
Tested: unit tests
=> bes_publisher: Publish to pubsub topic

bes_publisher/buildevent/BUILD.bazel, bes_publisher/buildevent/service.go, bes_publisher/buildevent/service_test.go, bes_publisher/main.go, lib/gmap/BUILD.bazel, lib/gmap/gmap.go
This change adds more messages to the list published by `bes_publisher`,
along with a test that ensures the attributes are aggregated correctly.
This change also adds a generic map library, with convenience functions
for maps so that these simple functions no longer need to be duplicated
in the codebase.
Tested: unit tests
=> bes_publisher: Publish more messages

scripts/gee, scripts/gee.changelog.md, scripts/gee.md
This adds two useful convenience commands to gee.
find: for quickly finding a named file in a branch.
vimdiff: vimdiff a file against the parent branch version.
Tested: manually ran each command.
=> gee: add find and vimdiff commands

third_party/bazel/src/main/java/com/google/devtools/build/lib/buildeventstream/proto/BUILD.bazel, third_party/bazel/src/main/protobuf/BUILD.bazel
This change adds `py_proto_library` rules for the Bazel BES proto, so that code in internal can depend on it.
Since internal only wants to use the top-level BES proto, only that rule needs to have public visibility; the dependencies can stick with restricted visibility.
Tested: Code in internal that requires the proto builds with this change when `--override_repository` is set appropriately
=> third_party: Add Python proto rules

bazel/enkit_credential_helper/BUILD.bazel, bazel/enkit_credential_helper/main.go
This change adds a binary that can act as a credential helper to bazel
as specified in
https://github.com/bazelbuild/proposals/blob/main/designs/2022-06-07-bazel-credential-helpers.md.
If successful, this will allow us to drop the tunnel requirement for
buildbarn.
Tested:
* Credential helper can successfully get through enproxy
Not tested (future PR):
* Helpful errors thrown when credentials don't exist
=> bazel: Add enkit_credential_helper

.bazelrc
This change cleans up the bazelrc:
* Dead flags are removed - assuming users know how to edit .bazelrc
* Flags specific to testing with NodeJS rules are removed, as NodeJS has also been removed from the repo
* `disk_cache` flag is removed, which avoids filling up the local disk without bound, and also allows `bazel clean` to work as expected. Prior to this change, building after `bazel clean` does not actually fully rebuild if hits are found in the disk cache.
Tested: Presubmits only
=> bazelrc: Clean up flags

bes_publisher/buildevent/BUILD.bazel, bes_publisher/buildevent/service.go, bes_publisher/buildevent/service_test.go, lib/gmap/gmap.go
This change adds:
* propagation of `TargetComplete` messages, so that listeners can process the build completion of non-test targets
* addition of `rule_type` attributes to `TargetComplete` and `TestResult` messages, which will allow handlers to filter by rule type.
Tested: Stood up locally with debug handler, observed correct messages and attributes being propagated
=> bes_publisher: Add TargetComplete messages, more attributes

scripts/gee
`gee commit` in the master branch produces an error message that contains
instructions on moving uncommitted changes to a new branch.  The instructions
were incorrect, this fixes them.
Tested: n/a
=> gee: fix "move changes to new branch" instructions

lib/retry/README.md, lib/retry/retry.go, proxy/ptunnel/tunnel.go
Background:
Authentication credentials have a time limit. Generally around 1 day.
Once they expire, they can no longer be used.
if I closed my laptop today and reopened it tomorrow, an existing
tunnel or ssh session would look frozen. Not because the protocol
cannot recover, but because the tunnel/ssh is stuck using the old
credentials - even after an enkit login.
There is code in enkit to re-load the credentials, but due to the
structure of the code this was only invoked once at session establishment
time, rather than at every attempt.
For the end user, this manifested as "I closed my laptop, re-opened
the day after, sessions are dead, no matter what".
With this PR:
Correctly re-evaluate options at each re-connection attempt, including
the ones to reload the …
=> proxy/ptunnel: correctly reload credentials after expiry.

enkit/proto/presubmit.proto, lib/bazel/affected_targets.go
In this PR:
- add support to only execute tests *including* at least one of the
specified tags.
=> lib/bazel: implement an included_tags, to limit to a subset of targets.

scripts/gee, scripts/gee.md
This means that `gee find` will also search the bazel-bin and similar
directories for generated files.
Tested: manual testing.
=> gee find: also search symlinks

bazel/appengine/configtools/BUILD.bazel
This change explicitly declares pyyaml as a package dependency requirement to the `merge` py_binary target. This will fix the `//specs:specs-web-config` target in internal which is broken right now on master.
Tested: 
- `BAZEL_PROFILE=buildbarn bazel build --override_repository=enkit=$HOME/enkit //specs:specs-web-config`
- http://buddy.gcp01.corp.enfabrica.net/invocation/3b5b0d5c-061e-472d-8b41-f2457547ed1e
- `BAZEL_PROFILE=buildbarn bazel test $(bazel query "kind(py_*, //...)")`
```
INFO: Analyzed 23 targets (0 packages loaded, 0 targets configured).
INFO: Found 20 targets and 3 test targets...
INFO: Elapsed time: 13.588s, Critical Path: 13.47s
INFO: 2 processes: 2 linux-sandbox.
INFO: Build completed successfully, 2 total actions
//bazel/linux/kunit:kunit_test …
```
=> python3 hermetic toolchain bug fix: Fix missing pyyaml requirement in bazel target

scripts/gee
Customer report says: they ran `gee update` to pull in commits that
other users had pushed onto their PR.  The commits caused merge
conflicts, leaving their branch in a bad state.
Root cause: When pull updated from origin, gee was assuming those
updates were safe and was using a naked `git rebase` invocation
instead of the safer rebase flow.
Fix: use the safer rebase flow with interactive conflict resolution
when merging commits from origin.
Tested:  testing in progress.  I won't submit until I've manually tested this flow,
but there's a few steps to get there.
=> gee update: use safer rebase flow when integrating changes from origin

scripts/gee, scripts/gee.changelog.md, scripts/gee.md
One user was making the mistake of thinking that "gee commit" was pushing
changes back into another user's PR, instead of their local fork of that
PR.  "gee commit" now detects if a user is committing a change in a fork
of a PR, and emits a message letting the user know that commit != pr_push.
Tested: n/a
=> gee: add pr_push note in gee commit

scripts/gee, scripts/gee.changelog.md
It has been brought to my attention that gee's colorscheme sucks: especially
the white-on-yellow colors used to report fatal errors.
New color scheme:
* info messages are green on black
* warning messages are yellow on black
* commandlines are black on blue
* fatal messages are black on red
Tested: Added a secret "colortest" command to view all message formats.  Looks
better than it used to.
=> gee: improve colors

scripts/gee
This one is a doozy:  This fixes a bug in gee where failure of the simple `gh
pr merge` command would cause an entire PR to be reverted and the PR closed.
Root cause:
gee's pr_submit command contains roughly this sequence of commands:
```
··_gh pr merge \
····--squash \
····--body-file "${BODYFILE}" \
····--repo "${UPSTREAM}/${REPO}" \
····"${FROM_BRANCH}"
...
··_git checkout -B "${CURRENT_BRANCH}" "upstream/${MAIN}"
··_push_to_origin "+${CURRENT_BRANCH}"
```
The last two commands force the current branch to reset --hard to master,
and then force-pushes to update origin, so that the branch can continue
to be used.  This is safe to do, because if `gh pr merge` failed, the `set -e`
context of this bash script should cause the funciton to exit, and the last
two commands won't run.  Right? …
=> gee: fix gee pr_submit trashing changes bug

scripts/gee
Previously, we had this bug:
`gee rerun; gee pr_submit --wait`
Would incorrectly submit a PR even though the checks hadn't started yet.  The
issue is that github is slow, and so after requesting presubmits, there is
a period of time where `gh pr check` tells us that there are no presubmits
and returns a "success" return code.
We don't want that -- so now gee will verify that at least one presubmit check
is being reprorted by `gh pr check` before confirming that checks have passed.
There's still a risk of fast presubmit checks completing before slow presubmit
checks have even started, but I don't know quite what the right solution is
(yet), and this fix will correct the problem >99% of the time.
Tested: `gee rerun && gee check --wait`
=> gee check: wait for checks to start

bazel/astore/defs.bzl, bazel/init/stage_1.bzl
This change switches to using a pre-built `astore` client for `astore_download` and `astore_upload` rules, since building the client is not supported in certain environments currently.
The astore client was built manually and uploaded to astore at `bazel/workspace_deps/astore`, before being publicly exposed so that it could be fetched via HTTP (fetching via astore would cause a bit of a chicken-and-egg scenario).
Tested: `bazel build //bazel/astore/tests:test_astore_download_file` still works
Jira: INFRA-4783
=> astore_download: Use prebuilt astore client

scripts/gee
github has a bug where the server will drop git ssh connections while it is
still cleaning up from a `gh pr merge` operation.  This PR adds a retry
to `git pull` after `gh pr merge` to work around the issue.
Tested: I was able to reproduce the issue by running `gee checks` right after
running `gee commit`.  gee handles gh's behavior correctly now.
```
$ gee commit -a -m "fixed"
CMD: /usr/bin/git add --all
CMD: /usr/bin/git commit -a -m fixed
[gee_retry_pull 3f0c0db] fixed
1 file changed, 22 insertions(+), 24 deletions(-)
CMD: /usr/bin/git fetch
CMD: /usr/bin/git push --quiet -u origin gee_retry_pull
$ ./gee check
CMD: /usr/bin/gh pr checks
Waiting for checks to start.
Some checks are still pending.  [W]ait, [r]etry, [a]bort, or [c]ontinue without waiting?  w
Waiting until all pending …
```
=> gee: retry failed pull requests

bazel/utils/remote/runner.template.sh, bazel/utils/testdata/remote/simple.ssh.expected, bazel/utils/testdata/remote/with-all-basic.ssh.expected, bazel/utils/testdata/remote/with-decorated-wrapper.ssh.expected, bazel/utils/testdata/remote/with-destdir.ssh.expected, bazel/utils/testdata/remote/with-local-dir.ssh.expected, bazel/utils/testdata/remote/with-noop-inputs.ssh.expected, bazel/utils/testdata/remote/with-opts.ssh.expected, bazel/utils/testdata/remote/with-remote-dir-inverted.ssh.expected, bazel/utils/testdata/remote/with-remote-dir.ssh.expected, bazel/utils/testdata/remote/with-wrapper.ssh.expected
The runner template syntax does not correctly work in the case of csh, this change fixes the failure by running the command in a bash env.
=> bazel: Runner template should be capable of running in non bash env

proxy/httpp/interface.go
This change defines the new types and additions to the enproxy config struct that enable mapping headers to request based on the user's groups.
The proposal enables a config spelled like:
```yaml
- from:
host: 'monitoring.corp.enfabrica.net'
to: http://127.0.0.1:3000/
transform:
xwebauth: "set"
mapRequestHeadersByGroup:
- header: X-Webauth-Role
groupMapping:
- group: foo
value: Admin
- group: bar
value: Editor
- group: ""
value: Viewer
```
To translate to: "Add `X-Webauth-Role: Admin` to users in the `foo`
group; add `X-Webauth-Role: Editor` to users in the `bar` group; add
`X-Webauth-Role: Viewer` to everyone else".
Tested: N/A
Jira: INFRA-4919
=> enproxy: Define config changes for conditionally adding headers

lib/oauth/ogoogle/BUILD.bazel, lib/slice/BUILD.bazel, lib/slice/slice.go, lib/slice/slice_test.go, proxy/httpp/BUILD.bazel, proxy/httpp/interface.go
This change implements the "map request headers by group" functionality, which allows header values to be assigned to a given header conditionally based on group matching. #890 has context on how the feature works.
In order to simplify the logic a bit, a helper library is created to convert slices into maps, reducing the need for nested `for` loops within the feature implementation itself.
Tested: unit tests only
Jira: INFRA-4919
=> enproxy: Implement mapRequestHeadersByGroup

bazel/linux/bundles.bzl, bazel/linux/defs.bzl, bazel/linux/providers.bzl, bazel/linux/runner.bzl, bazel/linux/templates/init-qemu.template.sh, bazel/linux/templates/init-uml.template.sh, bazel/linux/test.bzl
The next PR will add support for always being able to start an sshd
server within the test, and providing a cozier debugging environment.
A pre-requisite is to define the steps/commands necessary to run a
test, versus the steps/commands necessary to setup the environment.
This set of commits expands the capabilities of vm_bundle and friends
to support this.
- bazel/linux: remove nv_.* related rules, that are unused and obsolete.
- bazel/linux: add support for initialization steps in vm setup.
- bazel/linux: expand bundle capabilities to support list of binaries.
- bazel/linux: expand bundles to support recursive expansion.
- bazel/linux: improve qemu_test target to propagate init correctly.
=> bazel/linux: various feature additions in preparation for next PR

enkit/BUILD.bazel
Cadence chamber machines require a cgo-enabled version of `enkit` in order to properly resolve DNS names via e.g. NIS. This change swaps out the default build of enkit Linux binaries from pure-Go to cgo to build this cgo version by default, which should also be compatible with all other current environments.
Tested: `bazel run //enkit:enkit-linux-cgo-amd64 -- astore ls` still works locally
Jira: INFRA-5312
=> enkit: Always build cgo-enabled enkit for Linux

bazel/linux/bundles.bzl, bazel/linux/providers.bzl, bazel/linux/runner.bzl, bazel/linux/test.bzl
This PR fixes issues introduced in PR#878, and uses a better and simpler
approach to handle expansion of parameters.
More details in the descriptions of individual commits.
Tested: run all tests that failed in PRESUBMIT for:
https://github.com/enfabrica/internal/pull/17184
- bazel/linux: propagate arguments correctly.
- bazel/linux: use a better approach to handle recursion, fix bugs.
=> bazel/linux: fix breakages introduced by PR#878, variuos improvements

bazel/workspace_status.sh
Background:
lib/stamp/... seems to use the variable naming convention defined by
the buildbuddy documentation, used in the internal/ repository.
When building from the enkit repository (as is the default now with
the new release process? based on astore? not sure) stamping has
broken variables.
In this PR:
- use the same naming convention as the internal workspace_status.sh command.
=> bazel/workspace_status.sh: fixed stamping of binaries.

bazel/go_repositories.bzl, bazel/init/stage_1.bzl
Currently, patch labels are specified starting with `//` (omitting `@enkit`) which makes them "repo-relative": when another repo calls a macro that has a repository rule that references a patch with this format, it looks for the patch within itself instead of enkit.
To avoid having to duplicate these patches in other repos, this change makes the patch paths absolute, so other repos will look for them within enkit itself.
Tested:
* Built internal targets via `--override_repository`; confirmed this fixes build in internal
=> bazel: Make all patches repo-absolute

enkit/cmd/BUILD.bazel, enkit/cmd/command.go, enkit/machinecert/BUILD.bazel, enkit/machinecert/commands.go
This change adds boilerplate for (unimplemented) `machine-cert` subcommands `print` and `install` which show a machine's SSH certificate or generates and installs a new one, respectively.
Both commands are left unimplemented; this PR proposes both the names, commands, and file locations only.
`machine-cert` was chosen rather than `login` (which is usually used for people doing one-time logins) and `machine` (which I believe is implemented via plugin bash script.
Tested: Builds, commands print unimplemented
Jira: INFRA-5652
=> enkit: Add `machine-cert` subcommand

bazel/go_repositories.bzl, bb_reporter/BUILD.bazel, bb_reporter/main.go, bb_reporter/reporter/BUILD.bazel, bb_reporter/reporter/service.go
This change adds an implementation of a `CompletedActionLogger` server that basically drops all messages, while:
* logging a single message to stdout every once in a while, so we can see some actual test data
* collecting metrics, so we can get an idea of the scale of the data
Eventually this service should upload messages to some sort of database, but that will come in a future PR. This PR is sufficient to confirm that the implementation of the skeleton is sufficient to interoperate with Buildbarn.
Tested: Server builds and starts.
Jira: INFRA-5725
=> bb_reporter: Add no-op server

bazel/go_repositories.bzl, bb_reporter/main.go, bb_reporter/reporter/BUILD.bazel, bb_reporter/reporter/service.go
This change parses the `CompletedAction` message into a struct which will represent a BigQuery table entry. The proto message is not used directly in case it has too much nesting to be a useable BigQuery schema.
Pushing to BigQuery is still not implemented, but the parsed struct is printed periodically on stdout instead of the received message.
This change also modifies the batch size parameter, boosting that and the batch timeout params to flags in the process.
Tested: Deployed; successfully showing entries and no log errors/warnings
Jira: INFRA-5726
=> bb_reporter: Parse to BigQuery struct

bb_reporter/main.go, bb_reporter/reporter/BUILD.bazel, bb_reporter/reporter/bigquery.go, bb_reporter/reporter/service.go
This change implements BigQuery writing for each batch of `ActionRecord` instances.
Each struct is taught to implement `bigquery.ValueSaver`, which is an interface whereby each is converted to a row. This is a bit extra for a few reasons:
* the bigquery library can infer a schema from a struct instance (though it is not clear how the field names are inferred)
* there is already a conversion from proto message to struct, and now a second conversion from struct to map - it's possible to do this in one conversion. This double-conversion approach is chosen because it makes the metrics/logging more explicit (rather than needing to parse the Bigquery client library errors).
The BigQuery insertion code implements an interface that looks like internal's `memo.Inserter`, in case the latter is ever …
=> bb_reporter: Write results to BigQuery

bestie/server/test_result.go
404's in bestie logs don't show enough info to be debuggable. This change causes these errors to be logged with the URL that was attempted, in order to debug whether the URL is malformed.
Tested: deployed; saw URLs logged in errors
Jira: INFRA-5854
=> bestie: Improve error reporting around fetch failures

bestie/server/test_result.go, lib/kbuildbarn/options.go, lib/kbuildbarn/protoparse.go, lib/kbuildbarn/urls.go, lib/kbuildbarn/urls_test.go
buildbarn-browser URL patterns changed with a recent upgrade - they now
include the hash function used to calculate a particular blob.
We currently use SHA256 everywhere and don't plan to change, so this
change modifies the client libraries to accept a hash function name, and
buildbarn/unit test code to hardcode "sha256".
Tested: unit tests only
Jira: INFRA-5855
=> kbuildbarn: Fix buildbarn-browser URL generation

enkit/machinecert/BUILD.bazel, enkit/machinecert/commands.go, enkit/machinecert/install.go
This change implements the install command.
Not a ton of thought is put into adding tests; this command is useful in
the short-term to quickly issue some certs for the Cadence chamber
machines so that people can SSH between them cleanly.
Tested:
* Run locally; is able to create a keypair and obtain a signed
cert
Jira: INFRA-5652
=> enkit machine-cert: Implement `install` subcommand

bb_reporter/reporter/BUILD.bazel, infra/k8s_dummy/BUILD.bazel, infra/k8s_dummy/main.go
This change adds a test webserver that helps validate:
* external access works as expected
* metrics can be collected
It may be extended in the future to allow for testing gRPC, etc.
Jira: INFRA-5878
=> k8s: Add test webserver

renovate.json
Nobody is reviewing those PRs, and they are polluting the
PR queue. Just disable renovate until we can start paying
more attention to it.
=> disable renovate

astore/server/deploy/app.yaml
This change modifies the AppEngine manifest to enforce that there is always one instance running of the auth server, which should eliminate the possibility of auth errors due to the request timing out before an instance is available.
Running an instance consistently shouldn't incur too much cost, as it runs in a cheap application class.
Tested: N/A
Jira: INFRA-6047
=> auth server: Ensure that exactly one instance is always running

astore/server/main.go, bazel/go_repositories.bzl, bb_reporter/main.go, bes_publisher/main.go, bestie/server/main.go, flextape/server/main.go, go.mod, go.sum, infra/k8s_dummy/main.go, lib/kcerts/BUILD.bazel, lib/server/run.go, machinist/mserver/mserver.go
This change adds a `context` parameter to `server.Run`, which is used to shut down the server(s) by closing the underlying mux. This allows for a (semi-)graceful shutdown via e.g. signals for the apps that implement this via `signals.NotifyContext`.
`cmux` is updated since only the latest version has a `CMux.Close` method.
Tested: `k8s_dummy` now does a proper shutdown on Ctrl-C
Jira: INFRA-6066
=> server: Allow for graceful shutdown via context

bazel/init/stage_3.bzl, lib/protocfg/BUILD.bazel, lib/protocfg/cfg.go
This change adds a library that can load proto-based configuration files from a variety of file formats, with autodetection based on file extension.
This can replace some less-developed internal libraries once internal is updated to a new version of this repo.
Tested: Manually only, that jsonnet configs can be loaded successfully.
=> protocfg: Add library for parsing config files

shims/buildbuddy/BUILD.bazel, shims/buildbuddy/cmd/main.go, shims/buildbuddy/urls.go, shims/buildbuddy/urls_test.go
The buildbuddy shim rewrites bytestream URLs in query strings to trick BuildBuddy into fetching content from Buildbarn. Prior to this change, a shim can only rewrite any host it sees to a single bytestream host.
With this change, the shim will take a map of rewrites to perform, and rewrite the bytestream host depending on what the original bytestream hsot was. This will allow us to instruct a single BuildBuddy instance to redirect to multiple Buildbarn instances, as long as the hosts in the original bytestream requests are distinct in some way. (currently, they are distinct by either port number if a tunnel is used, or URL if no tunnel is used).
This code can be improved in many ways, but this change just extends functionality and modifies tests to test the new functionality.
Tested: unit …
=> bb_shim: Extend to take a map of bytestream hosts

bazel/init/stage_1.bzl
... see changelog here for new changes:
https://github.com/abseil/abseil-cpp/releases
Main ones interesting to enfabrica:
- logging library integrated in absl - which allows us to deprecte
both glog and gflags, and fix a number of pain points around flag
parsing.
- addition of the Cleanup for scope cleanup - allowing to deprecate
equivalent constructs
Tested:
Built and tested a large chunk of our codebase with the new absl version.
CI/CD will likely provide good signal here as well.
=> bazel/init: update absl version to the latest one.

bazel/dependencies/abseil/0001-absl-flags-parse.cc-provide-a-mechanism-to-let-other.patch, bazel/init/stage_1.bzl
In the latest abseil release there is no sane way to use multiple flag
libraries: there is no easy way to tell abseil to 1) ignore the flags
it does not know about and 2) LEAVE THEM in the returned argv 3) strip
the flags it does parse and know about. 2 out of 3 are possible using
the internal API, 3 is not.
This patch adds the ability to ignore flags abseil does not know about
AND leave them in the returned argv, which enables us to use multiple
flag libraries for code that is not based on abseil.
abseil in head provides a different function to achieve a similar
result, but it's very clumsy to use as it CHANGES the order of argv
arguments, which affects other flag parsing libraries.
Tested:
See corresponding PR in internal using and testing the feature.
=> bazel/dependencies/abseil: patch abseil to support multiple flag libraries.

bestie/server/BUILD.bazel, bestie/server/bigquery_metrics.go, bestie/server/main.go, bestie/server/service.go, bestie/server/test_result.go, bestie/server/xml_result.go
It is currently difficult to tell if bestie is having consistent issues due to the dashboard being incomplete; even for metrics shown, it is nontrivial to find the code location causing specific counters to get hit.
This change performs minimal changes to existing metrics (names, types etc.) but refactors their usage:
* metrics are no longer incremented in a goroutine - spawning gigantic numbers of goroutines spontaneously could be the cause of OoM issues
* metrics increments are inlined. This reduces the amount of code, and makes finding a code location for a given metric a 2-3 step process
* where metrics are limited to use in one file, the definition is moved to said file
Some small changes to metric semantics were made:
* insertion delay metric captures actual wall time from insertion …
=> bestie: Clean up metrics

bazel/dependencies/abseil/0001-absl-flags-parse.cc-provide-a-mechanism-to-let-other.patch
absl: update the patch to avoid flag reordering.
Background:
ABSL reorders argv to have -- and - flags first. This breaks flag
parsing by other libraries.
- update the patch so that when preserving flags is selected,
argv is not reordered.
Tested:
added test in other PR, will provide link separately.
=> absl: update the patch to avoid flag reordering

bazel/go_repositories.bzl, bazel/qtc/BUILD.bazel, bazel/qtc/dummy.go, go.mod, go.sum
There are currently some repositories fetched in the gazelle-generated list from go.mod that are needed, but don't actually have imports in the Go source. This leads to an issue where Go tooling is constantly trying to prune them from go.mod, and so Gazelle is trying to prune them from go_repositories.
Up until now, we have all been carefully stepping around this issue. This change fixes the issue by adding a dummy package with a few imports that ensures those packages are kept around.
=> gazelle: Fix pruning of necessary dependencies

.gitignore, .vscode/settings.json, bazel/go_repositories.bzl, bazel/qtc/BUILD.bazel, bazel/qtc/dummy.go, go.mod, go.sum, tools/gopackagesdriver.sh
The Go language server / bazel integration finally looks stable enough
to use - this change proposes that we make the setup canonical, and adds
some supporting scripts to make this possible.
This PR adds:
* the recommended gopackagesdriver.sh script from the editor setup
guide: https://github.com/bazelbuild/rules_go/wiki/Editor-setup#2-launcher-script
* the recommended editor config from the editor setup guide:
https://github.com/bazelbuild/rules_go/wiki/Editor-setup#2-launcher-script
Since editor-specific config files are gitignore'd, this change removes
the gitignore for vscode settings. The rationale here is that some of
these settings are truly project-specific (`gopls` LSP configuration
for bazel actually is different from normal Go projects, and is
different per bazel workspace) and …
=> vscode: Set up Go language server 

astore/server/main.go
This is mandatory for non-dynamic-scaling deployments. For dynamic
scaling... not as clear.
The handler always returns 200 and logs the request.
=> astore: handle appengine /_ah/ requests.

bb_reporter/reporter/service.go
This change removes unset `INTERVAL` fields from the struct, to fix a bug causing inserts to fail.
These fields were strings, which are translated to INTERVAL values by the bigquery library upon insert; however, when they are empty string, this conversion fails instead of converting to null.
This change fixes the issue by removing the fields entirely, causing them to be unset upon insert.
=> bb_reporter: Remove unset INTERVAL fields

bazel/utils/exec_test.bzl
Tests in bazel are normally built for the target platform, not
for the exec (or host) platform. The target platform is what needs to be
tested (although there can be multiple target platforms).
Further, cfg = "exec" applies to all direct and indirect
dependencies of a rule, as it changes what the target is.
Basically, any exec_test causes the entire dependency graph
of the test to be rebuilt for a different platform.
=> bazel/utils: fix exec_test to use the target platform.

bazel/update_goldens, bazel/utils/BUILD.bazel, bazel/utils/diff_test.bzl, bazel/utils/testdata/expected.foobar.bin
A diff_test user reported a problem where "update_goldens" was failing with a UnicodeDecoderError.
The problem turned out to be the `diff` tool reporting a binary diff, which contained
an invalid utf-8 sequence, which was raising this exception inside RunCheckOutput.
This PR updated the public version of update_goldens to be identical to our internal
version, enabling us to reproduce the issue.  The issue is then addressed by adding a
"binary" flag to diff_test that causes the "cmp" tool to be used instead of "diff"
for diff'ing binary files.  There were other ways to solve this issue, but this
is broadly the correct way to handle diffing binary files.
Tested: Added a foobar.bin and foobar.bin-diff_test.  Verified that update_goldens
fails with binary = False, but succeeds with binary = …
=> diff_test: compare binary files

scripts/gee, scripts/gee.md
This PR prepares gee for migration of the default branch in our
repo from "master" to "main."
The `gee migrate_default_branch` command will fix-up the gee-controlled
repositories to match the default branch of the upstream repo.
Tested: I created a "main" branch in my local repo, and used the new
command to verify that gee can "switch" from "main" to "master."  This
operation should be equivalent to switching from "master" to "main" when
the upstream repo branch name changes.
=> gee: add "migrate_default_branch" command

bazel/linux/utils.bzl
If a kernel_module rule has multiple dependencies that introduce the same module, we need to filter them out before we try to load them. (Functionality is described in the utils.bzl file but not fully implemented).
Tested:
kunit_test target that was failing due to `insmod: ERROR: could not insert module driver/core/enf-ubuntu-impish-generic/enf/host/enf.ko: File exists` is now passing
=> Remove duplicate kernel modules from dependencies

scripts/gee, scripts/gee.changelog.md, scripts/gee.md
Add `gee setup enable_bcompare` to configure gee to use the commercial
BeyondCompare tool to resolve merge conflicts.  The goal here is to make
it easy for Enfabricators to evaluate the use of BeyondCompare to see if
buying a license is worthwhile.
Tested: Manually tested in my hw-dev container.
=> gee setup: add "enable_bcompare"

bazel/dependencies/rules_foreign_cc_export_functions.patch, bazel/init/stage_1.bzl, bazel/meson/meson.bzl
This change updates `rules_foreign_cc` to the latest released version.
The new version takes a function that we were using private, so this change adds a patch to re-export it. `meson.bzl` is updated where some of the function signatures/contracts changed, and meson is updated to the latest release as well.
This change will need to be coupled with #<internal PR> when updating enkit in internal, as there is a change to how make variables are written/substituted during expansion that breaks existing builds otherwise.
Tested: See https://github.com/enfabrica/internal/pull/20899
Jira: INFRA-6722
=> rules_foreign_cc: Update to latest version

bazel/dependencies/make_less_pedantic_configure.patch, bazel/init/stage_1.bzl
Buildbarn FUSE workers don't expose proper timestamps, which confuses `configure` scripts that check for such things. This change adds a patch that removes this check for the `make` tool itself, which allows `make` to build on Buildbarn FUSE workers.
Tested: `BAZEL_PROFILE=buildbarn-staging bazel build @capnproto//... --override_repository=enkit=/home/scott/dev/enkit` can get past `make` build (fails on next build with similar `configure` script issue)
Jira: INFRA-6712
=> make: Patch with less pedantic `configure` script

bazel/astore/defs.bzl
Currently, we can apply patches on top of `http_archive` tars, but not `astore_package` tars. This change adds `patches` and `patch_args` attributes, and calls the same underlying `patch` util function that implements this for `http_archive`.
In theory, we can simply apply patches before uploading tars to astore. However, this inserts manual steps in the mirroring process, adding friction and increasing the probability of error. With this change, we can mirror code to astore as-is, and patch after-the-fact, which is at least enforced by automation.
=> astore_package: Add attributes to allow for patching

scripts/gee
A previous PR changed gee's behavior so that if the branch "main"
exists, gee assumes that the upstream branch's main branch is named
"main" instead of "master."
Some users have both "main" and "master" branches, and so the selection
of main branches are ambiguous.  gee started making an incorrect
assumption about the name of the upstream main branch, and this broke
some gee functionality.
This PR detects the condition where both "main" and "master" exists
and instead of making assumptions, warns the user that this arrangement
is confusing and then queries github to see what the real upstream
main branch is named.
Tested:
I created both main and master branches in my local repo and tested
gee.
```
$ ./scripts/gee up
WARNING: Confusing!  You have both "main" and "master" branches.
CMD: …
```
=> gee: handle the scenario where main and master branches both exist

bazel/astore/defs.bzl, lib/bazel/query.go
Affected targets detection currently handles external repositories by rewriting labels like `@repo//some:target` into a single label `@repo` whose only attribute is the sha256 of the downloaded archive; thus, if the archive changes, all rules that depended on some target within are also assumed to have changed. This is a bit conservative, but necessary so that:
* hashing all files within external repositories can be skipped
* dependency crawling code doesn't need to handle a variety of edge cases that might require patching third-party dependencies to work around
SHA256sums of the archives are picked up via the "workspace event log" which keeps track of each archive downloaded during the query; by querying when no dependencies are fetched, we will get a hash of each download reliably. …
=> enkit bazel: Collect a sha256 from commands that download files

bazel/init/stage_1.bzl, bazel/meson/test/BUILD.bazel
rules_foreign_cc was recently updated to the latest release, though this release is now a year old and doesn't contain the newest `meson` rule, which we can use to drop our current implementation. This PR updates `rules_foreign_cc` to the latest master commit.
Tested: `@qemu-uds` targets still build in internal with this change (and tweaks to make `meson()` rules compatible with rules_foreign_cc)
=> rules_foreign_cc: Update to latest master commit

bazel/dependencies/rules_python/custom_annotations.patch, bazel/init/stage_1.bzl, requirements.txt
This change:
* updates `rules_python` to the latest released version (which is just generally a good thing to do, as it reduces tech debt)
* adds a patch that allows for specific packages to be patched to avoid circular dependencies
The patch comes from
https://github.com/bazelbuild/rules_python/pull/1166#issuecomment-1641878169 and is necessary as airflow has made multiple of their packages dependent on each other on purpose for reasons that are unlikely to be walked back on. This is apparently valid in pip-land, but of course not valid in bazel. The patch is a nice medium-term workaround while the community figures out exactly how this should be handled.
Tested:
* `bazel test //...` in this repo (needed to regenerate `requirements.in`)
* affected-targets detection in internal to verify …
=> rules_python: Update to 0.24.0; add patch to handle circular deps

lib/bazel/affected_targets.go
This change removes the cursed bit of logic that skips the presubmit if the beginning of the build graph was broken; this allows the presubmit to pass for a change that rolls back build graph breakage, which used to be a problem.
This is still ostensibly a problem; however, now we have a more educated team and a mechanism to force the presubmits to pass, so this bit of logic can be removed, which is causing its own version of pain.
Tested: no
Jira: INFRA-7604
=> enkit bazel affected-targets: Remove presubmit skipping

bazel/enkit_credential_helper/main.go
This change modifies `enkit_credential_helper` so that if `ENKIT_OVERRIDE_TOKEN` is set, that value is used instead of opening the token from an on-disk storage. This will fix integration issues with environments that provide this token via secrets-backed environment variables.
Tested:
* `bazel run //bazel/enkit_credential_helper -- get` (normal behavior)
* `ENKIT_OVERRIDE_TOKEN=foo bazel run //bazel/enkit_credential_helper -- get` (override behavior)
=> enkit_credential_helper: Respect ENKIT_OVERRIDE_TOKEN env var

tools/codegen/codegen.bzl
This patch adds a `deps` label_list attribute to the `codegen()` rule.
The files listed in the `deps` are passed as `inputs` to the
implementation's `ctx.action.run()`.
This allows codegen top-level jinja2 templates to import or include
other templates, which is nice for creating re-usable template macro
libraries.
=> codegen: add a 'deps' attribute to the rule

bazel/go_repositories.bzl, go.mod, go.sum
This change updates the `bb-remote-execution` dependency to the latest version in preparation for fixing the dependencies in enkit such that libraries from this dependency can build successfully.
Tested: `bazel test //...`:
=> go: Update bb-remote-execution

infra/postsubmit/proto/postsubmit.proto
This change adds a field so that the container image + version can be manually overridden in postsubmit definitions.
This will help us test an image in a specific postsubmit before pushing it to all postsubmits.
Tested: N/A
Jira: INFRA-7115
=> postsubmits: Add a container_image field to spec

scripts/gee
Our containers lack a dbus subsystem, which causes the gh tool to misbehave
and spawn hundreds of dbus-launcher tasks.  The suggested fix from the
maintainers is to use the --insecure_storage option when calling gh auth login.
Additionally fixed a couple of unrelated pet peeves:
* Draft PR descriptions will no longer have the word DRAFT embedded in them.
* #-comments in code snippets won't be stripped (only lines starting with #
will be trimmed).
Tested: tbd
=> gee: workaround gh auth login bug

scripts/gee
Even though this is the correct workaround for gh's dbus-launcher bug,
it turns out that the `--insecure-storage` flag is not supported on
every version of gh.  Rather than force every user to upgrade, I'm just
removing the flag.  I haven't seen many reports of the dbug-launcher
issue lately anyway, maybe github got around to fixing it after all.
Tested:
=> gee: remove "--insecure-storage" from gh auth command

scripts/gee, scripts/gee.md
As requested by Ankit:
This PR adds GEE_REPO_DIR, GEE_DIR, GEE_REPO environment variables for overriding
gee's behavior.  I also updated the built-in help for gee to document these and
other environment variables.
To support these variables correctly, I also went through the gee script and
removed places where the original ~/gee/<repo> path was baked into the code.
Tested: Installed the updated gee, and used it for a variety of operations,
both with and without all three of the aforementioned environment variables set.
shellcheck still passes.  I'm going to kick this version of gee around a
bit more before cutting a formal release, and I'll ask Ankit to help me beta
test.
=> gee: add GEE_REPO_DIR environment variable

bes_publisher/buildevent/service.go
`aborted` events carry info about which tests did not run/finish in a particular invocation. This change ensures these messages are propagated (not all messages from the BES stream are propagated to save on Pubsub costs), so that downstream consumers can use them.
This is necessary to add info to DV dashboards about which regression tests did not finish.
Tested: builds only
Jira: INFRA-7972
=> bes_publisher: Propagate `aborted` events

scripts/gee, scripts/gee.changelog.md, scripts/gee.md
Ankit found a bug in gee where gee misbehaves if the GEE_DIR environment
variable is set to a path that ends with a "/" instead of a more canonical
path representation.
This PR armors gee against such things by using `realpath -m` to convert all
paths read from the environment into their canonical form.
This PR also updates the official gee version to 0.2.45 in preparation
for a new formal release.
Tested:
Previously, this sequence of commands would fail, and now they succeed:
```
$ export GEE_DIR=/home/jonathan/shared/jonathan
$ gee gcd master
/home/jonathan/shared/jonathan/internal/master
$ export GEE_DIR=/home/jonathan/shared/jonathan/
$ gee gcd master
/home/jonathan/shared/jonathan/internal/master
$ export GEE_DIR=/home///////jonathan/shared/jonathan//.///
$ gee gcd master …
```
=> gee: normalize paths from environment

infra/postsubmit/proto/postsubmit.proto
This change adds a mechanism for adding user-friendly debugging steps for determining why a postsubmit isn't behaving properly.
The first step added is a "large file printer", which will print out the largest N files in a particular directory; this will be useful for debugging INFRA-8302.
Tested: N/A
Jira: INFRA-8302
=> postsubmit: Add support for debugging steps

infra/postsubmit/proto/postsubmit.proto
Some builds require extra local storage in order to run correctly. This change adds a field that allows for the amount of space required to be captured.
Tested: N/A
Jira: INFRA-8419
=> postsubmit: Add option to specify local disk space

scripts/gee
priority: low
I didn't realize that the "set window title" escape sequence was specific to
screen/tmux and isn't supported by, say, xterm, causing users of the default
gee prompt to see some extra garbage on their screens.
Tested:
```
$ echo $TERM
screen-256color
$ eval "$(./gee bash_setup)"
$ gcd master
( confirmed that window title changed )
$ gcd gee_prompt
( confirmed that window title changed )
$ TERM=xterm
$ gcd master
( confirmed that window title did not change )
```
=> gee: disable window title when not running in screen or tmux

scripts/gee
When gee creates a new branch, it checks to see if a branch with the same
name exists in origin, and if it exists, it offers to restore the branch
from origin.
old behavior: gee would rebase the origin/branch onto master, which could
have merge conflicts.
new behavior: gee resets the branch to be identical to origin/branch, letting
the user choose when to rebase.
Tested: I used this feature in my build-00 container to restore a branch that
I had previously created from my build-04 container.  Works.
=> gee: reset instead of rebase when restoring a branch

scripts/gee, scripts/gee.changelog.md, scripts/gee.md
gee's bisect command is a wrapper around `git bisect` but automates the
process somewhat:
1. a temporary branch is created for use during bisection, so the
user's main branch is never changed.
2. a heuristic is used to try to find a previous good commit at some
point in the past.
3. after finding the suspect commit, the tool cleans up after itself
and removes the temporary branch.
Tested: Used to find a suspect commit in a branch I'm debugging.
=> gee: add bisect command

machinist/cmd/BUILD.bazel
This change compiles machinist for windows so that the hostname and IP address of windows machines can be ingested by prometheus.
Tested:
- Windows machine dashboard: https://monitoring.corp.enfabrica.net/d/IV0hu1m7z/windows-machine-statistics?orgId=1
- Installed machinist on the windows machine
```
bbhuynh@rosaparks:/opt/prometheus$ curl http://127.0.0.1:4456/metrics_targets | python3 -m json.tool
...
{
"labels": {
"hostname": "intelbs-02"
},
"targets": [
"10.10.255.10"
]
},
{
"labels": {
"hostname": "intelbs-01"
},
"targets": [
"10.10.255.17"
]
},
{
"labels": {
"hostname": "mtv-lab"
},
"targets": [
"10.10.255.8"
]
},
{
"labels": {
"hostname": "windows-00"
},
"targets": [
"10.10.255.8"
]
}
]
```
JIRA: INFRA-8348
=> machinist: Compile machinist for windows machines

CODEOWNERS, scripts/gee, scripts/gee.md
As reported in Jira INFRA-7849, the Sonora container has a /usr/bin/git from
2013.  A modern version is available in as /usr/enfabrica/bin/git, but gee has
to go looking.
This PR:
* changes gee's initialization code to search a list of paths to find
the best installed version of a tool
* allows the user to force gee to use a specific version of a tool by
setting the GIT, GH, JQ, and/or ENKIT environment variables
Tested: Ran `gee diagnose` and noted the correct paths for all tools are
reported.
=> gee: allow override of default tool paths

bazel/init/stage_2.bzl
This change updates the Golang toolchain used to the latest release, to fix the build for new third-party dependencies that will be added in a future change.
Tested: `bazel test //...` seems to be equivalently clean
=> go: Update version to 1.21

BUILD.bazel, bazel/go_repositories.bzl, bazel/init/stage_2.bzl, experimental/nomad_resource_plugin/licensedevice/BUILD.bazel, experimental/nomad_resource_plugin/licensedevice/cmd/nomad_license_plugin/BUILD.bazel, experimental/nomad_resource_plugin/licensedevice/cmd/nomad_license_plugin/main.go, experimental/nomad_resource_plugin/licensedevice/mock_test.go, experimental/nomad_resource_plugin/licensedevice/plugin.go, experimental/nomad_resource_plugin/licensedevice/plugin_test.go, experimental/nomad_resource_plugin/licensedevice/sqldb/BUILD.bazel, experimental/nomad_resource_plugin/licensedevice/sqldb/sqldb.go, experimental/nomad_resource_plugin/licensedevice/types/BUILD.bazel, experimental/nomad_resource_plugin/licensedevice/types/types.go, go.mod, go.sum, lib/str/BUILD.bazel, lib/str/pointer.go
This PR implements some of the top-level plugin logic:
* A "main" is added that looks like the main in the Nomad-provided
skeleton example
* `PluginInfo`, `ConfigSchema`, `SetConfig`, and `Fingerprint` are
implemented with high-level logic
* Unit tests for `Fingerprint` are added
This PR also defines interfaces for `Reserver` (how the plugin
communicates reservations) and `Notifier` (how the plugin receives
notifications that license state has changed, including from jobs on the
same node as well as jobs from other nodes). An implementation is
stubbed out for a postgres-backed table, and mocks are used for the
plugin unit tests.
Tested: unit tests added
=> device plugin: Add internal interfaces, some plugin impl

scripts/gee, scripts/gee.md
Setting `GEE_ENABLE_PRESUBMIT_CANCEL=1`` in the environment enables an
experimental gee feature that causes gee to kill a running presubmit job just
before pushing a change into a PR that modifies origin/branch (ie. an operation
that normally triggers a new presubmit job to start).
Tested: Manually tested.
* No effect when running `gee commit` in a branch without a PR.
* No effect when running `gee commit` in a branch with a PR but no outstanding changes.
* Successfully kills the gcloud job when running `gee commit` in a branch with a PR and
with outstanding changes.
=> gee: add GEE_ENABLE_PRESUBMIT_CANCEL feature

experimental/nomad_resource_plugin/licensedevice/BUILD.bazel, experimental/nomad_resource_plugin/licensedevice/mock_test.go, experimental/nomad_resource_plugin/licensedevice/plugin.go, experimental/nomad_resource_plugin/licensedevice/plugin_test.go, experimental/nomad_resource_plugin/licensedevice/sqldb/sqldb.go, experimental/nomad_resource_plugin/licensedevice/types/BUILD.bazel, experimental/nomad_resource_plugin/licensedevice/types/types.go
This change implements the `Reserve` method in terms of the interfaces:
* calling `Reserve` will attempt to lock specific license instances in
the DB
* upon success, the information on which license handle files to mount
into the task are returned
Tested: added basic unit test
=> device plugin: Implement `Reserve`

experimental/nomad_resource_plugin/licensedevice/schema/create_tables.sql
This change adds SQL to define two tables:
* `license_state` tracks state of each license
* `license_state_log` tracks changes to the `license_state` table, to
ease debugging
The SQL includes minimal comments for some fields that may not be
self-explanatory.
Tested: TODO
=> licensedevice plugin: Add SQL table definition 

scripts/gee
User exposed this bug: if a PR is marked as a draft, and then closed, github
labels it as state=CLOSED and isDraft=True.  Gee's old logic confused this
with an open PR with isDraft=True.  This new logic treats state as primary
and isDraft as secondary.
Tested: manual testing
```
gcd -m testing_gee
vi gee
gee commit -a -m "blah blah blah"
gee pr_make  # a draft PR
gh pr close
gee pr_make  # works now.
```
=> gee: handle closed PRs that are also drafts

scripts/gee
I noticed that `gee bisect` fails when searching for commits if any of the `git log --since` operations
returns an empty set (ie. during the holidays).  This PR detects and handles this condition.
Tested: Manualy testing in my local client.
=> gee bisect: handle absence of commits

scripts/gee, scripts/gee.changelog.md, scripts/gee.md
Sometimes I have a lot of PRs that I need reviews for.  To help my reviewers,
it's useful to generate a list of open PRs in text format, suitable for pasting
into a chat message or email.
This PR adds a "--text" option to "gee lspr" to generate this.  It further
enhances the lspr functionality by reporting presubmit check status to
the report.
Tested:
```
$ ./gee lspr --text
* #1009: gee: add "--text" option to lspr
2024-01-02 REVIEW_REQUIRED Checks pending.
https://github.com/enfabrica/internal/pull/1009
* #1005: a test draft PR
2023-12-18 REVIEW_REQUIRED DRAFT Checks passed.
https://github.com/enfabrica/internal/pull/1005
* #840: //proxy/ptunnel:go_default_test: tagged no-presubmit
2023-02-01 REVIEW_REQUIRED Checks passed.
https://github.com/enfabrica/internal/pull/840
* #378: gee: …
```
=> gee: add "--text" option to lspr

bazel/astore/defs.bzl
`http_archive` allows specification of a `patch_tool`.  Even though the
underlying `patch` function invoked by `astore_package` supports the
`patch_tool` attribute, our existing `astore_package` is missing support for
this attribute.
This PR adds that attribute so that it will be easier to migrate `http_archive`
rules to `astore_package` rules.
Tested: existing rules stil pass.
In an `internal` repo, verified that `patch_tool` attribute worked using
```
$ bazel sync --override_repository=enkit=${HOME}/gee/enkit/astore_package_patch
```
=> bazel/astore/defs.bzl: make astore_package compatible with http_archive

lib/heapdump/BUILD.bazel, lib/heapdump/heapdump.go
This change adds a thin wrapper around `pprof` to make dumping multiple heap dumps to files easier from our code, in order to aid debugging of memory usage.
Tested: used temporarily; appears to work
=> lib: Add `heapdump` library

bazel/init/stage_1.bzl, bazel/init/stage_2.bzl, bazel/init/stage_3.bzl, bazel/init/stage_4.bzl
This change adds a dependency on `rules_oci` to facilitate the migration away from `rules_docker`. A single image pull of `@golang_base` is created as `@container_golang_base` (named differently so they can both coexist for a short time) as a test that the rules are working.
Tested: `bazel build @container_golang_base//...` works
Jira: INFRA-9240
=> bazel: Add `rules_oci` to WORKSPACE

bb_reporter/BUILD.bazel, bestie/server/BUILD.bazel, infra/k8s_dummy/BUILD.bazel, machinist/mserver/cmd/BUILD.bazel, monitor/BUILD.bazel, shims/buildbuddy/cmd/BUILD.bazel
This change migrates all images built in this repo to use `rules_oci`
rules instead of `rules_docker` rules. Thankfully, all images built in
this repo today used hermetic rules, so there is an easy migration
path.
For rules that used `container_image`, there is a simple translation to
`oci_image`.
For rules that used `go_image`, there are extra transforms:
* `pkg_tar` must be used to prep the layer data. All data was put into
`/enfabrica/bin` to avoid conflicting with top-level dirs.
* `entrypoint` (and possibly `cmd`) must be set on the resulting image
to maintain compatibility with `go_image`.
When translating `oci_push` rules, `latest` was chosen as a remote tag
to be uniform across the repo.
Though `gcr.io` is going to be deprecated soon, the images are not moved
to a separate …
=> docker: Migrate image build to oci_* rules 

.vscode/settings.json, lib/bazel/commands/BUILD.bazel, lib/bazel/commands/commands.go, lib/bazel/commands/target_list.go, lib/bazel/commands/target_list_test.go, lib/bazel/commands/testdata/success.json, monitor/BUILD.bazel, third_party/bazel/src/main/java/com/google/devtools/build/lib/buildeventstream/proto/BUILD.bazel
This change adds a `bazel invocations` subcommand to interact with bazel invocation data from Buildbuddy/Buildbarn. The first subcommand implemented is `list-targets`, to provide an easy way to list targets that were aborted (which is not immediately visible on the Buildbuddy UI).
This command is spelled:
```
enkit bazel invocations list-targets --invocation-id <id>
```
which will list all targets, grouped by status and then sorted alphabetically.
The command can be shortened:
```
enkit bazel inv lt -i <id>
```
Only tests of a particular status can be shown, with the `--status-filter` flag:
```
enkit bazel inv lt -i <id> --status-filter=incomplete
```
The command prints a pretty list when connected to a TTY; otherwise, it simply lists the targets matching the filter.
---
Note: This …
=> enkit: Add `bazel invocations list-targets` subcommand

scripts/gee
Burned an hour helping a user who was having trouble pulling a PR, eventually
root-caused the issue to `gh repo set-default -view` being set to something
unexpected.
This PR adds code to `gee diagnose` to detect this issue, and `gee repair`
to fix this issue.
Tested: Manually did `gh repo set-default jonathan-enf/enkit` and then
ran `gee repair` and watched gee fix the issue.
=> gee: check/fix default-repo for user

bes_publisher/buildevent/service.go, bes_publisher/buildevent/service_test.go
This change will allow users to set
`--build_metadata=build_tag:<TAG>=<VALUE>` (where `<TAG>` and `<VALUE>` are user-specified) and will propagate these as `bt:<TAG>`/`<VALUE>` pairs on BES event messages propagated through PubSub. This will in turn allow e.g. the DV BES publisher to be configured to listen for multiple builds without going over the 256-char limit.
Tested: Added unit tests
Jira: INFRA-9511
=> bes_publisher: Propagate user-specified tags in event attributes

scripts/gee
Previously, gee would treat `gee commit --amend` like any other commit
operation.  It would try to integrate changes from origin before pushing
the amended commit, leading to merge conflicts.
The new functionality will detect that the user is amending the head
commit.  This means gee will need to force-push after amending head,
but gee does so in a way that adds extra checks and rebase opportunities
to try to make it harder to accidentally overwrite/discard upstream
commits.
The new functionality is:
1. if gee sees that the user is trying to amend the head commit, it will
first check origin to see if origin is ahead of head. If origin is ahead of
the local branch, the user is given the option of rebasing from origin
-- otherwise, gee will abort and no commit is created.
2. the `git …
=> gee: improve commit --amend support

scripts/gee, scripts/gee.changelog.md, scripts/gee.md
Tested: new PR creation template looks like this:
Tested:
ASSIGNEES: amichalol ccontavalli jonathan-enf minor-fixes
#
=> gee pr_make: assign assignees

bazel/go_repositories.bzl, experimental/nomad_resource_plugin/licensedevice/BUILD.bazel, experimental/nomad_resource_plugin/licensedevice/cmd/nomad_license_manage/BUILD.bazel, experimental/nomad_resource_plugin/licensedevice/cmd/nomad_license_plugin/BUILD.bazel, experimental/nomad_resource_plugin/licensedevice/cmd/nomad_license_plugin/main.go, experimental/nomad_resource_plugin/licensedevice/plugin.go, experimental/nomad_resource_plugin/licensedevice/plugin_test.go, experimental/nomad_resource_plugin/licensedevice/sqldb/BUILD.bazel, experimental/nomad_resource_plugin/licensedevice/sqldb/sqldb.go, go.mod, go.sum, proxy/BUILD.bazel
This change adapts the incoming `hclog.Logger` and sets it as `slog`s default logger, so that slog can be used throughout the codebase without logging to stdout/stderr accidentally.
Nomad requires that device plugins not log to stdin/stdout, using the supplied logger object instead. One way to comply is to plumb this logger object throughout, or make it global; both have drawbacks:
* loggers pollute function signatures
* polluted function signatures make said functions more tedious to test
* linked code may use other logging libraries that are not aware of this constraint
By following this method, we ensure that the global logger future library code is likely to use doesn't break the plugin's contract, while also keeping function signatures clean.
Other diffs in this PR are the result of …
=> licensedevice: Set incoming logger as slog's default

bazel/init/stage_1.bzl
This change updates the rules_oci version so that the `config` field can be used in `oci_pull`. Besides updating the `rules_oci` external repo to stay up-to-date, the `config` field may be required to fix the permissions issue in postsubmits. Currently, some postsubmits are failing due to a 401 permissions error pulling containers from `gcr.io`. Setting the `config` field to point to a docker `config.json` might solve the issue.
Tested:
- `bazel build --override_repository=enkit=$HOME/enkit //infra/puppet:puppet_server_image` to test that container builds are not broken with the newer version of `rules_oci`
JIRA: INFRA-9736
=> Update rules_oci to support docker config

scripts/gee, scripts/gee.changelog.md
In a chat group, someone suggested an improvement to the flow to follow when
rebasing the child branch of a branch that has been merged.  This PR captures
that improvement: to update the child branch with all of the commits of the
unsquashed parent branch, before using `rebase --onto` to move only the new
commits from the child branch on top of master.
Tested: manually testing this for a week or so in my own work.  I am my own
guinea pig.
=> gee: improve rebasing of children of submitted PRs

experimental/nomad_resource_plugin/licensedevice/schema/create_tables.sql
Errors came up when reserving a license whose id was longer than 16 characters.
Tested: altered table in production
=> The license ID is greater than 16 characters, use text.

bazel/init/stage_1.bzl, bazel/init/stage_2.bzl, bazel/init/stage_3.bzl
This change adds `rules_proto_grpc` rules to the repository, which may make it easier to integrate protobuf and grpc generated code between this repo and third-party repos.
Specifically, we are running into an issue integrating Python-generated protobuf code from this repo with Python-generated protobuf code from the googleapis repo that this may help resolve.
According to the matrix [here](https://bazel-contrib.github.io/SIG-rules-authors/proto-grpc.html#the-ruleset-options), these rules seem like the best-supported option.
Tested: no
Jira: INFRA-9986
=> WORKSPACE: Add rules_proto_grpc

bazel/init/stage_1.bzl, bazel/init/stage_2.bzl, bazel/init/stage_3.bzl, third_party/buildbuddy/proto/BUILD.bazel
This change migrates the Python proto targets for Buildbuddy protos to
use rules_proto_grpc rather than the old rules from the protobuf repo.
Tested: manually built against targets in internal; doesn't break builds
Jira: INFRA-9986
=> buildbuddy: Use rules_proto_grpc protobuf rules

third_party/buildbuddy/copy.bara.sky
This change updates the buildbuddy proto copybara to copy more relevant protos, so that we can keep the protos up-to-date with the currently-running Buildbuddy version.
Now that Buildbuddy has been updated, the protos we're coding against are outdated, and we're not able to view responses properly. When importing the updated protos, it's evident that they've expanded their proto definitions greatly, so we need to increase the number of protos we're importing. This change imports the set of protos required by `invocation.proto` transitively. A follow-on PR will perform the actual import and BUILD file adjustments.
Jira: INFRA-9987
=> buildbuddy: Update proto copybara

experimental/nomad_resource_plugin/licensedevice/schema/create_tables.sql
This avoids being unable to delete a license if there are log lines attached to it.
Jira: INFRA-10034
Tested: in production
=> Remove foreign key constraint on log table

scripts/gee
Old behavior: `gee pr_make` would auto-assign "@me" if no assignees are specified,
even if the PR is a draft.  New behavior: if pr is marked as a DRAFT, won't
auto-assign "@me".
Tested: testing now by creating a draft PR with no assignees.  update: it worked!
=> gee: don't auto-assign @me if PR is a DRAFT

bes_publisher/buildevent/service.go, bes_publisher/buildevent/service_test.go
This change modifies how "build tags" are propagated as BES pubsub message attributes.
Previously, passing `--build_metadata=build_tag:foo=bar` would add a Pubsub attribute of `bt:foo` = `bar` on all BES pubsub messages for this build.
The problem is that filtering on `bt:foo` is not possible due to the `:` character.
This change replaces `:` with `__` which is a legal character to filter on when creating Pubsub subscriptions, and won't get conflated with single `_` characters in the key.
Tested: unit tests only
Jira: INFRA-10127
=> bes_publisher: Fix propagation of build tags

machinist/cmd/BUILD.bazel
ARM targets are needed for some lab machines; this PR adds targets to build machinist for ARM, and to push an ARM build to astore.
Tested: pushed non-official build to astore via target
Jira: INFRA-10256
=> machinist: Add ARM binary targets

experimental/nomad_resource_plugin/licensedevice/cmd/nomad_license_manage/main.go, experimental/nomad_resource_plugin/licensedevice/docker/docker.go, experimental/nomad_resource_plugin/licensedevice/sqldb/sqldb.go
1) Add --reserve test to license manager.
2) If available, use the NOMAD_JOB_ID as the user process.
Jira: INFRA-10205
Tested: with test tool and in production for the job id.
=> Use nomad_job_id as the user process in the table.

bazel/utils/container/BUILD.bazel, bazel/utils/container/container.bzl
The `container_image` and `container_push` rule dynamically generate targets which bazel references relative to where the target was created. This change explicitly declares the full repo path to dependencies of targets that are dynamically generated so that bazel knows the correct path to resolve.
Tested:
- `bazel run --override_repository=enkit=$HOME/enkit //infra/puppet:puppet_server_image_exec`
- `bazel run --override_repository=enkit=$HOME/enkit //infra/puppet:base_puppet_server_image_builder -- --noclean_build_check`
- `bazel run --override_repository=enkit=$HOME/enkit //infra/puppet:puppet_server_image_push -- --noclean_build_check`
JIRA: INFRA-9581
=> Update visibility so the internal repo can reference enkit targets

bazel/init/stage_3.bzl, bazel/init/stage_4.bzl, bb_reporter/BUILD.bazel, bestie/server/BUILD.bazel, flextape/server/run.sh, infra/cloudbuild_staging/enkit_bazel_postsubmit.yml, infra/cloudbuild_staging/enkit_postsubmit.tf, infra/k8s_dummy/BUILD.bazel, machinist/example/deployment/docker-compose.yml, machinist/mserver/cmd/BUILD.bazel, monitor/BUILD.bazel, monitor/docker-compose.yml, proxy/BUILD.bazel, shims/buildbuddy/cmd/BUILD.bazel
This change updates container build/push targets to use container rules instead of rules_oci.
Tested:
- `bazel test ...:all`
- `bazel build ...:all`
JIRA: INFRA-9581
=> Pull and push containers to/from Artifact Registry

bazel/utils/container/container.bzl
This change defines full-paths to additional targets so that `bazel query` can reference targets in the enkit repo.
Tested:
- `bazel query --override_repository=enkit=$HOME/enkit 'deps(//...)'` from the internal repo
JIRA: INFRA-9581
=> Allow bazel query from internal to reference enkit targets

bazel/utils/container/BUILD.bazel, bazel/utils/container/container.bzl, bazel/utils/container/container_pusher.py, bazel/utils/container/muk/BUILD.bazel
This change modifies the `container_pusher` rule to generate a wrapper script to execute the tool instead of passing arguments to the tool via environment variables. Doing so allows bazel to determine the path of dependencies when targets in the internal repo execute container rules defined in the enkit repo.
Tested:
From the internal repo, I ran the following:
- `bazel run --override_repository=enkit=$HOME/enkit //infra/smoketest:disk_benchmark_image_push -- --noclean_build_check`
- `bazel run --override_repository=enkit=$HOME/enkit //infra/smoketest:infra_benchmark_image_builder -- --noclean_build_check`
JIRA: INFRA-10279
=> Artifact Registry: Generate a wrapper script to run container_pusher

bazel/utils/merge_kwargs.bzl, bazel/utils/merge_kwargs_test.bzl
Problem:
When you have a source dict like {"key": { ... another dict ...}} where
"key" does NOT exist in the destination dict, the inner dict is copied as
is, with a simple `dict(source["key"])` pretty much (outer dict is NEW,
independent, inner DICT is shared between SOURCE and DEST).
This is BAD: if the INNER dict is later modified, the SOURCE dict is also
modified. This was caught by @salil-enf in https://github.com/enfabrica/internal/pull/37246/commits/af987146705c809679404778d36b1dccfa22d4cf,
as bazel complained about a READ ONLY / FROZEN dict being modified.
In this PR:
- make dicts always recursively copied
- update unit tests
Fun fact:
The unit test was actually catching the bug, I suspect when I originally
edited it I paid attention to the first dict and last dict, but not
the …
=> bazel/utils/merge_kwargs.bzl: fix latent bug in merging dicts or dicts

scripts/gee, scripts/gee.md
Saves time by allowing the user to specify a last-known good commit, if known.
Tested: manually tested in another branch.
```
$ gee bisect --good d9aa369ca8 bbsim //mcu/mps/poc/csr:gpio_example_test
CMD: /usr/bin/git worktree add -f /home/jonathan/gee/internal/BISECT_bs2_724084
Preparing worktree (new branch 'BISECT_bs2_724084')
Updating files: 100% (20044/20044), done.
HEAD is now at d537d2a23e jg_superlint: fail on error, fix a failing command (#38124)
Created /home/jonathan/gee/internal/BISECT_bs2_724084
CMD: /usr/bin/git reset --hard bs2
HEAD is now at d537d2a23e jg_superlint: fail on error, fix a failing command (#38124)
CMD: /usr/bin/git bisect start
status: waiting for both good and bad commits
CMD: /usr/bin/git bisect bad
status: waiting for good commit(s), bad commit known …
```
=> gee bisect: add --good option

bazel/init/stage_1.bzl
This change updates `rules_oci` to a newer version which may contain a fix that allows the `oci_pull` rule to download container images from Artifact Registry using the `docker-credential-gcr` tool for authentication: https://cloud.google.com/artifact-registry/docs/docker/authentication#token
Tested:
- `bazel run --override_repository=enkit=$HOME/enkit //infra/puppet:puppet_server_image_push -- --noclean_build_check`
JIRA: INFRA-10547
=> Update rules_oci to v1.7.5

CODEOWNERS
This change removes ex-employees from the CODEOWNERS file and replaces them with Matt Hallmark.
Tested:
- None
JIRA: INFRA-10680
=> Remove ex-employees from the CODEOWNERS file

bazel/linux/defs.bzl, bazel/linux/platforms/BUILD.bazel, bazel/linux/platforms/defs.bzl, bazel/linux/providers.bzl, bazel/linux/templates/kernel_tree.BUILD.bzl, kbuild/v2/README.adoc, kbuild/v2/kpub-astore, kbuild/v2/scripts/amd64-build-publish.sh, kbuild/v2/scripts/archive-bazel-deb.sh, kbuild/v2/scripts/archive-deb.sh, kbuild/v2/scripts/arm64-build-publish.sh, kbuild/v2/scripts/build-debs.sh, kbuild/v2/scripts/build-kernel-release.sh, kbuild/v2/scripts/build-kernel-tree.sh, kbuild/v2/scripts/gen-bazel-meta2.sh, kbuild/v2/scripts/init-build.sh, kbuild/v2/scripts/lib.sh, kbuild/v2/scripts/repo-deb.sh, kbuild/v2/scripts/upload-deb.sh, kbuild/v2/scripts/upload-kernel-build.sh
This is now ready for review.
To actually build enf_core.ko for aarch64 requires the following PR from the internal repo:
https://github.com/enfabrica/internal/pull/40341
Note: internal PR 40341 refers to kernel artifacts that were built by this enkit PR.
Also I tested building a top of master internal enf_core.ko using this enkit to make sure this enkit was backwardly compatible.  It is. So outside of review comments, this should be able to merge without breaking the current internal master.
=> Add support for cross compiling enf.ko for aarch64

bazel/astore/defs.bzl
See individual commit messages. This adds/implements logic to automatically
retry failed astore downloads.
- astore: remove long addressed TODOs.
- bazel/astore: add logic to retry failed download commands.
- bazel/astore: improve the astore_download rule to retry multiple times.
=> bazel/astore/defs.bzl: automatically retry failed downloads

scripts/gee, scripts/gee.md
This PR:
* turns on auto-cancellation of presubmits by default
* improves detection of running presubmits by relying on `gcloud builds list`
rather than `gh pr list`.
* Promotes the functionality to a command `gee pr_cancel` for easier use
and testing.
Tested:
```
$ gee pr_cancel
CMD: gcloud --project=cloud-build-290921 builds list --format=yaml --filter=substitutions.BRANCH_NAME=synth_check_he\ AND\ \(status=\"WORKING\"\ OR\ status=\"QUEUED\"\)
Killed 0 job(s).
$ gee rerun
$ gee pr_cancel
CMD: gcloud --project=cloud-build-290921 builds list --format=yaml --filter=substitutions.BRANCH_NAME=synth_check_he\ AND\ \(status=\"WORKING\"\ OR\ status=\"QUEUED\"\)
Killed 0 job(s).
$ gee pr_cancel
CMD: gcloud --project=cloud-build-290921 builds list --format=yaml …
```
=> gee: improves ability to cancel presubmits

bazel/linux/defs.bzl
When putting down the aarch64 transition rule for kernel modules, set
the `visibility` and `tags` from the kwargs of the parent rule.
Signed-off-by: Curt Brune <curt@enfabrica.net>
=> aarch64 kernel modules: include 'visibility' and 'tags' from parent rule

scripts/gee, scripts/gee.changelog.md, scripts/gee.md
This PR cleans up a previous mistake.  I thought `gcloud builds cancel` outputted messages
to stdout, but it turns out the only message I care about is written to stderr, and everything
written to stdout can be discarded.
Tested: tested in my own work environment.
=> gee: clean up gcloud builds cancel output

bazel/utils/container/muk/muk.proto, bazel/utils/container/muk/muk.py
This change updates the `muk` tool to handle container builds based on the Rocky Linux distro.
Tested:
- `bazel run --override_repository=enkit=$HOME/enkit //infra/dev_container/mojave:mojave_base_image_builder -- --noclean_build_check` builds a new container from https://github.com/enfabrica/internal/pull/41200
JIRA: INFRA-8859
=> Support Rocky Linux in muk

bazel/linux/platforms/defs.bzl
This patch makes the aarch64 transition public by removing the leading
underscore from the name.  This allows external repos to also use this
transition.
=> aarch64 kernel modules: make aarch64 transition public

bazel/utils/container/container.bzl, bazel/utils/container/container_pusher.py
This change fixes a bug where users were able to build and push containers to the staging repo using the `--official` flag without having to specify the `--noclean_build_check`. This change also prints the full container image path and sha256 once it is promoted from the staging repo to the prod repo.
Tested:
- `bazel run --override_repository=enkit=$HOME/enkit //infra/dev_container/mojave:mojave_dev_image_push -- --promote us-docker.pkg.dev/enfabrica-container-images/infra-prod/dev_container/hw_dev/mojave@sha256:873f80e3cd99f3e9138ffd4fa916358f057e637f4205877f74616cf60ed4653e`
- `bazel run --override_repository=enkit=$HOME/enkit //infra/dev_container/mojave:mojave_dev_image_push -- --official`
JIRA: INFRA-10676, INFRA-10675
=> Correct container push and promote bugs

bazel/init/stage_1.bzl, tools/mdfmt/BUILD.bazel
This will let us use `expand_template` and speed up the NCCL build.
Tested with presubmit on the main enf repo.
=> Update bazel_skylib to 1.7.1

kbuild/v2/scripts/build-kernel-release.sh, kbuild/v2/scripts/build-kernel-tree.sh
This PR adds two defaults with flags to the `build-kernel-tree.sh`
script, which are convenient for kernel development.
1. `-c` -- perform a clean build, removing the output directory.  This
is off by default, meaning reuse any existing output directory for
incremental builds.  This is handy for development.
2. `-q` -- perform a "quiet" build.  The default is a medium noisy
build, useful during development.
The kbup-astore script, which builds and publishes artifacts to
astore, using these new flags to perform a clean builds that are less
noisy.
=> kbuild: add developer convenience defaults to build-kernel-tree.sh

scripts/gee
Using `gee` in a slightly non-standard way for the [fork-ns3 repo](https://github.com/enfabrica/fork-ns3). The `master` (which is also the github default branch) is different from the branch that we want to be doing our current development (`acf_s` branch). The way I am trying to make this known to `gee`  so that `gee rupdate` works is by adding the entry:
`acf_s acf_s ''`  in the `parents` file and changing `_add_parent_branches_to_chain()` to make this a valid condition to end the recursion.
=> gee: Exit the add_parent_branches recursion when a branch has itself as a parent

scripts/gee
Some user's environments or containers don't seem to set /opt/enfabrica/bin in
the default PATH variable.  This replaces all of gee's invocations of enkit
with a fully specified path.
PR generated by jonathan from branch gee_enkit_path.
Commits:
*  a664208 gee: explicit paths for enkit
=> gee: explicit paths for enkit

bazel/astore/astore_upload_dir.sh, bazel/astore/astore_upload_file.sh, bazel/workspace_status.sh
In our dev environment sh points to bash but this is not the default on ubuntu.
This fixes our scripts to not assume sh is bash.
This doesn't fix everything in this repo - but it's a start.
=> fix: use bash instead of sh

bazel/dive/BUILD.bazel, bazel/dive/dive.bzl, bazel/dive/dive.sh.tpl, bazel/dive/repositories.bzl, bazel/utils/container/container.bzl
Integrates [dive](https://github.com/wagoodman/dive) with bazel.
The rule takes an `oci_tarball` as input and will output a shell script that loads the tarball into a hermetic dive binary that you can `bazel run`.
See companion PR: https://github.com/enfabrica/internal/pull/44482/files
=> feat: add bazel rules for dive

bazel/linux/defs.bzl
Background:
A single kernel module rule can result in building multiple modules: one per
platform supported x one per kernel supported.
- When a kernel module depends on another kernel module, it implicitly depends
on ALL the artifacts produced by the other kernel module.
So for example, if I'm building a kernel module for one kernel one platform
only, any other module this module depends on will actually be built for ALL
platforms and for ALL kernels the other module is DEFINED for. Even if not
needed.
After this PR:
- The dependency graph is pruned so that only dependencies in the same platform
and same kernel are carried on.
Tested:
bazel aquery //driver/ib:enf-ubuntu-impish-generic-enf_ib
Without --override_repository=...:
[...]
Inputs: [ …
=> bazel/linux/defs.bzl: better prune kernel modules dependencies.

scripts/gee
The `rmbr` and `cleanup` commands are now improved:
* detects if a branch exists before attempting to delete it, avoiding the extra
"create a branch then delete it" steps.
* when deleting a list of branches, choosing not to delete a single branch doesn't
cause the entire command to immediately abort (subsequent branches will still
be deleted).
* improved messages.
Tested:
```
$ gee rmbr nem_406 nem_406_2 nem_406_3 new nightly1 our_cdc_tool our_cdc_tool2 \
pkgdef_elab pkgdef_elab_backup pr_38545 pr_40659 pr_40659_part_two pr_41554 \
pr_44633 rollback_--help rtl_4311 rtl_4540 rtl_4641 rtl_4751 rtl_4815 \
rtl_4848_limit_to_hbt rtl_4857 struct_to_pd_name synchk_codeowners \
synreport_ics synth_check_import synth_check_update testbranch vxe_covergroup \
xprop2
#################### …
```
=> gee rmbr: improvements

bazel/utils/BUILD.bazel, bazel/utils/diff_test.bzl, bazel/utils/md5sum_diff_test_test.md5sum
From the docstring:
"""md5sum_diff_test is a diff_test that diffs the md5 checksums
of a set of files.  This is useful in situations where the files
themselves are too large to keep in source control.
The md5sum value can be updated by the "update_golden" tool, just like
ordinary `diff_test`s.  Just like `diff_test`, the expected data
file must exist.
Arguments:
* name: The name of the diff_test to generate.
* srcs: The generated source files to check (the "actual" files).
* expected: The file containing the md5 checksum(s).  If omitted, the
default filename (name + ".md5sum") will be used instead.
"""
Tested: Adds an example md5sum_diff_test.
=> `diff_test.bzl`: add `md5sum_diff_test`

bazel/linux/defs.bzl
Currently, the Makefiles for kernel modules infer the bin directory from the include flags, or set it to be `bazel-out/k8-fastbuild/bin`. Both methods are brittle and the second one is incorrect if more than one platform is targeted.
This change will allow kernel modules to point to the right directories during compilation without having to resort to such brittle methods.
=> kernel_module - add paths to extra flags

bazel/init/stage_1.bzl, bazel/init/stage_2.bzl, bazel/init/stage_3.bzl, bazel/init/stage_4.bzl
This change adds the `rules_distroless` repo to `enkit` to be eventually imported by the `internal` repo.
Tested:
- `bazel test //...`
JIRA: ENGPROD-351
=> Add rules_distroless to enkit to be imported by internal

scripts/gee, scripts/gee.md
This adds a copy command that attempts to preserve git history.
Tested:
```
$ gee copy ./CODEOWNERS{,.backup}
srcs: ./CODEOWNERS
Current branch: copytest
Copy branch: _copytest_copying
CMD: /usr/bin/git checkout -b _copytest_copying
Switched to a new branch '_copytest_copying'
CMD: /usr/bin/git mv ./CODEOWNERS ./CODEOWNERS.backup
CMD: /usr/bin/git commit -m gee:\ Moved\ to\ ./CODEOWNERS.backup:\ ./CODEOWNERS
[_copytest_copying a40199902f] gee: Moved to ./CODEOWNERS.backup: ./CODEOWNERS
1 file changed, 0 insertions(+), 0 deletions(-)
rename CODEOWNERS => CODEOWNERS.backup (100%)
CMD: /usr/bin/git checkout HEAD~ ./CODEOWNERS
Updated 1 path from 11a0fe3528
CMD: /usr/bin/git commit -m gee:\ Restored\ ./CODEOWNERS
[_copytest_copying 185cc474e5] gee: Restored ./CODEOWNERS
1 file changed, 286 …
```
=> gee: add copy command

WORKSPACE, lib/client/commands/BUILD.bazel, lib/client/commands/login.go
Makes it so that `enkit login` also tries to authenticate our bbclientd CAS mounts.
=> try to auth to bb_clientd on login

bazel/dependencies/boringssl/0001-ignore-pedantic-warnings-and-move-hrss-polynomial-declarations-under-x64-flag.patch, bazel/init/stage_1.bzl, bazel/init/stage_2.bzl
Tested the boringssl repo changes for ARM64 and X86 based compilation and no issues were observed.
Verified that the enkit repo changes were picked up and the boringssl related patch got applied successfully.
Testing commands:
- clear && BAZEL_PROFILE=local bazel build
--override_repository=enkit=/home/naketi/gitrepos/enkit
//model/functional/model_test:model-grpc-e1
- clear && BAZEL_PROFILE=local bazel build
--override_repository=enkit=/home/naketi/gitrepos/enkit
//model/functional/model_test:model-grpc
=> Added external dependency to boringssl repository and added patch to fix compilations errors observed on ARM64 architecture.

bazel/dependencies/boringssl/0001-ignore-pedantic-warnings-and-move-hrss-polynomial-declarations-under-x64-flag.patch
Changed OPENSSL_X86_64 flag to __x86_64__ to fix 'undefined reference to 'poly_Rq_mul'' error
Ran below compilations and no issues were observed.
`BAZEL_PROFILE=local bazel build --override_repository=enkit=/home/naketi/gitrepos/enkit //model/functional/model_test:model-grpc-agent`
`BAZEL_PROFILE=local bazel build --override_repository=enkit=/home/naketi/gitrepos/enkit //model/functional/model_test:model-grpc`
`BAZEL_PROFILE=local bazel build --override_repository=enkit=/home/naketi/gitrepos/enkit //model/functional/model_test:model-grpc-e1`
=> Changed OPENSSL_X86_64 flag to __x86_64__ to fix 'undefined reference to 'poly_Rq_mul'' error

bazel/utils/BUILD.bazel, bazel/utils/cc_dynamic_wrapper.bzl, bazel/utils/dynamic_wrapper.bzl, bazel/utils/messaging.bzl, bazel/utils/testdata/dynamic/hello-dynamic.cc
Problem:
When using cc_foreign_rules and dynamic binaries, the generated
binary is often not runnable as is: the linker cannot find the library
at run time due to things like rpath, bazel sandboxing, or the
generated directory names.
So far we've worked around this on a need by need basis, by hard
coding paths in shell or python scripts to export the correct
LD_LIBRARY_PATH.
This PR:
defines a cc_dynamic_wrapper rule that generates a shell wrapper
for dynamic binaries that sets the LD_LIBRARY_PATH correctly
before running the binary.
This rule also embeds some convenience in updating the runfiles
definition with all the specified dependencies.
Read the .bzl file for documentation and details on how to use
the rule itself.
=>  bazel/utils: add a dynamic_wrapper rule for LD_LIBRARY_PATH.

scripts/gee, scripts/gee.changelog.md, scripts/gee.md
Previously, `gee` based all branches on `master`, which in turn was a local
clone of `upstream/master`.
Now, branches may be created with arbitrary upstream parents.  This allows
creating a branch based on, say, `master_a0` instead of `master`.  Further,
`gee` will now look at the parentage of the current branch when creating a
PR, and will use the upstream parent of the earlier branch as the "base"
branch to target for any newly created PR.
Make it easier for gee to use an upstream master other than "master".
Tested:
The following copy-pasta illustrates manually creating a local clone of upstream/glog, and then creating
a child branch of that branch, and then finally making a small change and creating a PR.  The generated PR
uses "enkit/glog" as the base branch for merging the PR.
```
$ …
```
=> gee 0.2.51: add support for non-standard base branches

scripts/gee, scripts/gee.changelog.md
A user had an issue where they ran `gee config enable_bcompare` but didn't
notice the warning message and instructions indicating that `bcompare` still
needed to be installed in their container. This PR fixes that issue by failing
to enable bcompare if bcompare is not installed (an error instead of a
warning).
While we're here, let's update to bcompare5 anyway.  Dark mode!
Tested: manually tested by creating a merge conflict and invoking the gui
mergetool to resolve it.
=> gee: update support for bcompare

bazel/dependencies/grpc/use_hermetic_py_headers.patch, bazel/init/stage_1.bzl, bazel/init/stage_2.bzl
TL;DR - This patch should fix the issue that pops up from time to time where grpc's python stuff breaks due to having python 3.12 installed on the system.
Going forward we should try to stamp out our usage of `python_configure` and `local_config_python`. This is a step in that direction.
After filling up my disk I had to `bazel clean --expunge` and started noticing some interesting side effects -
My builds started failing with a familiar error where grpc picks up python 3.12 headers which have an API break:
```sh
bazel-out/k8-fastbuild/bin/external/com_github_grpc_grpc/src/python/grpcio/grpc/_cython/cygrpc.cpp: In function 'size_t __Pyx_PyInt_As_size_t(PyObject*)':
bazel-out/k8-fastbuild/bin/external/com_github_grpc_grpc/src/python/grpcio/grpc/_cython/cygrpc.cpp:132754:55: error: …
```
=> fix: make grpc use hermetic python headers

scripts/gee, scripts/gee.changelog.md
While testing `gee` I noticed that `gee codeowners` was producing an incorrect
list of reviewers.  The root cause turned out to be PR #1088, which allows
for arbitrary upstream branches to be used for any given chain of branches.
As a result, `gee codeowners` was looking at the set of files that had changed
since "master" when the branch was actually a clone of "upstream/master" or
"upstream/master_a0".
This PR fixes the issue by refactoring out the code used by `gee pr_make` to
determine the correct upstream branch for a chain of PRs, and using that
upstream branch to determine the set of changed files to apply against the
CODEOWNERS rules.
I also added an `--upstream` option to `gee get_parent` to make it easier
to report the "ultimate upstream parent" information.
Tested: Tested …
=> gee codeowners: fix bug introduced by multi-master feature

scripts/gee, scripts/gee.changelog.md
I was cleaning up a previous PR and accidentally missed a spot where UPSTREAM_PARENT was
replaced by DEST_BRANCH.
Tested: Manually testing mkpr
=> gee mkpr: fix a mistake in previous PR

tools/codegen/codegen.py, tools/codegen/tests/test.template
This extension allows jinja2 scripts to emit text to standard logging during
code generation. This feature will ease the debugging of jinja2 templates.
Tested:
```
$ bazel build :gen-test-actual-gen
INFO: Analyzed target //tools/codegen/tests:gen-test-actual-gen (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
INFO: From Generating "tools/codegen/tests/gen-test.actual":
I0924 17:26:28.055019 140036723234624 codegen.py:118] tools/codegen/tests/test.template:5: bar
Target //tools/codegen/tests:gen-test-actual-gen up-to-date:
bazel-bin/tools/codegen/tests/gen-test.actual
INFO: Elapsed time: 0.725s, Critical Path: 0.63s
INFO: 2 processes: 1 internal, 1 linux-sandbox.
INFO: Build completed successfully, 2 total actions
```
=> codegen: add `tostderr` filter

bazel/enkit/defs.bzl
This change imports the `command` rules from the `multirun` external repo so that multiple bazel run targets can be executed with command line arguments.
Tested:
- `bazel run //infra/dev_container/hw_dev_v3/tests:update_all`
JIRA: ENGPROD-809
=> Add the command rules for multirun

bazel/dependencies/boringssl/0002-commentout-fips-module-AARCH64-declarations.patch, bazel/init/stage_1.bzl
**Unit Testing:**
**Command:** `BAZEL_PROFILE=local bazel build --config=gcc-13-aarch64 --override_repository=enkit=/home/naketi/gitrepos/enkit //model/functional/model_test:model-grpc-agent-aarch64`
**Binary:** `bazel-bin/model/functional/model_test/model-grpc-agent-aarch64`
(default-dev-env)naketi@penguin:~/gitrepos/E1$ file bazel-bin/model/functional/model_test/model-grpc-agent-aarch64
bazel-bin/model/functional/model_test/model-grpc-agent-aarch64: ELF 64-bit LSB executable, ARM aarch64, version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, not stripped
**Regression Testing:**
**Command:** `BAZEL_PROFILE=local bazel build --override_repository=enkit=/home/naketi/gitrepos/enkit //model/functional/model_test:model-grpc-agent`
**Binary:** …
=> Commented out AARCH64 related AES symbols to resolve boringssl->crypto->fipsmodule related linking errors.

scripts/gee, scripts/gee.md
Previously, "gee vimdiff" tried to be clever and just run vimdiff to diff files
within two work trees.  This fails if the parent is a remote branch, which is
now the default behavior for gee 0.2.51.
To fix this, gee no longer tries to be clever and instead relies on the "git
difftool" command internally.  Additionally, "gee vimdiff" is now renamed "gee
difftool", though the old command is still supported for backwards
compatibility.  Additionally, instead of forcing use of vimdiff, the currently
configured difftool is used.
This PR also includes some `gee config` cleanup: the user is allowed to select
between vim and neovim as a difftool.  `gee config default` will now select
`gee config enable_nvim` if nvim is installed, otherwise `gee config
enable_vim` is selected.
Tested: Manually ran …
=> gee vimdiff: now uses "git difftool"

bazel/dependencies/boringssl/0001-move-hrss-polynomial-declarations-under-x64-flag.patch, bazel/init/stage_1.bzl
Some of the changes in boringssl external repository are not needed after upgrading GCC version to GCC-13 form GCC-10. So, reverting the changes.
Tested the boringssl repo changes for ARM64 and X86 based compilation and no issues were observed.
Verified that the enkit repo changes were picked up and the boringssl related patch got applied successfully.
**Testing commands:**
```
clear && BAZEL_PROFILE=local bazel build --override_repository=enkit=/home/naketi/gitrepos/enkit //model/functional/model_test:model-grpc-agent-e1
clear && BAZEL_PROFILE=local bazel build --override_repository=enkit=/home/naketi/gitrepos/enkit //model/functional/model_test:model-grpc-agent
```
=> Reverted unwanted changes made to fix ARM64 based compilation errors in boringssl external repository

bazel/dependencies/rules_foreign_cc_module_linker_flags.patch, bazel/init/stage_1.bzl
Fixes bazel's linker flags not being passed to CMake module library targets - e.g.:
```cmake
add_library(foo MODULE)
```
This can lead to surprising behavior - see: https://github.com/enfabrica/internal/blob/5ac4068d3afad4a662962740981dde0764972c98/bazel/dependencies/rdma-core.BUILD.bazel#L47
Further we can remove the hardcoded linker flags in the above target.
We should merge this if upstream takes the fix: https://github.com/bazel-contrib/rules_foreign_cc/pull/1308.
Once we upgrade it can be removed.
=> fix(rules_foreign_cc): pass linker args from toolchain to module libs

bazel/dependencies/dropbear.BUILD.bazel, bazel/dependencies/libz.BUILD.bazel, bazel/init/stage_1.bzl
This PR adds zlib as a dependency. The default behavior is to use the zlib installed on the system. However, we may need to build zlib when cross compiling.
=> [SF-1038] Add support for zlib dependency

bazel/linux/platforms/BUILD.bazel, bazel/linux/platforms/defs.bzl
`kernel_module` targets were still silently building against our previous aarch64-linux cross compiler based on `bazel_embedded` instead of our new hand rolled one.
To fix this I've moved the `gcc-13` constraint into this repo so and made it a constraint of the `kernel-aarch64` platform.
This aligns the constraints setting of all the aarch64-linux platforms.
=> fix(bazel): make kernel module builds use gcc-13

bazel/utils/BUILD.bazel, bazel/utils/diff_test.bzl, bazel/utils/md5sum_diff_test_archive_test.md5sum
It's better to md5 checksum the contents of archives than the archives themselves.
Tested: Added a new test for checksumming archives, it passes.
=> md5sum_diff_test: improve handling of archives.

enkit/BUILD.bazel
This change compiles the `enkit` binary for arm64-linux to be used on Ampere servers and other ARM-based machines.
Tested:
- `bazel run //enkit:deploy`
- `curl -Lo ~/bin/enkit https://astore.corp.enfabrica.net/d/tools/enkit-arm64-linux`
JIRA: ENGPROD-866
=> Compile enkit for arm64-linux

bazel/dependencies/dropbear.BUILD.bazel
Linking dropbear statically doesn't work well because libnss (which we depend on via glibc) uses dynamic modules.  Dropbear authors recommend an alternative libc for static linking.
While at it, make some error messages go away.  These:
```
2024-11-12 20:01:35.241 SERR [qemu-acf01-host01-dropbear-215]:  [248] Nov 12 20:01:35 lastlog_openseek: Couldn't open /var/log/lastlog: Permission denied
2024-11-12 20:01:36.842 SERR [qemu-acf01-host01-dropbear-215]:  [247] Nov 12 20:01:36 syslogin_perform_logout: logout(pts/2) returned an error: No such file or directory
```
=> Dropbear fixes

bazel/dependencies/dropbear/0001-allow-blank-password.patch, bazel/dependencies/dropbear/0002-override-authorized-keys.patch, bazel/dependencies/dropbear/0003-ignore-user-s-shell.patch, bazel/init/stage_1.bzl
In the spirit of adding options to ignore passwords, etc also ignore the shell (useful in case it is set to `nologin`).
Update Dropbear while I'm looking at it anyway.
=> dropbear: add an option to ignore the user's shell

.bazelrc, MODULE.bazel, bazel/init/stage_1.bzl, bazel/utils/testdata/remote/with-all-inputs.files_to_copy.expected
Despite the branch name, this does what it says in the title.
Along the way, I found that it requires an explicit specification of C++ version >= C++14, so I added that to the .bazelrc.
All tests under [internal] //ib, //driver, and //sdk perform as before this change if I incorporate it in the main repository (with one necessary change to one line of code).
=> Update googletest to v1.15.2

bazel/utils/container/ubuntu_base.sh
Recommended packages are generally too heavy for containers.  We lost this flag when transitioning to the debootstrap build.
=> debootstrap: Do not install recommended packages

faketree/exec/BUILD.bazel, faketree/exec/exec_test.go
Prior to this change, `exec_test` was testing the version of `faketree` baked into the dev container, rather than a version built from the current source. Not only is this surprising, it doesn't work outside the dev container.
This change adds the from-source `faketree` binary as a data dependency, so that the test can find it using the `runfiles` library and run it directly. Additionally, some of the usages of the `assert` library are cleaned up to make the test easier to read.
Tested: test passes outside dev container
=> faketree: Fix exec_test failure outside dev container

.bazelrc, bazel/utils/container/container.bzl
As per [this comment](https://github.com/enfabrica/enkit/pull/1138#pullrequestreview-2446816475), base images in private registries are going away soon. In the meantime, `bazel test //...` when the user cannot pull images from these registries causes build failures; while `--keep_going` can be used to get some test results, it can be hard to spot real build failures among the expected ones.
This change modifies the `container_image` and `container_push` macros to add the `manual` tag to all generated targets, so that they aren't built unless specified by their specific label on the command line. This should fix the `bazel build //...` case for external users, while still allowing container images to be built and pushed as normal (since container image pushes are typically done via `bazel …
=> bazel: Force `container_image` targets to be tagged as `manual`

scripts/gee
Previously:
gee gcd -B upstream/master
would fail with an obscure error "git worktree" generated error message.
Now, it fails with a clear error indicating that the target branch name
argument was unspecified.
Tested: manually tested.
=> gee gcd: improve gcd to fail if target branch isn't specified

scripts/gee
Previously, `gee whatsout` would fail in branches created with `gee pr_checkout`.
```
$ gee whatsout
CMD: /usr/bin/git diff --name-only upstream/refs/pull/49674/head...pr_49674
fatal: ambiguous argument 'upstream/refs/pull/49674/head...pr_49674': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
WARNING: Command /usr/bin/git diff --name-only upstream/refs/pull/49674/head...pr_49674 failed with exit code 128
```
This PR creates a more consistent mapping from refspecs onto commit ids, so that commands will work consistently
regardless of whether the parent branch is local or remote.
```
$ ~/gee/enkit/fix_whatsout/scripts/gee whatsout
CMD: /usr/bin/git fetch upstream
CMD: /usr/bin/git …
```
=> gee whatsout: fix bug in pr branches

scripts/README.md, scripts/gee
While using my unreleased test version of gee, I see that my previous change
introduced a new bug into gee.  When another user pushed a commit into my PR,
`gee up` did not properly pull this new commit from origin into my local
branch.
The fault turned out to be my implementation of `_get_parent_head_commit`,
where I had hardcoded the remote name "upstream" instead of parsing the remote
specification correctly. This is now fixed.
Tested: I used the web interface to add a documentation-only commit to this
branch in origin, and ran `gee up`.  I watched gee pull the commit from origin
as expected.
=> gee bugfix: pulling new commits from origin

scripts/gee
A recent change broke rebasing of child branches:
```
CMD: /usr/bin/gh pr merge --squash --body-file /tmp/pr.message.n9uRON.txt --repo enfabrica/internal jonathan-enf:release_api_a0_rust
✓ Squashed and merged pull request enfabrica/internal#49753 (API release: enabling rust rules)
...
CMD: _gee_get_all_children_of release_api_a0_rust
WARNING: The following branches contain the commits that were just
WARNING: squash-merged, and need to be rebased to avoid future
WARNING: merge conflicts: first_recipe_migration release_api_a0_random_csr_multigen
Rebase child branches now? (Y/n)
CMD: /usr/bin/git show-ref refs/heads/release_api_a0_rust-unsquashed
WARNING: Command returned non-zero exit code: 1
```
The problem is my good friend `_get_parent_head_commit` only worked for
branches, not tags, and …
=> gee pr_submit: fix rebasing of child branches

scripts/gee, scripts/gee.changelog.md, scripts/gee.md
Github Badger stopped working for me, and I can't seem to fix it, so I decided to replicate
that functionality in gee's git-aware bash prompt.
gee's prompt now adds an "ASSIGNED_PRs" count to the prompt if that count is non-zero.
```
(int:python_and_rust_migration S=84, ASSIGNED_PRs=6)[1518] ~/gee/internal/python_and_rust_migration
$
```
If the count is zero, the prompt remains uncluttered:
```
(enk:gee_assigned_prs S=2)[1152] ~/gee/enkit/gee_assigned_prs
$
```
While I was here, I also improved the way that "gee lspr" reports PRs.  In
particular, it now lists PRs using the full URL instead of just the PR number,
making the URL clickable in the standard terminal. Additionally, PRs that fail
presubmit checks are now annotated appropriately.
```
(int:python_and_rust_migration S=84, …
```
=> gee: improve prls, git-aware prompt

astore/server/main.go, auth/proto/auth.proto, auth/server/auth/auth.go, auth/server/auth/auth_test.go, auth/server/auth/factory.go
Look at the individual commits, especially at the last one.
Tl;Dr: once the PR is merged, the auth server will start logging authentication
related events in a format suitable to define log based metrics on gcp and
app engine.
This is in preparation for the next PR, that will improve the logic in auth.go
to make it more resilient to misbehaving clients/applications, and less susceptible
to connection exhaustion by avoiding long lasting connections.
- astore, auth: consistently propagate and use logger.
- auth/server/auth/factory.go: run of go fmt.
- auth/server/auth/auth.go: make GetChannel private.
- auth: add minimal documentation on auth.proto and server/auth/auth.go.
- auth/server: start logging authentication requests and events.
=> auth/server: introduce more verbose logging (... for counters).

auth/server/auth/auth.go, auth/server/auth/auth_test.go
Please look at the commit message of individual commits.
It's a set of commits to harden the auth server.
The main improvments here are:
1. added fuzz testing of the auth server API, which highlighted
cases were golang routines can end up leaked or deadlocked.
2. address all cases highlighted by the fuzz testing.
Note that most of those cases are unlikely to be hit for real.
3. reduces the incidence of a slow known memory leak.
- auth/server: harden against misbehaving clients and users
- auth/server: drop jars once consumed.
=> astore/auth/server: hardening of server code.

auth/server/auth/auth.go, auth/server/auth/auth_test.go, auth/server/auth/factory.go, lib/client/commands/login.go
Currently, the auth server and client relies on long lived connections
(up to 30 minutes per connection).
With the default appengine connection limit of max_concurrent_requests of 10,
this means if 10 users do enkit login and walk away from the connection, the
server is hosed for ~30 minutes.
Although this limit was increased to the max a while back in our deployment,
let's start rolling out changes so we can start using short lived connections
instead (deployment requires users moving to a new client, which will take time).
Additionally, we move the client side timeout and retry handling to be
configurable with our default flag infrastructure, which will allow us
to tune those values via flag push on astore server without asking users for an
upgrade in the future.
See individual commits …
=> auth/client and server: adjust timeout handling.

bazel/linux/kunit/kunit_json.py
This change updates the import path to the kunit_parser as a result of the python 3.12 upgrade.
Tested:
- `bazel test //...`
- `bazel build //...`
JIRA: ENGPROD-987
=> Update import path of the kunit_parser

bazel/init/stage_1.bzl
This change updates the protobuf version so that test targets under the systest and ib directory can run without crashing. This is required for https://github.com/enfabrica/internal/pull/51203
Tested:
- `bazel test --override_repository=enkit=$HOME/enkit //systest/... //ib/... --test_tag_filters=-broken,-no-presubmit,-flaky`
JIRA: ENGPROD-987
=> Update protobuf version

scripts/gee, scripts/gee.md
Add a gee wrapper around cherry-pick that adds additional logging of what has
been integrated.
Tested: Used to create  https://github.com/enfabrica/internal/pull/52037 and
https://github.com/enfabrica/internal/pull/52088
=> gee: add pick command

scripts/gee, scripts/gee.md
This PR allows the user to enable automerge for newly created PRs.
The PR template now includes these lines:
Tested: manually testing on this very PR.
Well, it didn't work, but only because of the configuration of the enkit
repo.  It works for internal repo PRs.
```
CMD: /usr/bin/gh pr merge --auto --squash
GraphQL: Pull request Auto merge is not allowed for this repository (enablePullRequestAutoMerge)
WARNING: Command /usr/bin/gh pr merge --auto --squash failed with exit code 1
```
AUTOMERGE  # To enable automatic merging when merge requirements are met
=> gee pr_make: add automerge feature

lib/bazel/target.go
For some rules, the attribute generator_location had the full path to the temporary worktree, thus having a different hash between the two worktrees.
We ignore the path for this case.
Jira: ENGPROD-1034
Tested: run on same commit returns zero results, run on small commit returns small number of results
=> Attribute generator_location had full path in it

bazel/init/stage_1.bzl
This change updates `rules_pkg` to 1.0.1 to support compatibility with python 3.12.
Tested:
- `bazel run //infra/dev_container/hw_dev_v3:chromebook_dev_image_dev_repo_push`
=> Update rules_pkg to 1.0.1

scripts/gee, scripts/gee.md
Some cherry-picked commits turn into empty commits when merged, if the same
change was made separately to the local branch.  This causes `git mergetool` to
exit instantly, but the subsequent `git cherry-pick --continue` operation to
fail.  This version of gee detects and handles that condition.
Also, improved documentation.
Tested: manually tested.
=> gee pick: improve docs, handle empty commits

bazel/dependencies/grpc/fix_includes_warning.patch, bazel/init/stage_1.bzl
Recently upstream grpc has tried to refactor how includes are done in their builds - however the new way they're trying to do includes is going to be illegal in future versions of bazel resulting in nauseating warnings spamming the terminal during builds.
We will simply revert this commit until upstream gets around to properly fixing it.
commit: https://github.com/grpc/grpc/commit/06eda49d45a2697e1726e6802759c4fc5c09997c
=> fix(grpc): revert include changes that cause annoying bazel warnings

bazel/init/stage_1.bzl
This reverts commit 0dd8ea78ac78edf62e5bc8e9190648d0886625a7.
`rules_pkg` seems to have introduced some regressions that break our presubmits.
=> Revert "Update rules_pkg to 1.0.1 (#1176)"

BUILD.bazel, bazel/linux/BUILD.bazel.tpl, bazel/linux/defs.bzl, bazel/linux/repository.bzl
Extends our Linux kernel build rules to enable building and testing against a locally built kernel
instead of the prebuilt sdk's from our artifact store.
Bazel currently requires 3 main integration points with a build of the Linux kernel:
- A `vmlinuz` image (supplied by `kernel_image` targets)
- A `filegroup` containing the in tree Linux kernel modules
- A path to a Linux kernel build tree (obj dir)  for building a kernel module against - (typically supplied by `kernel_tree` target)
This change enables users to point bazel to locally built versions of these artifacts.
A new repository rule: `local_kernel_package` has been written that will import a local kernel install into bazel:
(in `WORKSPACE`):
```bazel
load("@enkit//bazel/Linux:repository.bzl", "local_kernel_package") …
```
=> bazel: kernel: enable using local builds of the linux kernel

bazel/init/stage_1.bzl, bazel/utils/yaml.bzl
This change implements a custom bazel rule that converts JSON to YAML required by: https://github.com/enfabrica/internal/pull/52398
Tested: 
- `bazel build --override_repository=enkit=$HOME/enkit //infra/networking/...` in the internal repo
JIRA: INFRA-11467
=> Add json_to_yaml rule

bazel/linux/BUILD.bazel.tpl, bazel/linux/defs.bzl, bazel/linux/repository.bzl
A couple of improvements for local kernel development:
- Allows having multiple installs under `~/rootfs` by adding `{version}` to glob.
- Allows overriding `version` with KVER environment variable.
Also includes a small adjustment to protect against cache poisoning. The local
kernel build tree is now an undeclared input so requiring the user passes an
absolute path for `--@enkit//:kernel_dir` ensures two users builds wont collide
with each other. This is of course not bullet proof.
=> Local kernel development improvements

scripts/gee
This fixes an issue Hila was experiencing.
Problem:
```
$ gee pr_checkout 51143
$ gee rmbr pr_51143
fatal: ambiguous argument 'upstream/refs/pull/51143/head...pr_51143': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```
Under the hood, gee was running:
```
git rev-list --left-right --count 'upstream/refs/pull/51143/head...pr_51143'
```
Because `upstream/refs/pull/51143/head` is a tag, not a branch, git rejects
this command.  The fix is to perform a fetch from upstream for that tag,
creating a "FETCH_HEAD" virtual branch that can be used in the rev-list
operation.
This modifies gee to re-use the existing `_git_rev_list_counts` function,
and fixes that function to robustly handling tags …
=> gee: fix rmbr of branches created with pr_checkout

scripts/gee, scripts/gee.changelog.md, scripts/gee.md
This PR updates gee to 0.2.54, and adds one new feature:
`gee pr_checkout` now supports a `-n` flag, that allows the
user to specify a branch name instead of using the default
`pr_NNN` branch name.
Tested:
```
$ gee pr_checkout -n foo_bar 1167
CMD: /usr/bin/git worktree add -b foo_bar -f /home/jonathan/gee/enkit/foo_bar master
Preparing worktree (new branch 'foo_bar')
HEAD is now at f29cf6c gee: fix "gee init" bug, improve "mkbr" handling. (#1177)
Created /home/jonathan/gee/enkit/foo_bar
CMD: /usr/bin/git fetch origin
CMD: /usr/bin/gh pr checkout --force --branch foo_bar 1167
remote: Enumerating objects: 398, done.
remote: Counting objects: 100% (158/158), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 68 (delta 49), reused 66 (delta 49), pack-reused 0 (from 0) …
```
=> gee 0.2.54 release: add -n option to pr_checkout

kbuild/v2/scripts/build-kernel-release.sh
We're at the place were we need some modules to be exported from the kernel build.
Tested with:
```
$ ./enkit/kbuild/v2/kpub-astore -r <linux_fork_with_kmods_included> -s 'arm64,emulator' -v
$ enkit astore get <artifact_uuid>
$ tar xf kernel-tree-image-arm64-emulator.tar.gz
$ cd install/build/
$ find . -iname "*.ko"
./lib/crypto/libarc4.ko
./drivers/net/ethernet/microchip/encx24j600-regmap.ko
./drivers/net/ethernet/microchip/encx24j600.ko
./drivers/net/ethernet/microchip/lan743x.ko
./drivers/net/ethernet/microchip/enc28j60.ko
./drivers/net/ppp/ppp_deflate.ko
./drivers/net/ppp/ppp_mppe.ko
./drivers/net/ppp/ppp_synctty.ko
./drivers/net/ppp/pppoe.ko
./drivers/net/ppp/pppox.ko
./drivers/net/ppp/bsd_comp.ko
```
Ticket: EMU-1151
=> kbuild: include kernel modules into astore artifact

scripts/gee
@hilakarp disocvered that the following sequence was failing:
gee pr_checkout 53809
gee rmbr pr_53809
Enabling debug mode (`DEBUG=1`), I saw that a hidden `git fetch` command was failing.
The error message was being suppressed because the `--quiet` flag was being supplied.
The actual failure was:
```
$ /usr/bin/git fetch  upstream pull/53809/head:FETCH_HEAD_B; echo $?
From github.com:enfabrica/internal
! [rejected]              refs/pull/53809/head -> FETCH_HEAD_B  (non-fast-forward)
1
```
What's going on here?  gee is calling "git fetch" on up to two different branches,
each of which could potentially be in upstream.  To facilitate, gee is replacing
the normal "FETCH_HEAD" temporary tag with "FETCH_HEAD_B" and "FETCH_HEAD_P" tags.
However, these tags aren't "magic" the way FETCH_HEAD is, …
=> gee rmbr: fix deletion of pr_NNN branches

bazel/init/stage_1.bzl
This change updates `pkg_files` to 1.1.0, to (hopefully) pick up some bug fixes to `pkg_tar`.
Tested: `bazel test //...` in this repo only
Jira: REL-44
=> WORKSPACE: Update `pkg_files` to the latest release

scripts/gee, scripts/gee.changelog.md, scripts/gee.md
`gee up` was failing for some branches created with `gee pr_checkout`, with error
messages along the lines of "upstream commit was not found."
`gee` was previously performing the following steps:
```
git fetch upstream
git ls-remote upstream refs/pull/12345/head
```
The first command was intended to ensure that the local image of the upstream
repo was up to date, and the 2nd command was designed to look up the commit
associated with the upstream pull request.
The problem was: `git fetch upstream` was only fetching commits associated
with branches (ie. master), but wasn't fetching commits associated with
references.  So: ls-remote was returning the SHA of a commit that `git fetch`
had not fetched.
The simplest fix is to just tell git to fetch what we want it to fetch.
The above two …
=> gee update: fix behavior when updating PR branches

bazel/astore/defs.bzl, f/README.md, f/astore/BUILD.bazel
Shortly we may need to run multiple astore upload targets and tag said uploads with the same tag (where the tag may change on each upload). There are a few ways to do this currently, none of which are great:
* edit the BUILD files before uploading, changing the `upload_tag` attribute on each target (requires building and pushing with a dirty source tree)
* find the UIDs after pushing and tag each file (tough/impossible to do from a script today)
This change introduces a third way, by creating a custom bazel setting that can propagate an array of tags from the `bazel run` commandline.
Example:
`experimental/BUILD.bazel`:
```
load("//bazel/astore:defs.bzl", "astore_upload")
astore_upload(
name = "tags_test",
file = "home/scott/foo.txt",
targets = ["foo.txt"],
upload_tag = "v0",
)
``` …
=> bazel: Add custom bazel flag for setting astore upload tags

scripts/gee, scripts/gee.changelog.md, scripts/gee.md
Udi found a bug in gee, such that gee was reporting errors while running `gee lsbr`
that looked like this:
```
$ gee lsbranches
CMD: /usr/bin/git fetch
all_traffic         : 1 ahead, 248 behind master
cleanup             : 1 ahead, 1657 behind master
/home/udi/bin/gee: line 1460: ((: == 0 : syntax error: operand expected (error token is "== 0 ")
counters            :  ahead,  behind upstream/master
```
The issue turned out to be: the way gee was parsing "upstream/master" when constructing
the fetch request for a parent branch.  I fixed the parsing, the error went away, and
I made some other improvements to the way lsbr reports information that will make it
easier to catch this issue if something similar arises in the future.
Tested:
I confirmed that I could reproduce the problem locally, …
=> gee lsbr: fix rev-list counting of branches derived from upstream/master

gee, scripts/gee, scripts/gee.changelog.md, scripts/gee.md
I noticed that the `gee pr_cancel` functionality (that cancels running
presubmit jobs automatically when users push new commits into their PRs) was
not working.  Opened INFRA-11657 and learned that the gcloud configuration
had changed in a way that now required an additional `--region us-west1`
flag for our gcloud commands.
I added the `--region` flag and now all is well.
Tested:
```
$ gee commit --amend
CMD: /usr/bin/git add --all
Amending previous commit.
CMD: /usr/bin/git fetch
CMD: /usr/bin/git commit --amend
[mcu_channels 3a0fb73bd4] fix apb4_if names, excise non-existant feedthroughs
Date: Fri Apr 18 12:17:55 2025 -0700
2 files changed, 102 insertions(+), 100 deletions(-)
Killing any previous presubmit jobs.
CMD: gcloud --project=cloud-build-290921 builds list --region us-west1 …
```
=> gee: fix pr_cancel

scripts/gee
Update the default path for bash to gee so that it is dynamically determined by `/usr/bin/env` because the Rocky Linux container used by the PD team uses bash 5.2 built from source defined under `/usr/enfabrica/bin/bash` since the default version of bash is too old to support gee.
Tested:
- Manually modified the gee script in a Rocky Linux 8 container and executed some basic gee commands
JIRA: ENGPROD-1086
=> Update default path for bash in gee

bazel/utils/container/muk/muk.py, bazel/utils/container/muk/testdata/base_dev.Dockerfile
This change fixes an issue where URLs containing ampersands (and possibly other characters significant in bash) aren't fetched correctly, by ensuring URLs are quoted inside Dockerfile `RUN` lines.
Tested: unit tests only
Jira: REL-108
=> muk: Quote apt-key fetch URLs

BUILD.bazel, astore/client/commands/commands.go, astore/client/commands/guess.go, bazel/astore/tests/BUILD.bazel, bazel/utils/container/muk/BUILD.bazel, infra/postsubmit/proto/BUILD.bazel, kbuild/v2/BUILD.bazel, machinist/cmd/BUILD.bazel, tools/codegen/BUILD.bazel
This change ensures that `astore` subcommands print warnings to stderr by using the logger present on the root subcommand.
This should remove most `fmt.Printf`s from the astore subcommands; the only ones remaining are:
* ones printing formatted output to stdout
* ones in the `guess` subcommand, which don't (yet) use a formatter.
Tested: `bazel run //enkit -- astore ls home/scott/bin/delta --console-format=json 2>/dev/null | jq '.'` successfully allows jq to parse the output
Jira: INFRA-11623
=> astore: Print warnings to stderr

bazel/init/stage_1.bzl, bazel/init/stage_3.bzl, bazel/utils/container/container.bzl
This change updates rules_oci to the latest version to build containers.
Tested:
- `bazel test //...`
- `bazel build //...`
- Update `oci_tarball` references in the internal repo
JIRA: ENGPROD-1151
=> Update rules_oci to the latest version

.bazelrc, bazel/init/stage_1.bzl, bazel/init/stage_2.bzl, bazel/init/stage_4.bzl, bazel/utils/container/container.bzl, tools/artifact_registry_auth.sh
This change removes the `rules_docker` package in favor of `rules_oci` as the default method to pull containers from Google Artifact Registry. The gcloud auth token must be explicitly supplied to `rules_oci` via the `--credential_helper` mechanism or else there will be an auth error.
Tested:
- Pull containers from Google Artifact Registry using `oci_pull`
- `bazel build @container_golang_base @golang_base`
JIRA: ENGPROD-1151
=> Remove rules_docker

bazel/utils/container/container.bzl
This change adapts the `container_push` custom bazel rule to consume tarballs produced the new way from the latest version of `rules_oci`.
Tested:
- `bazel query --override_repository=enkit=$HOME/enkit "kind(oci_load, //...)" > $HOME/oci_load_targets.txt` from the internal repo
- `bazel build --override_repository=enkit=$HOME/enkit --target_pattern_file=$HOME/oci_load_targets.txt --keep_going` from the internal repo
JIRA: ENGPROD-1151
=> Return tarballs from oci_load targets by default

scripts/gee, scripts/gee.md
This code required a modern version of gh, but is not supported by the 2023
version of gh that is part of the dev container.
Tested:
=> gee: disable token scope checks

CODEOWNERS
This PR adds myself, carlo and jason as root owners of the enkit repo. The CODEOWNERS seems to be acting a little odd on this repo, assigning people who don't exist in this file as CODEOWNERS. I'm hoping that kicking this file a bit here will get the CODEOWNERS working.
=> codeowners: Define root owners

bazel/init/stage_1.bzl
For compatibility with containers based on ancient distros, the astore client used for `astore_uploads` is prebuilt and itself fetched from astore.
This change manually updates to a newer prebuilt version, using the same process as in https://github.com/enfabrica/enkit/pull/869.
This new version was:
* tagged with `enkit astore tag add 52hfhiuekmeqt7fv8mdkkm28hjgsrg7v v2`
* exposed publicly via astore with `enkit astore public add bazel/workspace_deps/astore bazel/workspace_deps/astore/v2 --tag=v2`
Tested: 
* `bazel build //bazel/astore/tests:test_astore_download_file` still works
* `curl https://astore.corp.enfabrica.net/d/bazel/workspace_deps/astore/v1?u=7hfw4dsxxobamx5uyvvwmnj8tpxj7yub` redirects to file (old public URL)
* `curl …
=> bazel: Update astore client used for `astore_upload` targets

lib/bazel/affected_targets_test.go, lib/bazel/target.go
`bazel query` is resilient to circular dependencies, meaning it will still run and not report them (https://github.com/bazelbuild/bazel/issues/12204#issuecomment-1154017067).  This is unfortunate, because our "affected targets" code is not able to handle a cycle and will blow up with a stack overflow.
Detect cycles when querying deps, and print the first dep that led to the cycle being discovered.  This should help debug the issue when it occurs.  Unit test included.
Context: https://chat.google.com/room/AAAAuo7llA8/LVt5EN1qWXg/LVt5EN1qWXg?cls=10
=> Detect cycles in affected target dependency graphs

.github/CODEOWNERS
Only the top level one is valid.
Jira: INFRA-11726
=> Remove .gitHub/CODEOWNERS

bazel/astore/defs.bzl
It is needed to initialize cuda packages from astore.
=> ENGPROD-1167: add output to astore_download_and_extract, 

astore/server/deploy/app.yaml
The Go runtime is currently set at 1.19, which is no longer supported and prevents us from deploying new versions. This change updates to Go 1.21, which is supported (though not the latest Go version available).
Jira: REL-180
=> astore/auth server: Update Go runtime

bazel/enkit_credential_helper/BUILD.bazel
This change adds a target to build an arm64 build for ARM-powered Linux machines.
A second target is created to ensure that we have an amd64 build (usually implied because most machines we build on are, but this is implicit behavior made explicit here). Both targets are combined into a single `astore_upload` target to build + upload both architectures in one command.
Tested: Ran the upload target; `enkit astore ls --all tools/enkit_credential_helper` shows the built artifacts
Jira: none
=> enkit_credential_helper: Add arm64 build

astore/server/astore/BUILD.bazel, astore/server/astore/retrieve.go, astore/server/astore/retrieve_test.go, astore/server/astore/util_test.go
The `/gt` astore URL endpoint performs authentication via a token in the request parameters, but currently allows access when the token is completely missing. This change causes an error to be returned instead, so that we don't allow unauthenticated access to astore artifacts.
Tested: added unit test
Jira: REL-272
=> astore: Error when token not present in requests to `/gt` endpoint

bazel/utils/container/muk/muk.py
Don't error out on an existing directory in the mkdir in muk
Jira: ENGPROD-1198
Tested: not yet
=> Allow existing directory in muk mkdir

lib/client/commands/login.go, lib/kcerts/ssh.go
This change cleans up logging in `enkit login` to facilitate debugging of the token fetch hang.
With this change, it becomes clear that the hang is due to a buildbarn request via bb_clientd after the token is fetched and saved, and has nothing to do with the auth server.
Tested: ran `bazel run //enkit -- login --loglevel-console=debug` and saw expected output.
Jira: INFRA-11783
=> enkit: Add logging around `login` hang

scripts/gee, scripts/gee.changelog.md, scripts/gee.md
`pr_push` gets an optional `--force` option.
`pr_check` gets the ability to have the user specify the PR number to check.  Additionally,
if PR number is not specified, gee now infers PR number from branch name if the branch
is named in the format "pr_NNNN".
Tested: Ran `pr_check` in three scenarios: a non-PR branch with a PR, a non-PR branch
without a PR, and a branch created by `pr_checkout`.
=> gee 0.2.60: QOL improvements to pr_check and pr_push

bazel/astore/astore_upload_file.sh, bazel/astore/astore_upload_files.py, bazel/astore/defs.bzl, f/astore/BUILD.bazel, flextape/server/BUILD.bazel
This change adds a bazel flag that, when set, will prefix all astore paths used by `astore_upload` rules with the specified prefix.
Tested: manually:
* normal upload:
```
scott-> bazel run //flextape/server:astore_push
| Created                 Creator                        Arch           MD5                              UID                              Size    TAGs
| 2025-07-24 14:19:35.376 scott@enfabrica.net            amd64-linux    f11582e0138fe6a851ca6e40dd07d1c6 o78fvrn7kkhyvyoffuawrqemzxmt5gex 14 MB   [latest]
scott-> enkit astore ls infra/flextape/flextape_server
Directly downloadable
| Created                 Creator                        Arch           MD5                              UID                              Size    TAGs
| 2025-07-24 14:19:35.376 scott@enfabrica.net …
```
=> astore_upload: Add path_prefix bazel flag

bazel/astore/defs.bzl, f/astore/BUILD.bazel
This change makes the wrapper tool for `astore_upload` rules switchable
on the command-line, which will be useful for release builds where we
want the tool to have extra behavior, and we don't want to expose this
behavior publicly.
This would look something like:
```
bazel run \
--@enkit//f/astore:uploader=//my/custom/upload:tool \
//my/astore/upload:target
```
Tested: manually; `astore_upload` rules have same behavior as before.
=> astore_upload: Make wrapper tool switchable on the commandline

lib/bazel/affected_targets.go
It is excessive optimization for serial affected targets calculation
=> ENGPROD-1249: do not use custom repository cache in serial affected targets

bazel/utils/container/muk/BUILD.bazel
The `aspect_rules_py` rules appear to introduce wrapper scripts that are breaking `muk` usage by downstream rules. This change reverts us back to the built-in bazel rules for `muk` to unblock users while a more permanent fix is investigated.
Tested: `bazel run` of `nonhermetic_image_builder` target with `--help` flag prints help text, as expected:
```
bazel run --override_module=enkit=/home/scott/dev/enfabrica/enkit <target_redacted> -- --help
```
Jira: INFRA-11884
=> muk: Fall back to builtin `py_*` rules

scripts/gee
Something changed recently in our github configuration, causing the way I was parsing
`gh pr checks` output to start failing.  This PR corrects the regression.
Tested: Manually running `gh pr_checks`.
=> gee: fix "gh pr checks" parsing
