lib/khttp/kclient/client.go, lib/khttp/krequest/request.go, lib/khttp/protocol/get.go
Specifically:
- add support for creating POST requests, and posting data.
- add support for setting raw headers.
- add support for using a cookie jar.
=> lib/khttp: more flexibility in performing outbound requests.

bazel/linux/defs.bzl, bazel/linux/kunit/BUILD.bazel, bazel/linux/kunit/LICENSE, bazel/linux/kunit/README.md, bazel/linux/kunit/kunit.py, bazel/linux/kunit/kunit_config.py, bazel/linux/kunit/kunit_kernel.py, bazel/linux/kunit/kunit_parser.py
Add a directory partially mirroring the Linux kernel kunit tools subdir and use that as the default tap parser for the kernel_test bazel rule.
=> Introduce kunit tap parser

kbuild/utils/README.md
This partially solves https://github.com/enfabrica/enkit/pull/18#discussion_r577764664.
=> kbuild/utils/README: Add hint to kernel_test rule

bazel/linux/README.md
This should solve the UML part of  https://github.com/enfabrica/enkit/pull/18#discussion_r577764664.
=> bazel/linux/README: kernel image instructions

machinist/client/BUILD.bazel, machinist/client/README.md, machinist/client/machinist/BUILD.bazel, machinist/client/machinist/factory.go, machinist/client/machinist/machinist.go, machinist/client/main.go, machinist/rpc/BUILD.bazel, machinist/rpc/actions.proto, machinist/rpc/machinist.proto, machinist/server/BUILD.bazel, machinist/server/controller/BUILD.bazel, machinist/server/controller/controller.go, machinist/server/controller/factory.go, machinist/server/main.go
Basic .proto file defining the structure of the communication
protocol, and an initial implementation of a ping message.
=> [WIP]: initial skeleton of client and server for machinist.

.gitignore, bazel/go_repositories.bzl, go.mod, go.sum, lib/kcerts/BUILD.bazel, lib/kcerts/certs.go, lib/kcerts/certs_test.go
Does the following things:
- adds golang.org/crypto/ssh package 
- adds CA generation
- adds intermediate cert generation
- adds ssh key generation 
- bullet proof testing
FEEDBACK
When creating an RSA certificate, should there by an option to password encrypt it?
=> Add kcerts and tls/rsa certificate support

bazel/go_repositories.bzl, go.mod, go.sum
Adds https://github.com/miekg/dns as a dependency
=> add mkieg/dns as dependency

astore/rpc/auth.proto
Changes the shape of the general auth resopnse to include signed certificates
=> Change Shape of the Auth Response

astore/server/auth/BUILD.bazel, astore/server/auth/credentials.go, astore/server/main.go, proxy/ptunnel/commands/BUILD.bazel
Since I've been using github oauth while testing it's been nice.
Right now google defaults are hard coded.
=> Add oauth-type flag to auth server 

enkit/main.go, lib/kcerts/ssh.go, lib/kcerts/ssh_test.go, proxy/ptunnel/commands/BUILD.bazel, proxy/ptunnel/commands/agent.go, proxy/ptunnel/commands/ssh.go
Not the most complicated, would appreciate feedback on the printing sections of the code.
=> Adds SSH commands to enkit, under enkit ssh agent --<commands>

kbuild/utils/generate_custom_archive.sh
When generating a kbuild archive for astore, first verify a few
attributes of the kernel build directory, including:
- the kernel was built in the source directory
- the kernel was configured successfully
- the kernel was built successfully
Signed-off-by: Curt Brune <curt@enfabrica.net>
=> generate-kernel-archive: verify the kernel build directory

proxy/ptunnel/commands/BUILD.bazel, proxy/ptunnel/commands/agent.go, proxy/ptunnel/commands/agent_test.go
Adds in the ability arbitrarily exec command with the agent's environment variables set.
=> Adds Enkit  Agent --  <Command> Feature

bazel/linux/README.md
=> Point to the correct custom kernel archiving script.

kbuild/utils/README.md, kbuild/utils/release-kernel.sh
=> Add automation for enf and UML kernel releases.

lib/client/client.go
Token and identity could only be loaded from config space.
After this change:
Token and identity can now be supplied from the command line,
or directly via environment variables (kflags magic).
=> lib/client: provide ability to supply token and identity from CLI.

BUILD.bazel
In this PR:
- add instructions on how to use gazelle via bazel.
- add instructions on how to use buildifier
=> Add instructions on how to use bazel with gazelle and buildifier

WORKSPACE, astore/server/deploy/app.yaml, bazel/deps.bzl
In this PR
- Updates rules_go to the latest version
- Updates the go version to 1.15
=> Update go and rules_go

WORKSPACE
Version 1.15 results in error.
=> Update golang version in WORKSPACE

lib/config/defcon/default.go, lib/config/directory/homedir.go, lib/config/marshal/interface.go, lib/config/remote/remote.go, lib/config/store.go
No functional change. Just added comments explaining how the
library works, and how to use it.
=> lib/config: better documentation.

proxy/httpp/interface.go
Long story:
RFCs mandate how capitalization is handled in HTTP headers.
Specifically, mandate that headers have "Name-Whatever-Value"
kind of capitalization. "Name-WhatEver-Value" is not legal,
as "name-whatever-value".
golang base libraries use RFC compliant capitalization in
all outbound requests. So ...-WebSocket- headers are rewritten
as ...-Websocket-...
RFC compliant web servers accept them, but, non-RFC compliant
webservers may choke on them.
In this PR:
- add a configuration parameter to force golang web server to
be non compliant, by allowing to configure a header to map to
a differente value in a case sensitive way.
Unfortunately, there is no way to just preserve the case
provided by the client in a sane way, as the golang libraries
sanitize the headers in the first few lines of …
=> proxy/: add ability to remap headers in case sensitive way.

scripts/gee, scripts/gee_aliases.bash, scripts/gee_test.sh
- Initial version of gee, a git wrapper script.
- Fixing origin/upstream mixup.
- Initial version of gee, a git wrapper script.
- Add instructions on how to use bazel with gazelle and buildifier (#124)
- Fixing origin/upstream mixup.
=> gee initial version

scripts/gee
This PR integrates some additional gee changes that were pending in another
branch.
Specifically:
- Added bash_setup command.
- Fixed abnormal termination warning.
- Fix abnormal termination if "git commit" fails.
- Disregard rebase subshell exit code.
- Added help text to bash_setup script.
=> Small gee fixes.

scripts/BUILD.bazel, scripts/gee
- repair: a little more verbose.
- add share command
- lspr can inspect other users
- figlet logo
- more aliases
=> "share" command + cosmetics

scripts/gee, scripts/gee.orig
=> gee: add -b option to gcd

scripts/gee
- Make lspr more pretty.
- resurrect lost change
- check gh auth access.
- check ssh-add exit codes.
- "commit" command checks for upstream changes before pushing.
- fix call to _check_remote_branch
- fix typo
- lsbr: report changes in origin branch.
- "update" now also integrates changes from origin.
- Added back key generation.
- Don't rely on SSH_AGENT_PID.
- Deal with deleted directories.
- make gcd more robust.
- Fix gcd -b option.
- Improve gcd behavior outside of gee branch.
- Handle deleted directories.
- fix _fix_cwd
- fix fix for _fix_cwd
- fix fix fix for _fix_cwd
- gee: enable shallow clone.
=> gee: enable shallow clone

scripts/bkup
This is a rough cut of a backup utility.
It installs and uses rclone to back up a users home directory to GCP, and can
restore individual files.  This seems to work and is ready for further testing.
- first version of bkup
- added ls, cat, restore commands
=> backup utility

scripts/bkup
Add "diff" command to show differences between local files and backups.
Redirect all log messages to stderr.
=> bkup: add diff command, logging

scripts/gee
The "cleanup" command deletes old branches that have no local changes or unmerged commits.
=> gee: added "cleanup" command

scripts/gee
Crud, I was sloppy and broke gee in top of tree.  This is a quick-fix to repair
gee.
Along the way, I fixed all other shellcheck warnings so that gee is now
shellcheck-clean.
=> gee: Fix unterminated if statement

scripts/gee
The list of commands is now rendered in tabular form, making it more legible.
=> gee: purely cosmetic improvement to "help commands" output

astore/server/main.go, lib/oauth/BUILD.bazel, lib/oauth/types.go, scripts/BUILD.bazel
- Creates an interface for authenticators. This should be nice for testing later on, 
- Lets you choose on oauth2  whether or not to use the multi oauth2 flow. It defaults to not using it.
=> Adds in useMultiFlag

lib/retry/retry.go
In this PR:
- adding documentation for lib/retry, explaining what it is, and
how to use it.
- update the errors provided by lib/retry to implement the Unwrap
errors interface in newer versions of go.
No functional change, except the library is slightly simpler
to use.
=> lib/retry: add package documentation, unwrap.

scripts/gee
- add support for vimdiff and vscode
- mark emacs support as TODO
=> git: support vimdiff and vscode as merge tools.

kbuild/utils/release-kernel.sh
=> kbuild: Adapt kernel release script to Ubuntu flavour config layout

lib/bazel/commands/commands.go
This change allows the commandline to take a manually-specified
repository root, rather than always using the present working directory.
This will be necessary when running enkit in Cloud Build from a Docker
container, as the Cloud Build file will need to direct enkit to where
the repo is mounted in the container.
Tested:
```
~/dev/enkit/bazel-bin/enkit/enkit_/enkit \
bazel \
affected-targets \
list \
--start=master~1 \
--end=master
~/dev/enkit/bazel-bin/enkit/enkit_/enkit \
bazel \
affected-targets \
list \
--repo_root=/home/bminor/dev/enkit \
--start=master~1 \
--end=master
```
Jira: INFRA-52
=> enkit bazel affected-targets: Add repo_root flag

scripts/gee
PR generated by jonathan from branch gee_prompt.
Commits:
*  8f4a5f0 merge in git-prompt.sh
*  947b8e8 Updated bash_setup help text
=> gee bash_setup: add function to enable git-aware bash prompts.

lib/bazel/exec.go
Packages fetched via Cargo by bazel race on the $CARGO_HOME directory,
which has a known global default, when multiple bazel invocations are
in-flight at once.
This change sets $CARGO_HOME to a tempdir on each invocation, so that
invocations never collide here.
Tested: Fixes flakiness issue in internal presubmit - goes from failing
50% to 0% out of 8 runs.
Jira: INFRA-140
=> bazel presubmit: Set CARGO_HOME on all invocations

proxy/enfuse/BUILD.bazel, proxy/enfuse/types.go, proxy/enfuse/websocket.go, proxy/enfuse/websocket_test.go
- Makes a websocket connection pool
- Makes a threadsafe wrapper for reading and writing around websockets
- Create a type that determines how the pool can find it's clients.
=> Create Websocket Connection Pool

flextape/client/client.go
With this change, the flextape client logs the following to stderr:
* Upon successful license reservation, the flextape invocation ID and a
corresponding message
* While queued, the flextape invocation ID and the queue position every
30s
Tested: Ran the server, and then ran 10 clients against it locally with:
```
for i in $(seq 1 10); do (LICENSE_SERVER_IMPL=flextape bazel-bin/manager/client/client_/client localhost 6433 xilinx vivado sleep 60 &); done
```
and manually validated the output.
Jira: INFRA-139
=> flextape client: Log to stderr when queued

faketree/BUILD.bazel, faketree/README.md, faketree/faketree.go, faketree/faketree_test.go, faketree/faketree_test.sh, go.mod, go.sum
See README.md for details, faketree_test.sh, but also the
help message in faketree.go.
=> add faketree command, to provide a fake directory tree.

astore/server/BUILD.bazel, astore/server/templates/BUILD.bazel, bazel/appengine/BUILD.bazel, bazel/appengine/defs.bzl, bazel/appengine/deploy/BUILD.bazel, bazel/appengine/deploy/main.go, bazel/appengine/gcloud.sh, bazel/deps.bzl, bazel/qtc/defs.bzl
This change copies rules defined by ccontavalli/bazel-rules into
//bazel, and removes the dependency of enkit on ccontavalli/bazel-rules.
Jira: INFRA-191
=> Fork ccontavalli/bazel-rules into //bazel

scripts/gee
PR generated by jonathan from branch gee_pr_checks.
Commits:
*  f08a9cb run gh pr checks before pr submit
=> gee pr_submit: run "gh pr checks" first.

scripts/gee
Now that "gee fix" functionality has been refactored out of the "gee fix"
command, make "gee fix" a simple wrapper for invoking "fix_format.sh".
PR generated by jonathan from branch gee_fix_format.
Commits:
*  e0b5470 gee fix: now just invokes fix_format.sh
=> gee fix: now just invokes fix_format.sh

scripts/gee
PR generated by jonathan from branch gee_repair.
Commits:
*  74d3d83 gee repair: bypass startup checks.
=> gee repair: bypass startup checks.

scripts/gee
Adds support for meld as a gui mergetool.
PR generated by jonathan from branch gee_meld.
Commits:
*  5e16b88 gee: add "config enable_meld" option
=> gee: add "config enable_meld" option

lib/token/token.go
This PR is a nop: code is not changed in any way. It only adds comments
explaining the use of the library, and the use of most functions.
=> lib/token: add go docstrings.

lib/kflags/defaults.go, lib/khttp/ktest/server.go, lib/khttp/protocol/get.go, lib/oauth/oauth.go
This PR contains no code changes: only comments and documentation.
As I had to re-learn what a few functions did and how they worked,
I added docstrings on top of those functions.
=> lib/*: adding a few docstrings.

bazel/linux/run_um_kunit_tests.template
=> kunit: Redirect UML output to stdout for parser to see it

lib/kbuildbarn/BUILD.bazel, lib/kbuildbarn/README.md, lib/kbuildbarn/urls.go, lib/kbuildbarn/urls_test.go
The way to translate between bytestream urls and how to fetch them from buildbarn is a little obfuscatory. This is an attempt to document some of the current methods of translating betwene the two in code.
=> bestie: kbuildbarn url parser

lib/kbuildbarn/options.go, lib/kbuildbarn/urls.go, lib/kbuildbarn/urls_test.go
Does the following things:
* makes kkbuildbarn use more options and less eLOC. makes it so that url generation is sane.
* Tests and Develops the api for generating files
=> kbuildbarn: cut down api, add files and make more functional

proxy/nasshp/nassh.go
Background:
When reading data from TCP, one can request X bytes, but only get back
Y bytes, with Y < X, depending on how much data was received so far.
The code assumed that 4 bytes could always be read, as it was not consuming
directly from a TCP session, but through several layers that implement
various kinds of buffering.
Turns out that short reads are possible, a complete end to end test
using very short messages is showing short reads causing the session
to break and then, well, re-establishing thanks to the ability to
resume a tunnel.
In this PR:
- handle short reads correctly.
Tested:
end to end test (in a separate PR) using io.Pipe can reproduce this
with roughly one failure per MB transferred.
=> proxy/nasshp: fix short read handling.

enkit/outputs/commands.go
This change moves some flags to be persistent flags on the root `enkit
outputs` subcommand, as other sub-subcommands will eventually need
access to them.
This change also ensures that all flags are dash-separated for
consistency.
Jira: INFRA-550
=> enkit outputs: Improve flag consistency

machinist/polling/metrics.go, machinist/polling/register.go
Problem: dmesgErrs only increases, therefore should be a counter metric.
=> machinist: make dmesg errors a counter

faketree/faketree.go, faketree/faketree_test.sh
faketree would wait for its direct child to die, and then exit with its exit
status. If this child process spawned other children, it would not wait for
them to complete.
This is a problem when the parent, for example, is sending SIGTERM to the
entire process group - terminating the direct children possibly sooner than
indirect children, and returning/completing status before all are killed.
In this PR:
Add code so faketree _waits_ for its own child, and any indirect child
spawned within the namespace.
This is protected around the --wait= option, turned on by default, but
can easily be disabled with --wait=false.
Tested: simple test added in faketree_test.sh. Manually tested with
commands like:
faketree -- sh -c "(sleep 5 & (sleep 2 & sleep 5) & sleep 7) &"
To verify that …
=> faketree: wait for all child processes to die before returning.

faketree/faketree.go, faketree/faketree_test.sh
Background:
What do we do when faketree receives SIGTERM? or SIGKILL? or one
of its children does? So far, faketree has had the default behavior,
whatever it was.
Problems:
- when invoked from within bazel, test-setup.sh creates a process
group, and then sends SIGTERM to _all_ processes in the process
group to handle timeout.
But as soon as the first direct child terminates, it sends SIGKILL to _all_
processes, effectively terminating them immediately.
With no signal handling in faketree, SIGTERM causes faketree to
exit immediately, effectively triggering the SIGKILL.
This pgroup handling is also imprecise: if a child process creates its own
process group, it won't get signaled at all.
- when invoked from buildbarn - instead - an action is terminated by sending a
signal to the direct …
=> faketree: handle signals in a different way.

bazel/cloud_run/defs.bzl
This change adds attributes that allow for the ingress mode, VPC
connector, and VPC connector mode to be specified. These attributes help
ensure Cloud Run services can talk to each other without being
internet-visible.
Tested: Deleted and re-deployed bestie metrics viewing pipeline with
this change; pipeline appears to be functional.
Jira: INFRA-687
=> cloud_run_deploy: Add networking attributes

lib/bazel/affected_targets.go
Presubmit failing with PRs that fix a build graph breakage are
confusing and cause delays in landing the fix PRs. At the same time,
there is no sensible set of affected targets to build if the build graph
cannot be queried at both points, which it can't if it was broken at one
of them.
This PR adds a special-case for runs where the build graph was broken at
the start commit (as determined by the entire query failing for any
reason) and fixed at the end commit - the library returns no changed
targets and no error. This should cause the presubmit to pass with a
no-op build in this case.
This is still not a very good presubmit because it doesn't build
anything, and a warning is emitted to this effect. However, it will at
least reduce confusion with fix PRs.
Tested: not yet
Jira: INFRA-174
=> affected targets: Pass if build graph is fixed between start and end

astore/client/astore/astore.go
Currently, when querying by UID, the client sends a request with no tags
to the server, which the server interprets by defaulting a latest tag
before running the query. This causes the query to return no results
when the package with that UID is not marked `latest`.
With this change, the client will always send a request with an empty
`TagSet` when querying by UID, which the server interprets as "set no 
default". This allows queries for specific UIDs to proceed as expected.
Tested: `bazel run //enkit -- astore download --force-uid rqh8i6qspag3ynxdqdu4k33keymgmxkn --output=/tmp/test_ip.tgz --loglevel-console=debug --overwrite` now downloads the requested file instead of erroring
Jira: INFRA-830
=> astore client: Specify empty tag set when querying by ID

flextape/server/run.sh
https://enfabrica.atlassian.net/browse/INFRA-885
Testing:
- Already deployed on infra-00
=> Updated flextape hash

flextape/server/run.sh
[INFRA-901](https://enfabrica.atlassian.net/browse/INFRA-901)
Testing:
- Deployed on infra-00
=> Update flextape hash

flextape/server/run.sh
Tested: Currently deployed version
Jira: INFRA-607
=> flextape: Update hash deployed

bazel/linux/defs.bzl
In this PR:
- allow kdeps to be manually and explicitly set for a module.
This was actually in the PR description for PR556, but had
left out the commit.
- improve the macro to recursively expand dependencies to:
1) remove duplicates in expanded modules.
2) print a helpful message rather than ignore important
problems or burn out in flames.
=> bazel/linux: better error handling of recursive deps.

scripts/gee, scripts/gee.changelog.md, scripts/gee.md
gee: fix format of date used for shallow clone.
Doh: %M is minutes.  %m is month.
Tested: Validated date is now formatted correctly.
=> gee: fix format of date used for shallow clone.

lib/config/directory/BUILD.bazel, lib/config/directory/homedir_test.go, lib/karchive/BUILD.bazel, lib/kcerts/BUILD.bazel, lib/kcerts/ssh.go, lib/kcerts/ssh_test.go
Test fixes for https://enfabrica.atlassian.net/browse/INFRA-927
=> Enable Tests Broken in CI

bazel/linux/bundles.bzl
Followup from https://github.com/enfabrica/enkit/pull/605#discussion_r873988704
=> bazel/linux: make kunit_bundle templates public

bazel/linux/qemu.bzl, bazel/linux/runner.bzl
=> bazel/linux: fix kernel_qemu_run when supplied with qemu_binary

bazel/linux/runner.bzl
Make this function public. Add verbose flag to enable/disable echo and
return the corresponding label for each command.
=> bazel/linux: refactor commands_and_runtime

bazel/linux/runner.bzl
Create a new function that extracts prepare, run, and check from a
vm_bundle.
=> bazel/linux: refactor code into get_prepare_run_check

scripts/gee, scripts/gee.md
Improving the gee documentation to respond to some user questions
around performing and recovering from rebase operations.
Tested: visual inspection of generated documentation
=> gee: improve documentation around rebase operations

bazel/linux/defs.bzl
kernel_module should define its runfiles so that the following works:
kernel_module(name = "mod" ...)
sh_binary(name = "test", srcs = ["test.sh"], data = [":mod"])
Jira: https://enfabrica.atlassian.net/browse/SF-219
=> bazel/linux: fix kernel_module to define its runfiles

bazel/meson/meson.bzl
=> bazel/meson: support passing arguments to meson setup

enkit/outputs/commands.go
Currently, only one user can `enkit outputs mount` on a shared dev
machine, as when tunnels are required the local port used is hardcoded
to a single value.
This change moves the value to a flag, so that multiple people might be
able to use `enkit outputs mount` by modifying the flag value.
The flag is defaulted to the same value as the hardcoded value, to keep
this change non-breaking.
Jira: INFRA-1476
=> enkit outputs: Take local tunnel port as flag

CODEOWNERS
=> CODEOWNERS: add George Prekas to do code reviews for gee.

scripts/gee, scripts/gee.md
Convenience command for rerunning presubmits.
Tested: Tested for this PR.
=> low pri: gee pr_rerun command

proxy/ptunnel/commands/tunnel.go
Prior to this change, a tunnel could not be opened on a particular UDS path if the socket already existed, with the assumption being that there is another process potentially using that socket. Though the logic would check for this by dialing the socket and looking for failure, it would still error if the process controlling the previous socket instance had died.
With this change, the socket is aggressively removed so that the new instance can listen at that same path. The assumption is that it is rare that the old process still exists if the socket dial fails (it is more common that it was killed not-nicely, in which case removing the socket is the correct fix).
Tested: with a change to using UDS for buildbarn in internal:
* `BAZEL_PROFILE=buildbarn bazel test //guidelines/...` - creates …
=> enkit tunnel: Delete orphaned UDS sockets on start

bazel/utils/files.bzl
Background:
files_to_dir uses tar to recursively copy and preserve files
attributes, while adjusting their paths.
Problem:
In our CI pipeline, one of the most frequent causes of error
is files_to_dir failing with an error indicating that the
input file has changed while tar was processing it.
So far, I have not been able to reproduce this locally, and
by hacking the script and rule in different ways I could not
figure this out. Seems to be happening frequenlty from CI,
but even with multiple manual runs on buildbarn I had no luck.
There's a log of things I tried below.
In this PR:
As this is making our tests extremely unreliable, attempt
the copy multiple times with a short delay in case of failure.
This should paper over the issue - until we figure it out.
We could also change command …
=> bazel/utils: hack files.bzl to avoid error in CI pipeline.

bazel/linux/defs.bzl
This change will allow linking a cc_library to a kernel module without having to specify the include path explicitly in the kernel module.
Jira: https://enfabrica.atlassian.net/browse/SF-164
=> bazel/linux: kernel_module sets up include path properly

bazel/astore/defs.bzl
We currently have an `astore_download` BUILD rule, which is a tad cursed because network I/O shouldn't be done during the build phase (only during the preceding fetch phase). In practice, this rule is problematic to run on buildbarn, which doesn't have credentials to execute the required fetch.
This change creates an equivalent `astore_file` rule, to complement the existing rules (which assume the file is a tarball, and have some unpacking logic). This rule covers the usecase where the file is not a tarball, and saves us from adding release steps that involve wrapping single files into a tarball.
Some of the common downloading logic is extracted to a helper function, which helps shorten the definition of the new rule, as well as existing rules.
Tested:
* added to `WORKSPACE`:
``` …
```
=> astore: Add repository rule for downloading single file

scripts/gee, scripts/gee.changelog.md, scripts/gee.md
I'm grateful for the prompt reviews!  It helps me break up work so that the
release commit is separate from the new feature commit.
Tested: n/a
=> gee: 0.2.38 release

flextape/server/run.sh
=> flextape: updated container with latest counts

scripts/gee, scripts/gee.changelog.md, scripts/gee.md
=> gee: release version 0.2.37

scripts/gee, scripts/gee.changelog.md, scripts/gee.md
gee is pretty stable these days, this release contains a few cosmetic improvements.
Tested: I'm using this version of gee locally.
=> gee 0.2.38 release

tools/codegen/README.md, tools/codegen/codegen.py, tools/codegen/tests/d2-test.expected, tools/codegen/tests/gen-test.expected, tools/codegen/tests/test.template
This PR allows codegen to use regexes to replace patterns,
both from filters and from functions.
=> codegen: add support for regex replacements.

tools/codegen/README.md
Forgot a git push before hitting the merge button. PR fixing the error.
=> tools/codegen: fix the README file.

scripts/gee, scripts/gee.changelog.md, scripts/gee.md
=> gee: label 0.2.41 release.

flextape/server/run.sh
=> flextape: latest proto

tools/codegen/codegen.py
=> codegen: use correct syntax for raising an exception.

infra/k8s_dummy/main.go
This change adds a log statetment that executes every minute, so that it can be used to verify that logs collection works.
Tested: Ran; saw log heartbeat messages
=> k8s_dummy: Add periodic logging

bb_reporter/reporter/service.go
GKE worker nodes will propagate equivalent data in different keys of the worker metadata; this change updates the `bb_reporter` binary to recognize these keys as well.
New columns are added to capture:
* the "environment" (prod, staging, etc.)
* the "worker class": unique name for this pool
* the "worker version": when iterating on a pool, it may be nice to increment/change a different field, to gather stats on config changes over time
These are given defaults if not set; these same defaults will be used to backfill the existing data.
Tested:
* Stood up as part of internal PR
* Ran build on GKE cluster, saw appropriate entries in table
Jira: INFRA-6074
=> bb_reporter: Add support for GKE worker metadata

bestie/server/test_result.go
This change adds a metric that records HTTP success/failure + status code for each bytestream fetch.
While looking at this metric, it became clear that all fetches are returning an HTTP 200 even when the item is not found, and the stream is closing early. This might hypothetically cause any wrapper on the `io.Reader` to error. In the case of zip files, we append this error to a list in a hot loop and retry the next file, which could cause an OoM if this codepath always returns a non-EOF error. To guard against this, the code exits the loop on any zip iteration failure.
Tested: Built, deployed, no OoMs in 8h: 
Jira: INFRA-6331
=> bestie: Fix error loop; add fetch metrics

astore/client/commands/commands.go, astore/client/commands/formatter.go
This change adds a `--console-format` flag to all `enkit astore` operations, that allows for changing the table format to a machine-parseable format of choice (including JSON, YAML, TOML, etc.)
The implementation is a bit hacky, since most marshaling code is built around files and autodetection based on file extension, which doesn't exist for stdout. However, this should quickly provide more value than code that parses the existing table format.
This change also renames `MarshalFormatter` to `OpFile` to be a bit less generic, and follow Go naming convention (types that end in `er` are interface types).
Tested:
* `bazel run //enkit -- astore upload $PWD/CODEWONERS@home/scott/tmp/CODEOWNERS --console-format=json 2>/dev/null` prints expected JSON to stdout
* `bazel run //enkit -- astore …
=> enkit astore: Introduce `--console-format` flag to format stdout output

bb_reporter/reporter/service.go
This change modifies bb_reporter to:
* stop setting `INTERVAL`-typed fields in the schema (all of which are now optional)
* set `INTEGER`-typed nanosecond-duration fields in the schema (all of which are currently optional)
This means that future inserts will have the desired field set, while ensuring bb_reporter is resilient to:
* the removal of INTERVAL fields from the schema in the future
* the enforcement of INTEGER nanosecond-duration fields in the future
Tested: no
Jira: INFRA-6577
=> bb_reporter: Set integer ns fields instead of interval fields

machinist/README.md
This change updates the README to align with the direction of machinist as laid out in INFRA-9184.
Tested: N/A
Jira: INFRA-9184
=> machinist: Update README

experimental/nomad_resource_plugin/licensedevice/cmd/nomad_license_manage/main.go
with the addition of defer db.Reset(), it doesn't seem to leave connections open.
Jira: INFRA-9746
Tested: tried various combinations of success and failure, doesn't leave connections open any more.
=> Add deferred close to attempt to clean up connections

crashReport_031524_14281_quantus_21.2.2-s138_(null)_build-00_59525.log, scripts/gee, scripts/gee.changelog.md, scripts/gee.md
gee tries to use `git checkout` to select between "ours" and "theirs" when
resolving merge conflicts.  This fails to work when the file has been updated
in one branch and deleted in the other branch: the git command terminates with
a non-zero exit code, causing gee to abort with an error and leaving the user
in a merge-in-progress state.
This PR improves the behavior by detecting this condition and invoking `git mergetool`
to resolve the updated/deleted merge conflict.  (there are other ways to resolve this
merge conflict but `git mergetool` was the cleanest.)
Tested:
I created two branches: test1 and test2.  In branch test1, I modified CODEOWNERS.  In branch
test2, I deleted CODEOWNERS.
Behavior before this fix:
```
$ gcd test1
$ gee set_parent test2
test2 is the parent branch of test1
$ …
```
=> gee: improve handling of updated/deleted merge conflicts

experimental/nomad_resource_plugin/licensedevice/sqldb/sqldb.go
We found the licensedevice WaitForNotification returning an error which used to be met with a return from the goroutine. Now, forever retry to connect if it returns an error.
Jira: INFRA-10000
Tested: Locally on nomad agent
=> Change plugin to always attempt to reconnect listener

scripts/gee, scripts/gee.changelog.md, scripts/gee.md
Tested: manually tested after gh auth cert expired.
=> gee hello: check/fix gh auth status

bazel/linux/defs.bzl
By default, bazel tries to build the non-host CPU architecture targets
for pre/post-submit, which fails because they don't match the host
architecture.  This is an old problem, see INFRA-1516.
This patch adds tags to those targets to skip them for
pre/post-submit.
The "transistioned" variants of the targets are built by
pre/post-submit so no coverage is lost.
=> linux: skip non-host architecture kernel modules for CI

proxy/ptunnel/commands/agent.go
Adds an equivalent to ssh-agent -c so `enkit ssh agent` can be used on fish shell
```
enkit ssh agent csh
```
=> enkit agent: support c-sytle shells

astore/client/commands/commands.go
Cleanup after "enkit astore login" removal: c655b784a631fff5180376d63cf4e18582d45978
=> Update help to match removal of "astore login"

bazel/utils/container/bootstrap_ubuntu.sh
This change updates the container build script to restore the `/tmp` directory. Merge this first before merging https://github.com/enfabrica/internal/pull/47841
Tested:
- `bazel test --override_repository=enkit=$HOME/enkit --spawn_strategy=processwrapper-sandbox //infra/dev_container/hw_dev_v3/tests:all`
JIRA: INFRA-11202
=> Restore the /tmp directory in the dev container

bazel/dependencies/dropbear.BUILD.bazel
This PR adds a conditional `--host` argument to dropbear dependency.
=> Add host arguemtn to dropbear configuration for ARM builds

scripts/gee, scripts/gee.changelog.md
=> gee hello: check github API permissions

lib/bazel/workspace_events.go
In Bazel 6 repository name in log file has one `@`, but two in Bazel 7.
=> Fix to workspace events log parser for Bazel 6

bazel/utils/container/muk/muk.proto, bazel/utils/container/muk/muk.py, bazel/utils/container/muk/util.libsonnet
Added new command to muk.py, muk.proto to set environment variables.
Jira: ENGPROD-1198
Tested: locally
=> Add setting environment variables to muk image builder

bazel/utils/remote.bzl, bazel/utils/remote/runner.template.sh
=> Propagate env during remote_run

bazel/astore/astore_upload_files.py
local file path has to be added into JSON so we can process it when uploading information to the artifacts database
=> feat(ci): record local file path into JSON report

bazel/utils/container/container.bzl, bazel/utils/container/muk/main.py, bazel/utils/container/muk/muk.proto, bazel/utils/container/muk/muk.py
Adds support for untarring files during a docker create operation.
Jira: ENGPROD-1198
Tested: build container, worked
=> Add tar support to muk

bazel/utils/remote.bzl
Print an appropriate error message when this happens
=> Detect when a test suite is supplied to remote rule

allocation_manager/service/service.go, allocation_manager/service/unit.go
Print known topologies on AM server startup
=> [allocation_manager] Print known topologies on AM server startup

bazel/astore/astore_upload_files.py
This change causes the absolute + resolved local file path to be output in JSON, so that downstream tooling can unambiguously refer to the same file that was uploaded.
Tested:
```
scott-> bazel run --stamp //flextape/client/flextape_client:astore_push --//f/astore:output_format=json
{"Artifacts": [{"sid": "75/ph/hkhyrpm7o2m5qexuj35gjdozks3h", "uid": "6i5dzfhico3poeoa3jbtju6m7o8jfh5t", "tag": ["latest"], "MD5": "H97x1aCmugZrwjBrQFL52Q==", "size": 8950285, "creator": "scott@enfabrica.net", "created": 1752165956094527197, "architecture": "amd64-linux", "AstorePath": "infra/flextape/flextape_client", "LocalPath": "/home/scott/.cache/bazel/_bazel_scott/123c9f3701c0ccd16e4a749a4e84c054/execroot/enkit/bazel-out/k8-fastbuild/bin/flextape/client/flextape_client/flextape_client_/flextape_client"}], …
```
=> astore_upload: Output full path in JSON output
